// Auto-generated by extract.mjs from "SUNX Sense Onboarding.html".
// Edit the individual sections below; HMR will pick up changes.
import React from 'react';
import ReactDOM from 'react-dom/client';
// Babel-standalone code expected React/ReactDOM as globals.
window.React = React;
window.ReactDOM = { createRoot: ReactDOM.createRoot };

// ===== tutorial.jsx =====
// Post-onboarding tutorial — runs after "Let's get started" on slide 5
// 5 steps: Permissions → Locating → First declaration → Thank you → Health insight

const T_PRIMARY = 'oklch(0.65 0.14 230)';
const T_ACCENT  = 'oklch(0.72 0.14 155)';
const T_AMBER   = 'oklch(0.78 0.14 75)';
const T_RED     = 'oklch(0.62 0.18 25)';

const TUTORIAL_COPY = {
  en: {
    skip: '',
    steps: [
      {
        eyebrow: 'STEP 1 · PERMISSIONS',
        title: 'Three permissions to begin.',
        body: 'Sense needs your location to place you in a zone, Bluetooth to pair a Carbostar, and notifications to nudge you when your zone changes.',
        cta: 'Allow all',
      },
      {
        eyebrow: 'STEP 2 · LOCATING',
        title: 'Finding your zone…',
        body: 'Zooming from the global map down to your H3 cell. This is where your declaration will land.',
        cta: 'Continue',
      },
      {
        eyebrow: 'STEP 3 · FIRST DECLARATION',
        title: 'How does the air feel right now?',
        body: 'Tap the option that best describes the air around you. You can refine this later with a Carbostar.',
        cta: 'Send declaration',
      },
      {
        eyebrow: 'STEP 4 · CONFIRMED',
        title: 'Thank you. Your zone is live.',
        body: 'Your declaration has been verified by 3 nearby contributors and added to the SUNX Earth network.',
        cta: 'See what this means',
      },
      {
        eyebrow: 'STEP 5 · YOUR AIR · HEALTH',
        title: 'What 612 ppm means for you.',
        body: 'CO₂ is invisible — but your body knows. Here is how the air you just declared compares to known thresholds.',
        cta: 'Open my map',
      },
    ],
    perms: [
      { name: 'Location', detail: 'When in use', code: 'GPS · ZONE PLACEMENT' },
      { name: 'Bluetooth', detail: 'For PX Carbostar', code: 'BLE 5.0 · PAIRING' },
      { name: 'Notifications', detail: 'Zone alerts only', code: 'CRITICAL EVENTS' },
    ],
    declOptions: [
      { id: 'fresh', label: 'Fresh', sub: 'Outdoor, breezy', ppm: 412, color: T_ACCENT },
      { id: 'normal', label: 'Normal', sub: 'Indoor, ventilated', ppm: 612, color: 'oklch(0.78 0.14 95)' },
      { id: 'stuffy', label: 'Stuffy', sub: 'Crowded room', ppm: 980, color: T_AMBER },
      { id: 'heavy', label: 'Heavy', sub: 'Stale, foggy head', ppm: 1340, color: T_RED },
    ],
    healthBands: [
      { from: 0, to: 600, label: 'Fresh', detail: 'Outdoor baseline. Clear thinking, full focus.', color: T_ACCENT },
      { from: 600, to: 1000, label: 'Normal', detail: 'Typical indoor. Comfortable for hours.', color: 'oklch(0.78 0.14 95)' },
      { from: 1000, to: 1500, label: 'Drowsy', detail: 'Reduced concentration, mild fatigue.', color: T_AMBER },
      { from: 1500, to: 2500, label: 'Heavy', detail: 'Headaches, sleepiness, poor decisions.', color: T_RED },
    ],
    yourReading: 'Your reading',
    verified: 'verified by',
    nearby: 'nearby',
    finish: 'Open my map',
  },
  tr: {
    skip: '',
    steps: [
      {
        eyebrow: 'ADIM 1 · İZİNLER',
        title: 'Başlamak için üç izin.',
        body: 'Sense; bölgene yerleştirmek için konum, Carbostar eşlemek için Bluetooth, bölge değişimlerini haber vermek için bildirim izni ister.',
        cta: 'Tümüne izin ver',
      },
      {
        eyebrow: 'ADIM 2 · KONUM',
        title: 'Bölgen bulunuyor…',
        body: 'Küresel haritadan H3 hücrene yakınlaşıyoruz. Deklarasyonun buraya düşecek.',
        cta: 'Devam et',
      },
      {
        eyebrow: 'ADIM 3 · İLK DEKLARASYON',
        title: 'Şu an hava nasıl hissettiriyor?',
        body: 'Çevrendeki havayı en iyi anlatan seçeneği işaretle. Bunu sonra Carbostar ile inceleştirebilirsin.',
        cta: 'Deklarasyonu gönder',
      },
      {
        eyebrow: 'ADIM 4 · ONAYLANDI',
        title: 'Teşekkürler. Bölgen artık canlı.',
        body: 'Deklarasyonun, yakındaki 3 katılımcı tarafından doğrulandı ve SUNX Earth ağına eklendi.',
        cta: 'Bunun anlamı',
      },
      {
        eyebrow: 'ADIM 5 · HAVAN · SAĞLIK',
        title: '612 ppm senin için ne demek?',
        body: 'CO₂ görünmez — ama bedenin bilir. Az önce deklare ettiğin hava, bilinen eşiklerle nasıl karşılaştırılıyor?',
        cta: 'Haritamı aç',
      },
    ],
    perms: [
      { name: 'Konum', detail: 'Kullanıldığında', code: 'GPS · BÖLGE TESPİTİ' },
      { name: 'Bluetooth', detail: 'PX Carbostar için', code: 'BLE 5.0 · EŞLEME' },
      { name: 'Bildirimler', detail: 'Sadece bölge uyarıları', code: 'KRİTİK OLAYLAR' },
    ],
    declOptions: [
      { id: 'fresh', label: 'Taze', sub: 'Açık hava, esinti', ppm: 412, color: T_ACCENT },
      { id: 'normal', label: 'Normal', sub: 'Havalandırılmış', ppm: 612, color: 'oklch(0.78 0.14 95)' },
      { id: 'stuffy', label: 'Boğucu', sub: 'Kalabalık ortam', ppm: 980, color: T_AMBER },
      { id: 'heavy', label: 'Ağır', sub: 'Bayat, başağrısı', ppm: 1340, color: T_RED },
    ],
    healthBands: [
      { from: 0, to: 600, label: 'Taze', detail: 'Açık hava düzeyi. Net düşünme, tam odak.', color: T_ACCENT },
      { from: 600, to: 1000, label: 'Normal', detail: 'Tipik iç mekân. Saatlerce rahat.', color: 'oklch(0.78 0.14 95)' },
      { from: 1000, to: 1500, label: 'Uyuşuk', detail: 'Konsantrasyon düşer, hafif yorgunluk.', color: T_AMBER },
      { from: 1500, to: 2500, label: 'Ağır', detail: 'Başağrısı, uyku hâli, zayıf kararlar.', color: T_RED },
    ],
    yourReading: 'Senin değerin',
    verified: 'doğrulayan',
    nearby: 'yakın',
    finish: 'Haritamı aç',
  },
};

// ─────────────────────────────────────────────────────────────
// STEP 1 — Permissions hero (3 stacked permission cards)
// ─────────────────────────────────────────────────────────────
function StepPermissions({ dark, lang, onComplete }) {
  const c = TUTORIAL_COPY[lang];
  const [granted, setGranted] = React.useState([false, false, false]);
  const all = granted.every(Boolean);

  // Auto-cascade through perms when "Allow all" is pressed
  const grantAll = () => {
    [0,1,2].forEach((i) => {
      setTimeout(() => setGranted(g => { const n = [...g]; n[i] = true; return n; }), 350 * (i + 1));
    });
    setTimeout(onComplete, 350 * 4 + 400);
  };

  const icons = [
    // Location pin
    <svg key="loc" width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M12 21s7-6 7-12a7 7 0 0 0-14 0c0 6 7 12 7 12z" stroke={T_PRIMARY} strokeWidth="1.8"/>
      <circle cx="12" cy="9" r="2.5" fill={T_PRIMARY}/>
    </svg>,
    // Bluetooth
    <svg key="bt" width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M7 7l10 10-5 5V2l5 5L7 17" stroke={T_PRIMARY} strokeWidth="1.8" strokeLinejoin="round"/>
    </svg>,
    // Bell
    <svg key="bell" width="24" height="24" viewBox="0 0 24 24" fill="none">
      <path d="M5 17h14l-2-2v-5a5 5 0 0 0-10 0v5l-2 2zM10 21a2 2 0 0 0 4 0" stroke={T_PRIMARY} strokeWidth="1.8" strokeLinejoin="round"/>
    </svg>,
  ];

  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', gap: 10 }}>
      {c.perms.map((p, i) => (
        <div key={i} style={{
          padding: 14, borderRadius: 14,
          background: dark ? 'oklch(0.20 0.015 225)' : 'rgba(255,255,255,0.85)',
          border: `1px solid ${granted[i] ? T_ACCENT : (dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)')}`,
          display: 'flex', alignItems: 'center', gap: 12,
          transition: 'all 0.3s',
          transform: granted[i] ? 'translateY(0)' : 'translateY(0)',
          boxShadow: granted[i] ? `0 0 0 4px ${T_ACCENT}1a` : 'none',
        }}>
          <div style={{
            width: 40, height: 40, borderRadius: 10,
            background: dark ? 'rgba(140,200,255,0.10)' : 'rgba(20,90,180,0.08)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>{icons[i]}</div>
          <div style={{ flex: 1 }}>
            <div style={{ fontFamily: 'Geist', fontSize: 14, fontWeight: 600,
              color: dark ? '#fff' : '#0a1420' }}>{p.name}</div>
            <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
              color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)' }}>{p.code}</div>
          </div>
          {granted[i] ? (
            <div style={{
              width: 26, height: 26, borderRadius: '50%',
              background: T_ACCENT,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              animation: 'fadeSlide 0.3s ease-out',
            }}>
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path d="M3 7l3 3 5-6" stroke="#fff" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </div>
          ) : (
            <div style={{
              fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
              color: dark ? 'rgba(255,255,255,0.4)' : 'rgba(20,30,50,0.4)',
            }}>{p.detail.toUpperCase()}</div>
          )}
        </div>
      ))}
      <button onClick={grantAll} disabled={all} style={{
        marginTop: 10, height: 50, border: 'none', borderRadius: 14,
        background: 'linear-gradient(135deg, oklch(0.65 0.14 230), oklch(0.58 0.16 220))',
        color: '#fff', fontFamily: 'Geist', fontSize: 14, fontWeight: 600,
        cursor: all ? 'default' : 'pointer',
        opacity: all ? 0.5 : 1,
        boxShadow: '0 8px 20px rgba(20,90,200,0.3)',
      }}>{c.steps[0].cta}</button>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// STEP 2 — Locating: world → H3 zone zoom
// ─────────────────────────────────────────────────────────────
function StepLocating({ dark, lang, onComplete }) {
  const [phase, setPhase] = React.useState(0); // 0: world, 1: city, 2: zone
  React.useEffect(() => {
    const t1 = setTimeout(() => setPhase(1), 900);
    const t2 = setTimeout(() => setPhase(2), 2000);
    const t3 = setTimeout(onComplete, 3200);
    return () => { clearTimeout(t1); clearTimeout(t2); clearTimeout(t3); };
  }, []);

  const cx = 171, cy = 150;
  const cellSize = phase === 0 ? 6 : phase === 1 ? 16 : 36;
  const opacity = phase === 0 ? 1 : 0.3;

  const cells = [];
  const dx = cellSize * Math.sqrt(3);
  const dy = cellSize * 1.5;
  for (let row = -8; row < 8; row++) {
    for (let col = -8; col < 8; col++) {
      const x = cx + col * dx + (row % 2 ? dx / 2 : 0);
      const y = cy + row * dy;
      cells.push({ x, y, row, col });
    }
  }

  const yourCellIdx = cells.findIndex(c => c.row === 0 && c.col === 0);
  const labelMap = { 0: 'EARTH · GLOBAL', 1: 'ISTANBUL · CITY', 2: 'YOUR ZONE · H3 R10' };

  return (
    <div style={{ width: 342, height: 300, position: 'relative',
      borderRadius: 20, overflow: 'hidden',
      background: dark ? 'oklch(0.17 0.015 225)' : 'oklch(0.98 0.008 225)',
      border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}` }}>

      {/* breathing target rings */}
      {[0,1,2].map(i => (
        <div key={i} style={{
          position: 'absolute', left: cx - 50, top: cy - 50, width: 100, height: 100,
          borderRadius: '50%', border: `1.5px solid ${T_PRIMARY}`,
          opacity: 0.3, animation: 'ripExpand 2.4s ease-out infinite',
          animationDelay: `${i * 0.8}s`,
        }} />
      ))}

      <svg width="342" height="300">
        {cells.map((c, i) => {
          const d = Math.hypot(c.x - cx, c.y - cy);
          if (d > 150) return null;
          const isYou = i === yourCellIdx;
          return (
            <path key={i}
              d={hexPath(c.x, c.y, cellSize - 1)}
              fill={isYou && phase === 2 ? T_ACCENT : (dark ? 'oklch(0.24 0.015 225)' : 'oklch(0.94 0.01 225)')}
              stroke={isYou && phase === 2 ? T_ACCENT : (dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)')}
              strokeWidth={isYou && phase === 2 ? 2 : 1}
              opacity={isYou ? 1 : opacity * (1 - d / 200)}
              style={{ transition: 'all 0.9s cubic-bezier(.4,0,.2,1)' }}
            />
          );
        })}
        {/* center crosshair */}
        <circle cx={cx} cy={cy} r="3" fill={T_PRIMARY}
          style={{ animation: 'dotBreath 1.2s ease-in-out infinite', transformOrigin: `${cx}px ${cy}px` }} />
      </svg>

      <div style={{ position: 'absolute', left: 16, bottom: 14,
        fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
        color: dark ? 'rgba(255,255,255,0.55)' : 'rgba(20,30,50,0.55)',
        display: 'flex', alignItems: 'center', gap: 6,
      }}>
        <span style={{ width: 5, height: 5, background: T_ACCENT, borderRadius: '50%',
          animation: 'dotBreath 1.6s ease-in-out infinite' }} />
        {labelMap[phase]}
      </div>
      <div style={{ position: 'absolute', right: 16, bottom: 14,
        fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
        color: dark ? 'rgba(255,255,255,0.55)' : 'rgba(20,30,50,0.55)' }}>
        ZOOM · {phase === 0 ? 'R3' : phase === 1 ? 'R6' : 'R10'}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// STEP 3 — Declaration form (4 air-quality buttons)
// ─────────────────────────────────────────────────────────────
function StepDeclaration({ dark, lang, onComplete, setReadingPpm }) {
  const c = TUTORIAL_COPY[lang];
  const [pick, setPick] = React.useState(1); // default to Normal
  const selected = c.declOptions[pick];

  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', gap: 10 }}>
      {/* preview ring */}
      <div style={{
        padding: 16, borderRadius: 16,
        background: dark ? 'oklch(0.20 0.015 225)' : 'rgba(255,255,255,0.85)',
        border: `1px solid ${dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)'}`,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <div>
          <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
            color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)' }}>YOUR DECLARATION</div>
          <div style={{ fontFamily: 'Geist', fontSize: 22, fontWeight: 600, marginTop: 2,
            color: dark ? '#fff' : '#0a1420' }}>
            {selected.label}
            <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 11, letterSpacing: 1,
              color: selected.color, marginLeft: 8 }}>≈ {selected.ppm} ppm</span>
          </div>
          <div style={{ fontFamily: 'Geist', fontSize: 12,
            color: dark ? 'rgba(255,255,255,0.55)' : 'rgba(20,30,50,0.55)', marginTop: 2 }}>
            {selected.sub}
          </div>
        </div>
        <div style={{
          width: 48, height: 48, borderRadius: '50%',
          background: selected.color,
          boxShadow: `0 0 0 6px ${selected.color}26`,
          animation: 'haloBreath 2.4s ease-in-out infinite',
        }} />
      </div>

      {/* options grid */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
        {c.declOptions.map((o, i) => (
          <button key={o.id} onClick={() => setPick(i)} style={{
            padding: '12px 12px', borderRadius: 12, textAlign: 'left',
            background: pick === i
              ? (dark ? 'oklch(0.22 0.025 225)' : '#fff')
              : (dark ? 'oklch(0.18 0.012 225)' : 'rgba(255,255,255,0.5)'),
            border: pick === i ? `1.5px solid ${o.color}` : `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)'}`,
            cursor: 'pointer',
            display: 'flex', flexDirection: 'column', gap: 4,
            boxShadow: pick === i ? `0 4px 14px ${o.color}33` : 'none',
            transition: 'all 0.2s',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{ width: 8, height: 8, borderRadius: '50%', background: o.color }} />
              <span style={{ fontFamily: 'Geist', fontSize: 13, fontWeight: 600,
                color: dark ? '#fff' : '#0a1420' }}>{o.label}</span>
            </div>
            <div style={{ fontFamily: 'Geist', fontSize: 11,
              color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)' }}>{o.sub}</div>
          </button>
        ))}
      </div>

      <button onClick={() => { setReadingPpm(selected.ppm); onComplete(); }} style={{
        marginTop: 6, height: 50, border: 'none', borderRadius: 14,
        background: 'linear-gradient(135deg, oklch(0.65 0.14 230), oklch(0.58 0.16 220))',
        color: '#fff', fontFamily: 'Geist', fontSize: 14, fontWeight: 600,
        cursor: 'pointer',
        boxShadow: '0 8px 20px rgba(20,90,200,0.3)',
        display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
      }}>
        {c.steps[2].cta}
        <svg width="14" height="14" viewBox="0 0 14 14"><path d="M2 7h10m-4-4l4 4-4 4" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/></svg>
      </button>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// STEP 4 — Confirmation with sparkles + your reading
// ─────────────────────────────────────────────────────────────
function StepConfirm({ dark, lang, readingPpm, onComplete }) {
  const c = TUTORIAL_COPY[lang];
  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 14 }}>
      {/* big checkmark with rings */}
      <div style={{ position: 'relative', width: 200, height: 200,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        marginTop: 6,
      }}>
        {[0,1,2].map(i => (
          <div key={i} style={{
            position: 'absolute', width: 200, height: 200, borderRadius: '50%',
            border: `1.5px solid ${T_ACCENT}`,
            opacity: 0.3, animation: 'ripExpand 2.4s ease-out infinite',
            animationDelay: `${i * 0.8}s`,
          }} />
        ))}
        <div style={{
          width: 110, height: 110, borderRadius: '50%',
          background: 'linear-gradient(135deg, oklch(0.78 0.14 155), oklch(0.65 0.14 155))',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          boxShadow: `0 16px 40px ${T_ACCENT}55`,
          animation: 'haloBreath 2.4s ease-in-out infinite',
        }}>
          <svg width="48" height="48" viewBox="0 0 48 48" fill="none">
            <path d="M12 24l8 8 16-18" stroke="#fff" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        </div>
        {/* sparkles */}
        {[0,1,2,3,4,5].map(i => {
          const a = (i / 6) * Math.PI * 2 + 0.3;
          const x = 100 + Math.cos(a) * 80;
          const y = 100 + Math.sin(a) * 80;
          return <div key={i} style={{
            position: 'absolute', left: x - 3, top: y - 3, width: 6, height: 6,
            background: T_ACCENT, transform: 'rotate(45deg)',
            animation: `dotBreath 1.6s ease-in-out infinite`, animationDelay: `${i * 0.2}s`,
            transformOrigin: 'center',
          }} />;
        })}
      </div>

      {/* reading card */}
      <div style={{
        width: '100%', padding: 16, borderRadius: 16,
        background: dark ? 'oklch(0.20 0.015 225)' : 'rgba(255,255,255,0.85)',
        border: `1px solid ${dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)'}`,
        boxSizing: 'border-box',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div>
            <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
              color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)' }}>{c.yourReading.toUpperCase()}</div>
            <div style={{ fontFamily: 'Geist', fontSize: 30, fontWeight: 600, marginTop: 2,
              fontVariantNumeric: 'tabular-nums', letterSpacing: -1,
              color: dark ? '#fff' : '#0a1420' }}>{readingPpm}<span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 12, color: T_ACCENT, marginLeft: 6 }}>ppm</span></div>
          </div>
          <div style={{
            fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.2, lineHeight: 1.5,
            color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)', textAlign: 'right',
          }}>
            {c.verified.toUpperCase()}<br/>
            <span style={{ color: T_ACCENT }}>3 {c.nearby.toUpperCase()}</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// STEP 5 — Health insight: CO₂ scale with your reading marked
// ─────────────────────────────────────────────────────────────
function StepHealth({ dark, lang, readingPpm }) {
  const c = TUTORIAL_COPY[lang];
  const max = 2500;
  const pct = (ppm) => Math.min(100, (ppm / max) * 100);

  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', gap: 14 }}>
      {/* scale bar */}
      <div style={{ position: 'relative', height: 38, marginTop: 4 }}>
        <div style={{
          position: 'absolute', inset: 0,
          display: 'flex', borderRadius: 8, overflow: 'hidden',
          boxShadow: '0 1px 4px rgba(0,0,0,0.08)',
        }}>
          {c.healthBands.map((b, i) => (
            <div key={i} style={{
              flex: b.to - b.from,
              background: b.color, opacity: 0.85,
            }} />
          ))}
        </div>
        {/* your reading marker */}
        <div style={{
          position: 'absolute', left: `${pct(readingPpm)}%`, top: -8,
          transform: 'translateX(-50%)',
          display: 'flex', flexDirection: 'column', alignItems: 'center',
        }}>
          <div style={{
            padding: '3px 8px', borderRadius: 6,
            background: dark ? '#fff' : '#0a1420',
            color: dark ? '#0a1420' : '#fff',
            fontFamily: 'Geist Mono, ui-monospace, monospace',
            fontSize: 10, fontWeight: 600, letterSpacing: 0.5,
            whiteSpace: 'nowrap',
          }}>{readingPpm} ppm</div>
          <div style={{
            width: 0, height: 0,
            borderLeft: '5px solid transparent', borderRight: '5px solid transparent',
            borderTop: `6px solid ${dark ? '#fff' : '#0a1420'}`,
          }} />
        </div>
      </div>
      {/* tick marks */}
      <div style={{ display: 'flex', justifyContent: 'space-between',
        fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
        color: dark ? 'rgba(255,255,255,0.4)' : 'rgba(20,30,50,0.4)', marginTop: -10 }}>
        <span>0</span><span>600</span><span>1000</span><span>1500</span><span>2500 ppm</span>
      </div>

      {/* band cards */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 6, marginTop: 4 }}>
        {c.healthBands.map((b, i) => {
          const isYours = readingPpm >= b.from && readingPpm < b.to;
          return (
            <div key={i} style={{
              padding: '10px 12px', borderRadius: 10,
              background: isYours
                ? (dark ? 'oklch(0.22 0.025 225)' : '#fff')
                : 'transparent',
              border: isYours ? `1.5px solid ${b.color}` : `1px solid ${dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)'}`,
              display: 'flex', alignItems: 'center', gap: 10,
              boxShadow: isYours ? `0 4px 14px ${b.color}26` : 'none',
            }}>
              <div style={{ width: 6, height: 32, borderRadius: 3, background: b.color, flexShrink: 0 }} />
              <div style={{ flex: 1 }}>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 8 }}>
                  <span style={{ fontFamily: 'Geist', fontSize: 13, fontWeight: 600,
                    color: dark ? '#fff' : '#0a1420' }}>{b.label}</span>
                  <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9,
                    letterSpacing: 1, color: dark ? 'rgba(255,255,255,0.45)' : 'rgba(20,30,50,0.45)' }}>
                    {b.from}–{b.to} ppm
                  </span>
                  {isYours && (
                    <span style={{ marginLeft: 'auto',
                      fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
                      color: b.color, fontWeight: 600 }}>← YOU</span>
                  )}
                </div>
                <div style={{ fontFamily: 'Geist', fontSize: 11, lineHeight: 1.4, marginTop: 2,
                  color: dark ? 'rgba(255,255,255,0.55)' : 'rgba(20,30,50,0.55)' }}>{b.detail}</div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Tutorial host — manages step progression
// ─────────────────────────────────────────────────────────────
function TutorialFlow({ dark, lang, device, onExit }) {
  const c = TUTORIAL_COPY[lang];
  const [step, setStep] = React.useState(0);
  const [readingPpm, setReadingPpm] = React.useState(612);

  const advance = () => setStep(s => s + 1);

  // Auto-advance step 2 (locating) is internal; step 1 advances on grant
  let hero = null;
  if (step === 0) hero = <StepPermissions dark={dark} lang={lang} onComplete={advance} />;
  if (step === 1) hero = <StepLocating dark={dark} lang={lang} onComplete={advance} />;
  if (step === 2) hero = <StepDeclaration dark={dark} lang={lang} onComplete={advance} setReadingPpm={setReadingPpm} />;
  if (step === 3) hero = <StepConfirm dark={dark} lang={lang} readingPpm={readingPpm} onComplete={advance} />;
  if (step === 4) hero = <StepHealth dark={dark} lang={lang} readingPpm={readingPpm} />;

  const stepData = c.steps[step];
  const showCTA = step !== 0 && step !== 2; // those have their own buttons

  return (
    <div key={step} style={{
      width: '100%', height: '100%', position: 'relative',
      display: 'flex', flexDirection: 'column',
      background: dark ? 'oklch(0.14 0.015 225)' : 'oklch(0.985 0.008 220)',
      animation: 'fadeSlide 0.5s ease-out',
      fontFamily: 'Geist, Inter, -apple-system, system-ui, sans-serif',
    }}>
      {/* Top bar */}
      <div style={{
        paddingTop: device === 'ios' ? 58 : 48,
        paddingLeft: 20, paddingRight: 20,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{
            width: 20, height: 20, borderRadius: 6,
            background: 'linear-gradient(135deg, oklch(0.65 0.14 230), oklch(0.72 0.14 155))',
            boxShadow: '0 2px 6px rgba(20,90,180,0.25)',
          }} />
          <span style={{
            fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 11, letterSpacing: 2, fontWeight: 500,
            color: dark ? 'rgba(255,255,255,0.7)' : 'rgba(20,30,50,0.6)',
          }}>SUNX · SENSE · TUTORIAL</span>
        </div>
        <div style={{ display: 'flex', gap: 4 }}>
          {[0,1,2,3,4].map(i => (
            <div key={i} style={{
              width: i === step ? 16 : 5, height: 5, borderRadius: 3,
              background: i <= step ? T_PRIMARY : (dark ? 'rgba(255,255,255,0.15)' : 'rgba(20,30,50,0.12)'),
              transition: 'all 0.35s cubic-bezier(.2,.9,.2,1)',
            }} />
          ))}
        </div>
      </div>

      {/* Hero */}
      <div style={{ margin: '20px auto 0', display: 'flex', justifyContent: 'center' }}>
        {hero}
      </div>

      {/* Eyebrow + label strip */}
      <div style={{
        margin: '14px 24px 0',
        fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 10, letterSpacing: 1.8,
        color: T_PRIMARY, fontWeight: 500,
      }}>{stepData.eyebrow}</div>

      {/* Copy */}
      <div style={{ padding: '8px 24px 0', flex: 1 }}>
        <h1 style={{
          fontFamily: 'Geist', fontWeight: 600, fontSize: 22, lineHeight: 1.18, letterSpacing: -0.6,
          color: dark ? '#fff' : '#0a1420', margin: '0 0 8px', textWrap: 'balance',
        }}>{stepData.title}</h1>
        <p style={{
          fontFamily: 'Geist', fontSize: 13, lineHeight: 1.5,
          color: dark ? 'rgba(255,255,255,0.6)' : 'rgba(20,30,50,0.6)',
          margin: 0, textWrap: 'pretty',
        }}>{stepData.body}</p>
      </div>

      {/* Footer CTA (only when step is passive) */}
      {showCTA && (
        <div style={{
          padding: '0 24px',
          paddingBottom: device === 'ios' ? 40 : 32,
        }}>
          <button onClick={step === 4 ? onExit : advance} style={{
            width: '100%', height: 50, border: 'none', borderRadius: 14,
            background: 'linear-gradient(135deg, oklch(0.65 0.14 230), oklch(0.58 0.16 220))',
            color: '#fff', fontFamily: 'Geist', fontSize: 14, fontWeight: 600,
            cursor: 'pointer',
            boxShadow: '0 8px 20px rgba(20,90,200,0.3)',
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
          }}>
            {stepData.cta}
            <svg width="14" height="14" viewBox="0 0 14 14"><path d="M2 7h10m-4-4l4 4-4 4" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/></svg>
          </button>
        </div>
      )}
      {/* If step has internal button (perms/declaration), still leave bottom space */}
      {!showCTA && (
        <div style={{ paddingBottom: device === 'ios' ? 40 : 32 }} />
      )}
    </div>
  );
}

window.TutorialFlow = TutorialFlow;


// ===== inline block =====
// iOS.jsx — Simplified iOS 26 (Liquid Glass) device frame
// Based on the iOS 26 UI Kit + Figma status bar spec. No assets, no deps.
// Exports: IOSDevice, IOSStatusBar, IOSNavBar, IOSGlassPill, IOSList, IOSListRow, IOSKeyboard

// ─────────────────────────────────────────────────────────────
// Status bar
// ─────────────────────────────────────────────────────────────
function IOSStatusBar({ dark = false, time = '9:41' }) {
  const c = dark ? '#fff' : '#000';
  return (
    <div style={{
      display: 'flex', gap: 154, alignItems: 'center', justifyContent: 'center',
      padding: '21px 24px 19px', boxSizing: 'border-box',
      position: 'relative', zIndex: 20, width: '100%',
    }}>
      <div style={{ flex: 1, height: 22, display: 'flex', alignItems: 'center', justifyContent: 'center', paddingTop: 1.5 }}>
        <span style={{
          fontFamily: '-apple-system, "SF Pro", system-ui', fontWeight: 590,
          fontSize: 17, lineHeight: '22px', color: c,
        }}>{time}</span>
      </div>
      <div style={{ flex: 1, height: 22, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 7, paddingTop: 1, paddingRight: 1 }}>
        <svg width="19" height="12" viewBox="0 0 19 12">
          <rect x="0" y="7.5" width="3.2" height="4.5" rx="0.7" fill={c}/>
          <rect x="4.8" y="5" width="3.2" height="7" rx="0.7" fill={c}/>
          <rect x="9.6" y="2.5" width="3.2" height="9.5" rx="0.7" fill={c}/>
          <rect x="14.4" y="0" width="3.2" height="12" rx="0.7" fill={c}/>
        </svg>
        <svg width="17" height="12" viewBox="0 0 17 12">
          <path d="M8.5 3.2C10.8 3.2 12.9 4.1 14.4 5.6L15.5 4.5C13.7 2.7 11.2 1.5 8.5 1.5C5.8 1.5 3.3 2.7 1.5 4.5L2.6 5.6C4.1 4.1 6.2 3.2 8.5 3.2Z" fill={c}/>
          <path d="M8.5 6.8C9.9 6.8 11.1 7.3 12 8.2L13.1 7.1C11.8 5.9 10.2 5.1 8.5 5.1C6.8 5.1 5.2 5.9 3.9 7.1L5 8.2C5.9 7.3 7.1 6.8 8.5 6.8Z" fill={c}/>
          <circle cx="8.5" cy="10.5" r="1.5" fill={c}/>
        </svg>
        <svg width="27" height="13" viewBox="0 0 27 13">
          <rect x="0.5" y="0.5" width="23" height="12" rx="3.5" stroke={c} strokeOpacity="0.35" fill="none"/>
          <rect x="2" y="2" width="20" height="9" rx="2" fill={c}/>
          <path d="M25 4.5V8.5C25.8 8.2 26.5 7.2 26.5 6.5C26.5 5.8 25.8 4.8 25 4.5Z" fill={c} fillOpacity="0.4"/>
        </svg>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Liquid glass pill — blur + tint + shine
// ─────────────────────────────────────────────────────────────
function IOSGlassPill({ children, dark = false, style = {} }) {
  return (
    <div style={{
      height: 44, minWidth: 44, borderRadius: 9999,
      position: 'relative', overflow: 'hidden',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      boxShadow: dark
        ? '0 2px 6px rgba(0,0,0,0.35), 0 6px 16px rgba(0,0,0,0.2)'
        : '0 1px 3px rgba(0,0,0,0.07), 0 3px 10px rgba(0,0,0,0.06)',
      ...style,
    }}>
      {/* blur + tint */}
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 9999,
        backdropFilter: 'blur(12px) saturate(180%)',
        WebkitBackdropFilter: 'blur(12px) saturate(180%)',
        background: dark ? 'rgba(120,120,128,0.28)' : 'rgba(255,255,255,0.5)',
      }} />
      {/* shine */}
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 9999,
        boxShadow: dark
          ? 'inset 1.5px 1.5px 1px rgba(255,255,255,0.15), inset -1px -1px 1px rgba(255,255,255,0.08)'
          : 'inset 1.5px 1.5px 1px rgba(255,255,255,0.7), inset -1px -1px 1px rgba(255,255,255,0.4)',
        border: dark ? '0.5px solid rgba(255,255,255,0.15)' : '0.5px solid rgba(0,0,0,0.06)',
      }} />
      <div style={{ position: 'relative', zIndex: 1, display: 'flex', alignItems: 'center', padding: '0 4px' }}>
        {children}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Navigation bar — glass pills + large title
// ─────────────────────────────────────────────────────────────
function IOSNavBar({ title = 'Title', dark = false, trailingIcon = true }) {
  const muted = dark ? 'rgba(255,255,255,0.6)' : '#404040';
  const text = dark ? '#fff' : '#000';
  const pillIcon = (content) => (
    <IOSGlassPill dark={dark}>
      <div style={{ width: 36, height: 36, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        {content}
      </div>
    </IOSGlassPill>
  );
  return (
    <div style={{
      display: 'flex', flexDirection: 'column', gap: 10,
      paddingTop: 62, paddingBottom: 10, position: 'relative', zIndex: 5,
    }}>
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '0 16px',
      }}>
        {/* back chevron */}
        {pillIcon(
          <svg width="12" height="20" viewBox="0 0 12 20" fill="none" style={{ marginLeft: -1 }}>
            <path d="M10 2L2 10l8 8" stroke={muted} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        )}
        {/* trailing ellipsis */}
        {trailingIcon && pillIcon(
          <svg width="22" height="6" viewBox="0 0 22 6">
            <circle cx="3" cy="3" r="2.5" fill={muted}/>
            <circle cx="11" cy="3" r="2.5" fill={muted}/>
            <circle cx="19" cy="3" r="2.5" fill={muted}/>
          </svg>
        )}
      </div>
      {/* large title */}
      <div style={{
        padding: '0 16px',
        fontFamily: '-apple-system, system-ui',
        fontSize: 34, fontWeight: 700, lineHeight: '41px',
        color: text, letterSpacing: 0.4,
      }}>{title}</div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Grouped list (inset card, r:26) + row (52px)
// ─────────────────────────────────────────────────────────────
function IOSListRow({ title, detail, icon, chevron = true, isLast = false, dark = false }) {
  const text = dark ? '#fff' : '#000';
  const sec = dark ? 'rgba(235,235,245,0.6)' : 'rgba(60,60,67,0.6)';
  const ter = dark ? 'rgba(235,235,245,0.3)' : 'rgba(60,60,67,0.3)';
  const sep = dark ? 'rgba(84,84,88,0.65)' : 'rgba(60,60,67,0.12)';
  return (
    <div style={{
      display: 'flex', alignItems: 'center', minHeight: 52,
      padding: '0 16px', position: 'relative',
      fontFamily: '-apple-system, system-ui', fontSize: 17,
      letterSpacing: -0.43,
    }}>
      {icon && (
        <div style={{
          width: 30, height: 30, borderRadius: 7, background: icon,
          marginRight: 12, flexShrink: 0,
        }} />
      )}
      <div style={{ flex: 1, color: text }}>{title}</div>
      {detail && <span style={{ color: sec, marginRight: 6 }}>{detail}</span>}
      {chevron && (
        <svg width="8" height="14" viewBox="0 0 8 14" style={{ flexShrink: 0 }}>
          <path d="M1 1l6 6-6 6" stroke={ter} strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      )}
      {!isLast && (
        <div style={{
          position: 'absolute', bottom: 0, right: 0,
          left: icon ? 58 : 16, height: 0.5, background: sep,
        }} />
      )}
    </div>
  );
}

function IOSList({ header, children, dark = false }) {
  const hc = dark ? 'rgba(235,235,245,0.6)' : 'rgba(60,60,67,0.6)';
  const bg = dark ? '#1C1C1E' : '#fff';
  return (
    <div>
      {header && (
        <div style={{
          fontFamily: '-apple-system, system-ui', fontSize: 13,
          color: hc, textTransform: 'uppercase',
          padding: '8px 36px 6px', letterSpacing: -0.08,
        }}>{header}</div>
      )}
      <div style={{
        background: bg, borderRadius: 26,
        margin: '0 16px', overflow: 'hidden',
      }}>{children}</div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Device frame
// ─────────────────────────────────────────────────────────────
function IOSDevice({
  children, width = 402, height = 874, dark = false,
  title, keyboard = false,
}) {
  return (
    <div style={{
      width, height, borderRadius: 48, overflow: 'hidden',
      position: 'relative', background: dark ? '#000' : '#F2F2F7',
      boxShadow: '0 40px 80px rgba(0,0,0,0.18), 0 0 0 1px rgba(0,0,0,0.12)',
      fontFamily: '-apple-system, system-ui, sans-serif',
      WebkitFontSmoothing: 'antialiased',
    }}>
      {/* dynamic island */}
      <div style={{
        position: 'absolute', top: 11, left: '50%', transform: 'translateX(-50%)',
        width: 126, height: 37, borderRadius: 24, background: '#000', zIndex: 50,
      }} />
      {/* status bar (absolute) */}
      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, zIndex: 10 }}>
        <IOSStatusBar dark={dark} />
      </div>
      {/* nav + content */}
      <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
        {title !== undefined && <IOSNavBar title={title} dark={dark} />}
        <div style={{ flex: 1, overflow: 'auto' }}>{children}</div>
        {keyboard && <IOSKeyboard dark={dark} />}
      </div>
      {/* home indicator — always on top */}
      <div style={{
        position: 'absolute', bottom: 0, left: 0, right: 0, zIndex: 60,
        height: 34, display: 'flex', justifyContent: 'center', alignItems: 'flex-end',
        paddingBottom: 8, pointerEvents: 'none',
      }}>
        <div style={{
          width: 139, height: 5, borderRadius: 100,
          background: dark ? 'rgba(255,255,255,0.7)' : 'rgba(0,0,0,0.25)',
        }} />
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Keyboard — iOS 26 liquid glass
// ─────────────────────────────────────────────────────────────
function IOSKeyboard({ dark = false }) {
  const glyph = dark ? 'rgba(255,255,255,0.7)' : '#595959';
  const sugg = dark ? 'rgba(255,255,255,0.6)' : '#333';
  const keyBg = dark ? 'rgba(255,255,255,0.22)' : 'rgba(255,255,255,0.85)';

  // special-key icons
  const icons = {
    shift: <svg width="19" height="17" viewBox="0 0 19 17"><path d="M9.5 1L1 9.5h4.5V16h8V9.5H18L9.5 1z" fill={glyph}/></svg>,
    del: <svg width="23" height="17" viewBox="0 0 23 17"><path d="M7 1h13a2 2 0 012 2v11a2 2 0 01-2 2H7l-6-7.5L7 1z" fill="none" stroke={glyph} strokeWidth="1.6" strokeLinejoin="round"/><path d="M10 5l7 7M17 5l-7 7" stroke={glyph} strokeWidth="1.6" strokeLinecap="round"/></svg>,
    ret: <svg width="20" height="14" viewBox="0 0 20 14"><path d="M18 1v6H4m0 0l4-4M4 7l4 4" fill="none" stroke="#fff" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>,
  };

  const key = (content, { w, flex, ret, fs = 25, k } = {}) => (
    <div key={k} style={{
      height: 42, borderRadius: 8.5,
      flex: flex ? 1 : undefined, width: w, minWidth: 0,
      background: ret ? '#08f' : keyBg,
      boxShadow: '0 1px 0 rgba(0,0,0,0.075)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      fontFamily: '-apple-system, "SF Compact", system-ui',
      fontSize: fs, fontWeight: 458, color: ret ? '#fff' : glyph,
    }}>{content}</div>
  );

  const row = (keys, pad = 0) => (
    <div style={{ display: 'flex', gap: 6.5, justifyContent: 'center', padding: `0 ${pad}px` }}>
      {keys.map(l => key(l, { flex: true, k: l }))}
    </div>
  );

  return (
    <div style={{
      position: 'relative', zIndex: 15, borderRadius: 27, overflow: 'hidden',
      padding: '11px 0 2px',
      display: 'flex', flexDirection: 'column', alignItems: 'center',
      boxShadow: dark
        ? '0 -2px 20px rgba(0,0,0,0.09)'
        : '0 -1px 6px rgba(0,0,0,0.018), 0 -3px 20px rgba(0,0,0,0.012)',
    }}>
      {/* liquid glass bg — same recipe as nav pills */}
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 27,
        backdropFilter: 'blur(12px) saturate(180%)',
        WebkitBackdropFilter: 'blur(12px) saturate(180%)',
        background: dark ? 'rgba(120,120,128,0.14)' : 'rgba(255,255,255,0.25)',
      }} />
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 27,
        boxShadow: dark
          ? 'inset 1.5px 1.5px 1px rgba(255,255,255,0.15)'
          : 'inset 1.5px 1.5px 1px rgba(255,255,255,0.7), inset -1px -1px 1px rgba(255,255,255,0.4)',
        border: dark ? '0.5px solid rgba(255,255,255,0.15)' : '0.5px solid rgba(0,0,0,0.06)',
        pointerEvents: 'none',
      }} />

      {/* autocorrect bar */}
      <div style={{
        display: 'flex', gap: 20, alignItems: 'center',
        padding: '8px 22px 13px', width: '100%', boxSizing: 'border-box',
        position: 'relative',
      }}>
        {['"The"', 'the', 'to'].map((w, i) => (
          <React.Fragment key={i}>
            {i > 0 && <div style={{ width: 1, height: 25, background: '#ccc', opacity: 0.3 }} />}
            <div style={{
              flex: 1, textAlign: 'center',
              fontFamily: '-apple-system, system-ui', fontSize: 17,
              color: sugg, letterSpacing: -0.43, lineHeight: '22px',
            }}>{w}</div>
          </React.Fragment>
        ))}
      </div>

      {/* key layout */}
      <div style={{
        display: 'flex', flexDirection: 'column', gap: 13,
        padding: '0 6.5px', width: '100%', boxSizing: 'border-box',
        position: 'relative',
      }}>
        {row(['q','w','e','r','t','y','u','i','o','p'])}
        {row(['a','s','d','f','g','h','j','k','l'], 20)}
        <div style={{ display: 'flex', gap: 14.25, alignItems: 'center' }}>
          {key(icons.shift, { w: 45, k: 'shift' })}
          <div style={{ display: 'flex', gap: 6.5, flex: 1 }}>
            {['z','x','c','v','b','n','m'].map(l => key(l, { flex: true, k: l }))}
          </div>
          {key(icons.del, { w: 45, k: 'del' })}
        </div>
        <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
          {key('ABC', { w: 92.25, fs: 18, k: 'abc' })}
          {key('', { flex: true, k: 'space' })}
          {key(icons.ret, { w: 92.25, ret: true, k: 'ret' })}
        </div>
      </div>

      {/* bottom spacer (emoji+mic area, icons omitted) */}
      <div style={{ height: 56, width: '100%', position: 'relative' }} />
    </div>
  );
}

Object.assign(window, {
  IOSDevice, IOSStatusBar, IOSNavBar, IOSGlassPill, IOSList, IOSListRow, IOSKeyboard,
});

// ===== inline block =====
// Android.jsx — Simplified Android (Material 3) device frame
// Status bar + top app bar + content + gesture nav + keyboard.
// Based on Figma M3 spec. No dependencies, no image assets.

const MD_C = {
  surface: '#f4fbf8',
  surfaceVariant: '#dae5e1',
  inverseOnSurface: '#ecf2ef',
  secondaryContainer: '#cde8e1',
  primaryFixedDim: '#83d5c6',
  onSurface: '#171d1b',
  onSurfaceVar: '#49454f',
  onPrimaryContainer: '#00201c',
  primary: '#006a60',
  frameBorder: 'rgba(116,119,117,0.5)',
};

// ─────────────────────────────────────────────────────────────
// Status bar (time left, wifi/cell/battery right)
// ─────────────────────────────────────────────────────────────
function AndroidStatusBar({ dark = false }) {
  const c = dark ? '#fff' : MD_C.onSurface;
  return (
    <div style={{
      height: 40, display: 'flex', alignItems: 'center',
      justifyContent: 'space-between', padding: '0 16px',
      position: 'relative',
      fontFamily: 'Roboto, system-ui, sans-serif',
    }}>
      {/* time left */}
      <div style={{ width: 128, display: 'flex', alignItems: 'center', gap: 8 }}>
        <span style={{ fontSize: 14, fontWeight: 400, letterSpacing: 0.25, lineHeight: '20px', color: c }}>9:30</span>
      </div>
      {/* camera punch-hole (center) */}
      <div style={{
        position: 'absolute', left: '50%', top: 8, transform: 'translateX(-50%)',
        width: 24, height: 24, borderRadius: 100, background: '#2e2e2e',
      }} />
      {/* status icons right */}
      <div style={{ display: 'flex', alignItems: 'center' }}>
        <div style={{ display: 'flex', paddingRight: 2 }}>
          <svg width="16" height="16" viewBox="0 0 16 16" style={{ marginRight: -2 }}>
            <path d="M8 13.3L.67 5.97a10.37 10.37 0 0114.66 0L8 13.3z" fill={c}/>
          </svg>
          <svg width="16" height="16" viewBox="0 0 16 16" style={{ marginRight: -2 }}>
            <path d="M14.67 14.67V1.33L1.33 14.67h13.34z" fill={c}/>
          </svg>
        </div>
        <svg width="16" height="16" viewBox="0 0 16 16">
          <rect x="3.75" y="2" width="8.5" height="13" rx="1.5" fill={c}/>
          <rect x="5.5" y="0.9" width="5" height="2" rx="0.5" fill={c}/>
        </svg>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Top app bar (Material 3 small/medium)
// ─────────────────────────────────────────────────────────────
function AndroidAppBar({ title = 'Title', large = false }) {
  const iconDot = (
    <div style={{
      width: 48, height: 48, display: 'flex', alignItems: 'center', justifyContent: 'center',
    }}>
      <div style={{ width: 22, height: 22, borderRadius: '50%', background: MD_C.onSurfaceVar, opacity: 0.3 }} />
    </div>
  );
  return (
    <div style={{ background: MD_C.surface, padding: '4px 4px 0' }}>
      <div style={{ height: 56, display: 'flex', alignItems: 'center', gap: 4 }}>
        {iconDot}
        {!large && (
          <span style={{
            flex: 1, fontSize: 22, fontWeight: 400, color: MD_C.onSurface,
            fontFamily: 'Roboto, system-ui, sans-serif',
          }}>{title}</span>
        )}
        {large && <div style={{ flex: 1 }} />}
        {iconDot}
      </div>
      {large && (
        <div style={{
          padding: '16px 16px 20px',
          fontSize: 28, fontWeight: 400, color: MD_C.onSurface,
          fontFamily: 'Roboto, system-ui, sans-serif',
        }}>{title}</div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// List item (Material 3)
// ─────────────────────────────────────────────────────────────
function AndroidListItem({ headline, supporting, leading }) {
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 16,
      padding: '12px 16px', minHeight: 56, boxSizing: 'border-box',
      fontFamily: 'Roboto, system-ui, sans-serif',
    }}>
      {leading && (
        <div style={{
          width: 40, height: 40, borderRadius: '50%',
          background: MD_C.primary, color: '#fff',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: 18, fontWeight: 500, flexShrink: 0,
        }}>{leading}</div>
      )}
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 16, color: MD_C.onSurface, lineHeight: '24px' }}>{headline}</div>
        {supporting && (
          <div style={{ fontSize: 14, color: MD_C.onSurfaceVar, lineHeight: '20px' }}>{supporting}</div>
        )}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Gesture nav bar (pill)
// ─────────────────────────────────────────────────────────────
function AndroidNavBar({ dark = false }) {
  return (
    <div style={{
      height: 24, display: 'flex', alignItems: 'center', justifyContent: 'center',
    }}>
      <div style={{
        width: 108, height: 4, borderRadius: 2,
        background: dark ? '#fff' : MD_C.onSurface, opacity: 0.4,
      }} />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Device frame — wraps everything
// ─────────────────────────────────────────────────────────────
function AndroidDevice({
  children, width = 412, height = 892, dark = false,
  title, large = false, keyboard = false,
}) {
  return (
    <div style={{
      width, height, borderRadius: 18, overflow: 'hidden',
      background: dark ? '#1d1b20' : MD_C.surface,
      border: `8px solid ${MD_C.frameBorder}`,
      boxShadow: '0 30px 80px rgba(0,0,0,0.25)',
      display: 'flex', flexDirection: 'column', boxSizing: 'border-box',
    }}>
      <AndroidStatusBar dark={dark} />
      {title !== undefined && <AndroidAppBar title={title} large={large} />}
      <div style={{ flex: 1, overflow: 'auto' }}>
        {children}
      </div>
      {keyboard && <AndroidKeyboard />}
      <AndroidNavBar dark={dark} />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Keyboard — Gboard (Material 3)
// ─────────────────────────────────────────────────────────────
function AndroidKeyboard() {
  let _k = 0;
  const key = (l, { flex = 1, bg = MD_C.surface, r = 6, minW, fs = 21 } = {}) => (
    <div key={_k++} style={{
      height: 46, borderRadius: r, flex, minWidth: minW,
      background: bg, display: 'flex', alignItems: 'center', justifyContent: 'center',
      fontFamily: 'Roboto, system-ui', fontSize: fs,
      color: MD_C.onPrimaryContainer,
    }}>{l}</div>
  );
  const row = (keys, style = {}) => (
    <div style={{ display: 'flex', gap: 6, justifyContent: 'center', ...style }}>
      {keys.map(l => key(l))}
    </div>
  );
  return (
    <div style={{
      background: MD_C.inverseOnSurface, padding: '0 8px 8px',
      display: 'flex', flexDirection: 'column', gap: 4,
    }}>
      {/* navbar spacer (icons omitted) */}
      <div style={{ height: 44 }} />
      {/* key rows */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {row(['q','w','e','r','t','y','u','i','o','p'])}
        {row(['a','s','d','f','g','h','j','k','l'], { padding: '0 20px' })}
        <div style={{ display: 'flex', gap: 6 }}>
          {key('', { bg: MD_C.surfaceVariant })}
          <div style={{ display: 'flex', gap: 6, flex: 7, minWidth: 274 }}>
            {['z','x','c','v','b','n','m'].map(l => key(l))}
          </div>
          {key('', { bg: MD_C.surfaceVariant })}
        </div>
        <div style={{ display: 'flex', gap: 6 }}>
          {key('?123', { bg: MD_C.secondaryContainer, r: 100, minW: 58, fs: 14 })}
          {key(',', { bg: MD_C.surfaceVariant })}
          {key('', { flex: 3, minW: 154 })}
          {key('.', { bg: MD_C.surfaceVariant })}
          {key('', { bg: MD_C.primaryFixedDim, r: 100, minW: 58 })}
        </div>
      </div>
    </div>
  );
}

Object.assign(window, {
  AndroidDevice, AndroidStatusBar, AndroidAppBar, AndroidListItem, AndroidNavBar, AndroidKeyboard,
});

// ===== inline block =====
// Mascot — the "Sense Orb": a friendly pulsing sphere with AQI ring
// Consistent across all slides; changes expression subtly per slide
function SenseOrb({ size = 56, dark = false, mood = 'calm' }) {
  const primary = 'oklch(0.65 0.14 230)';
  const accent = 'oklch(0.72 0.14 155)';
  const eyeColor = dark ? '#0a1420' : '#0a1420';

  const eyeY = mood === 'excited' ? 44 : mood === 'focused' ? 50 : 48;
  const smileY = mood === 'excited' ? 68 : 64;
  const smileCurve = mood === 'excited' ? 8 : mood === 'focused' ? 3 : 5;

  return (
    <svg width={size} height={size} viewBox="0 0 100 100" style={{ flexShrink: 0 }}>
      <defs>
        <radialGradient id={`orbGrad-${mood}`} cx="35%" cy="30%" r="70%">
          <stop offset="0%" stopColor="#fff" stopOpacity="0.9" />
          <stop offset="40%" stopColor={primary} stopOpacity="0.5" />
          <stop offset="100%" stopColor={primary} stopOpacity="0.9" />
        </radialGradient>
      </defs>

      {/* outer AQI ring */}
      <circle cx="50" cy="50" r="46" fill="none" stroke={accent} strokeWidth="1.5"
        strokeDasharray="3 4" opacity="0.5"
        style={{ animation: 'coreSpin 12s linear infinite', transformOrigin: '50px 50px' }} />

      {/* breathing glow */}
      <circle cx="50" cy="50" r="42" fill={primary} opacity="0.12"
        style={{ animation: 'haloBreath 3s ease-in-out infinite', transformOrigin: '50px 50px' }} />

      {/* body */}
      <circle cx="50" cy="50" r="34" fill={`url(#orbGrad-${mood})`} />

      {/* highlight */}
      <ellipse cx="40" cy="36" rx="10" ry="6" fill="#fff" opacity="0.45" />

      {/* eyes */}
      <circle cx="40" cy={eyeY} r="2.5" fill={eyeColor} />
      <circle cx="60" cy={eyeY} r="2.5" fill={eyeColor} />

      {/* smile */}
      <path d={`M 42 ${smileY} Q 50 ${smileY + smileCurve} 58 ${smileY}`}
        stroke={eyeColor} strokeWidth="2" fill="none" strokeLinecap="round" />
    </svg>
  );
}

window.SenseOrb = SenseOrb;

// ===== inline block =====
// Data-viz heroes — aligned with SUNX Sense product (H3 hex zones, declarations, PX Carbostar telemetry, SUNX tokens, zone trust)
const HERO_W = 342;
const HERO_H = 300;

const AQI_RAMP = {
  good: 'oklch(0.72 0.14 155)',
  mod:  'oklch(0.78 0.14 95)',
  poor: 'oklch(0.72 0.16 55)',
  bad:  'oklch(0.62 0.18 25)',
};
const PRIMARY = 'oklch(0.65 0.14 230)';
const ACCENT  = 'oklch(0.72 0.14 155)';

// flat-top hex path generator — pointy hexes for H3-style map
function hexPath(cx, cy, r) {
  const pts = [];
  for (let i = 0; i < 6; i++) {
    const a = Math.PI / 3 * i - Math.PI / 2;
    pts.push([cx + Math.cos(a) * r, cy + Math.sin(a) * r]);
  }
  return 'M ' + pts.map(p => p.join(' ')).join(' L ') + ' Z';
}
// offset hex grid layout
function hexGrid(cols, rows, r, startX = 0, startY = 0) {
  const dx = r * Math.sqrt(3);
  const dy = r * 1.5;
  const out = [];
  for (let row = 0; row < rows; row++) {
    for (let col = 0; col < cols; col++) {
      const x = startX + col * dx + (row % 2 ? dx / 2 : 0);
      const y = startY + row * dy;
      out.push({ x, y, row, col });
    }
  }
  return out;
}

// ─────────────────────────────────────────────────────────────
// HERO 1 — Global H3 intelligence: hex world pulse
// ─────────────────────────────────────────────────────────────
function Hero1Globe({ dark }) {
  const bg    = dark ? 'oklch(0.17 0.015 225)' : 'oklch(0.98 0.008 225)';
  const hexFill = dark ? 'oklch(0.24 0.015 225)' : 'oklch(0.94 0.01 225)';
  const hexStroke = dark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.04)';

  // sphere-like: hex cells arranged in circle, fade at edges
  const cells = hexGrid(12, 9, 17, -20, -10);
  const cx = HERO_W / 2, cy = HERO_H / 2;

  const active = [
    { i: 30, c: AQI_RAMP.good },
    { i: 41, c: AQI_RAMP.good },
    { i: 55, c: AQI_RAMP.mod },
    { i: 27, c: AQI_RAMP.poor },
    { i: 52, c: AQI_RAMP.good },
    { i: 39, c: AQI_RAMP.bad },
    { i: 63, c: AQI_RAMP.good },
    { i: 44, c: AQI_RAMP.mod },
    { i: 70, c: AQI_RAMP.good },
  ];
  const activeMap = new Map(active.map(a => [a.i, a.c]));

  return (
    <div style={{ width: HERO_W, height: HERO_H, position: 'relative',
      borderRadius: 20, overflow: 'hidden', background: bg,
      border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}` }}>

      {/* breathing rings */}
      {[0,1,2].map(i => (
        <div key={i} style={{
          position: 'absolute', left: cx - 130, top: cy - 130,
          width: 260, height: 260, borderRadius: '50%',
          border: `1.5px solid ${PRIMARY}`, opacity: 0.15,
          animation: `breathPulse 4s ease-in-out infinite`,
          animationDelay: `${i * 1.3}s`,
        }} />
      ))}

      <svg width={HERO_W} height={HERO_H}>
        <defs>
          <radialGradient id="h1mask" cx="50%" cy="50%" r="50%">
            <stop offset="0%" stopColor="#fff" stopOpacity="1"/>
            <stop offset="75%" stopColor="#fff" stopOpacity="1"/>
            <stop offset="100%" stopColor="#fff" stopOpacity="0"/>
          </radialGradient>
          <mask id="h1m">
            <rect width={HERO_W} height={HERO_H} fill="url(#h1mask)"/>
          </mask>
        </defs>
        <g mask="url(#h1m)">
          {cells.map((c, i) => {
            const d = Math.hypot(c.x - cx, c.y - cy);
            if (d > 125) return null;
            const isAct = activeMap.has(i);
            return (
              <path key={i} d={hexPath(c.x, c.y, 15)}
                fill={isAct ? activeMap.get(i) : hexFill}
                stroke={hexStroke} strokeWidth="1"
                style={isAct ? {
                  animation: 'dotBreath 3s ease-in-out infinite',
                  animationDelay: `${(i * 97) % 2000}ms`,
                  transformOrigin: `${c.x}px ${c.y}px`,
                  opacity: 0.9,
                } : { opacity: 1 - (d / 150) }}
              />
            );
          })}
        </g>
      </svg>

      {/* readout chip */}
      <div style={{
        position: 'absolute', left: 16, bottom: 14,
        fontFamily: 'Geist Mono, ui-monospace, monospace',
        fontSize: 9, letterSpacing: 1.5,
        color: dark ? 'rgba(255,255,255,0.45)' : 'rgba(20,30,50,0.45)',
        display: 'flex', alignItems: 'center', gap: 6,
      }}>
        <span style={{ width: 5, height: 5, background: ACCENT, borderRadius: '50%',
          animation: 'dotBreath 1.6s ease-in-out infinite' }} />
        H3 · RES 8 · GLOBAL
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// HERO 2 — Declaration lands into a zone
// ─────────────────────────────────────────────────────────────
function Hero2Ripple({ dark }) {
  const bg = dark ? 'oklch(0.17 0.015 225)' : 'oklch(0.98 0.008 225)';
  const hexFill = dark ? 'oklch(0.24 0.015 225)' : 'oklch(0.94 0.01 225)';
  const hexStroke = dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)';

  // local hex neighborhood — user's zone center, neighbours around
  const cells = hexGrid(8, 7, 22, -5, 10);
  const cx = HERO_W / 2, cy = HERO_H / 2;
  // find nearest hex to center as "your zone"
  let nearest = 0, minD = Infinity;
  cells.forEach((c, i) => {
    const d = Math.hypot(c.x - cx, c.y - cy);
    if (d < minD) { minD = d; nearest = i; }
  });

  const neighbors = [
    { idx: nearest, c: ACCENT, isYou: true },
    { idx: nearest - 8, c: AQI_RAMP.good, isYou: false },
    { idx: nearest + 8, c: AQI_RAMP.mod, isYou: false },
    { idx: nearest - 1, c: AQI_RAMP.good, isYou: false },
    { idx: nearest + 1, c: AQI_RAMP.good, isYou: false },
    { idx: nearest - 9, c: AQI_RAMP.poor, isYou: false },
    { idx: nearest + 7, c: AQI_RAMP.good, isYou: false },
  ];
  const nMap = new Map(neighbors.map(n => [n.idx, n]));

  return (
    <div style={{ width: HERO_W, height: HERO_H, position: 'relative',
      borderRadius: 20, overflow: 'hidden', background: bg,
      border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}` }}>

      <svg width={HERO_W} height={HERO_H}>
        {/* all cells */}
        {cells.map((c, i) => {
          const hit = nMap.get(i);
          if (hit) {
            return (
              <g key={i}>
                <path d={hexPath(c.x, c.y, 20)}
                  fill={hit.c} opacity={hit.isYou ? 0.9 : 0.5}
                  stroke={hit.isYou ? ACCENT : hexStroke} strokeWidth={hit.isYou ? 2 : 1}
                  style={hit.isYou ? {} : {
                    animation: 'dotBreath 3.2s ease-in-out infinite',
                    animationDelay: `${i * 180}ms`,
                    transformOrigin: `${c.x}px ${c.y}px`,
                  }}
                />
              </g>
            );
          }
          return <path key={i} d={hexPath(c.x, c.y, 20)}
            fill={hexFill} stroke={hexStroke} strokeWidth="1" />;
        })}

        {/* user's hex ripple */}
        {[0, 1, 2].map(i => {
          const c = cells[nearest];
          return (
            <path key={`r${i}`} d={hexPath(c.x, c.y, 20)}
              fill="none" stroke={ACCENT} strokeWidth="2"
              style={{
                animation: 'ripExpand 2.4s ease-out infinite',
                animationDelay: `${i * 0.8}s`,
                transformOrigin: `${c.x}px ${c.y}px`,
                transformBox: 'fill-box',
              }} />
          );
        })}
      </svg>

      {/* Declaration chip */}
      <div style={{
        position: 'absolute', left: cx + 40, top: cy - 70,
        padding: '8px 10px', borderRadius: 10,
        background: dark ? 'rgba(15,25,35,0.92)' : 'rgba(255,255,255,0.95)',
        boxShadow: '0 8px 24px rgba(0,0,0,0.15)',
        fontFamily: 'Geist Mono, ui-monospace, monospace',
        fontSize: 10, letterSpacing: 0.2,
        color: dark ? '#e8f0fa' : '#0a1420',
        border: `1px solid ${dark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)'}`,
        whiteSpace: 'nowrap',
        animation: 'chipFloat 2.4s ease-in-out infinite',
      }}>
        <div style={{ color: ACCENT, fontSize: 8, letterSpacing: 1 }}>DECLARATION · +1</div>
        <div style={{ marginTop: 2, fontSize: 11 }}>CLEAN AIR · 0.87</div>
      </div>

      {/* hex id */}
      <div style={{
        position: 'absolute', left: 16, bottom: 14,
        fontFamily: 'Geist Mono, ui-monospace, monospace',
        fontSize: 9, letterSpacing: 1.5,
        color: dark ? 'rgba(255,255,255,0.45)' : 'rgba(20,30,50,0.45)',
      }}>8828308281fffff · YOUR ZONE</div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// HERO 3 — PX Carbostar telemetry stream
// ─────────────────────────────────────────────────────────────
function Hero3Network({ dark }) {
  const bg = dark ? 'oklch(0.17 0.015 225)' : 'oklch(0.98 0.008 225)';
  const border = dark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)';
  const textMute = dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)';
  const textMain = dark ? '#fff' : '#0a1420';

  // Telemetry sparkline (CO₂ ppm over time)
  const N = 32;
  const pts = [];
  for (let i = 0; i < N; i++) {
    const x = (i / (N-1)) * (HERO_W - 40) + 20;
    const t = i / (N-1);
    const base = 410 + Math.sin(t * 5) * 8 + Math.sin(t * 13) * 4 + t * 6;
    const y = 240 - (base - 400) * 4;
    pts.push([x, y, base]);
  }
  const sparkD = pts.reduce((a, [x,y], i) => a + (i===0?`M ${x} ${y}`:` L ${x} ${y}`), '');
  const sparkArea = sparkD + ` L ${pts[N-1][0]} 270 L ${pts[0][0]} 270 Z`;

  return (
    <div style={{ width: HERO_W, height: HERO_H, position: 'relative',
      borderRadius: 20, overflow: 'hidden', background: bg, border: `1px solid ${border}`,
      padding: 18, boxSizing: 'border-box' }}>

      {/* device pill */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <div style={{
          display: 'flex', alignItems: 'center', gap: 10,
        }}>
          {/* device icon */}
          <div style={{
            width: 34, height: 34, borderRadius: 9,
            background: 'linear-gradient(135deg, oklch(0.35 0.03 240), oklch(0.22 0.02 240))',
            border: '1px solid rgba(255,255,255,0.08)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            position: 'relative',
          }}>
            <div style={{
              width: 8, height: 8, borderRadius: '50%',
              background: ACCENT, boxShadow: `0 0 10px ${ACCENT}`,
              animation: 'dotBreath 1.3s ease-in-out infinite',
            }} />
            {/* grille */}
            <div style={{
              position: 'absolute', right: 5, top: 6, width: 6, height: 22,
              background: `repeating-linear-gradient(to bottom, transparent 0 2px, rgba(255,255,255,0.15) 2px 3px)`,
              borderRadius: 2,
            }} />
          </div>
          <div>
            <div style={{
              fontFamily: 'Geist, Inter, system-ui', fontSize: 13, fontWeight: 500,
              color: textMain,
            }}>PX Carbostar</div>
            <div style={{
              fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
              color: textMute,
            }}>PAIRED · BLE 5.0</div>
          </div>
        </div>
        <div style={{
          padding: '4px 8px', borderRadius: 100,
          background: dark ? 'rgba(180,220,160,0.12)' : 'rgba(50,150,80,0.08)',
          color: ACCENT,
          fontFamily: 'Geist Mono, ui-monospace, monospace',
          fontSize: 8, letterSpacing: 1,
          display: 'flex', alignItems: 'center', gap: 4,
        }}>
          <span style={{ width: 4, height: 4, borderRadius: '50%', background: ACCENT,
            animation: 'dotBreath 1.5s ease-in-out infinite' }} />
          LIVE
        </div>
      </div>

      {/* big readout */}
      <div style={{ marginTop: 18, display: 'flex', alignItems: 'baseline', gap: 6 }}>
        <div style={{
          fontFamily: 'Geist, Inter, system-ui', fontWeight: 600,
          fontSize: 52, letterSpacing: -1.8, lineHeight: 1,
          color: textMain, fontVariantNumeric: 'tabular-nums',
        }}>412</div>
        <div style={{
          fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 13,
          color: textMute,
        }}>ppm CO₂</div>
      </div>
      <div style={{
        fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9,
        color: ACCENT, marginTop: 2, letterSpacing: 0.5,
      }}>▲ STREAMING TO SUNX EARTH</div>

      {/* telemetry sparkline */}
      <svg width={HERO_W - 36} height={90} style={{ position: 'absolute', left: 0, bottom: 14 }}
        viewBox={`0 150 ${HERO_W} 130`}>
        <defs>
          <linearGradient id="h3sparkFill" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={PRIMARY} stopOpacity="0.3"/>
            <stop offset="100%" stopColor={PRIMARY} stopOpacity="0"/>
          </linearGradient>
        </defs>
        <path d={sparkArea} fill="url(#h3sparkFill)"/>
        <path d={sparkD} stroke={PRIMARY} strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
        <circle cx={pts[N-1][0]} cy={pts[N-1][1]} r="4" fill={PRIMARY}/>
        <circle cx={pts[N-1][0]} cy={pts[N-1][1]} r="8" fill={PRIMARY} opacity="0.3"
          style={{ animation: 'dotBreath 1.6s ease-in-out infinite',
            transformOrigin: `${pts[N-1][0]}px ${pts[N-1][1]}px` }}/>

        {/* traveling telemetry packets */}
        {[0,1,2].map(i => (
          <circle key={i} r="2" fill={ACCENT}>
            <animateMotion dur="2.4s" repeatCount="indefinite" begin={`${i * 0.8}s`} path={sparkD}/>
          </circle>
        ))}
      </svg>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// HERO 4 — SUNX tokens (on Earth platform)
// ─────────────────────────────────────────────────────────────
function Hero4Tokens({ dark }) {
  const gold = 'oklch(0.78 0.14 75)';
  const [count, setCount] = React.useState(0);

  React.useEffect(() => {
    let i = 0, steps = 80, target = 864;
    const t = setInterval(() => {
      i++;
      const p = i / steps, eased = 1 - Math.pow(1 - p, 3);
      setCount(Math.round(target * eased));
      if (i >= steps) clearInterval(t);
    }, 30);
    return () => clearInterval(t);
  }, []);

  const spark = [];
  const N = 24;
  for (let i = 0; i < N; i++) {
    const x = (i / (N-1)) * (HERO_W - 48) + 24;
    const base = i / (N-1);
    const noise = Math.sin(i * 0.8) * 0.08 + Math.sin(i * 1.7) * 0.05;
    const y = 220 - (base * 90 + noise * 40);
    spark.push([x, y]);
  }
  const sparkD = spark.reduce((a, [x,y], i) => a + (i===0?`M ${x} ${y}`:` L ${x} ${y}`), '');
  const sparkArea = sparkD + ` L ${spark[N-1][0]} 240 L ${spark[0][0]} 240 Z`;

  return (
    <div style={{ width: HERO_W, height: HERO_H, position: 'relative', borderRadius: 20, overflow: 'hidden',
      background: dark
        ? 'linear-gradient(160deg, oklch(0.22 0.03 250), oklch(0.17 0.015 230))'
        : 'linear-gradient(160deg, oklch(0.98 0.01 230), oklch(0.94 0.02 220))',
      border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}`,
      padding: 20, boxSizing: 'border-box' }}>

      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{
          fontFamily: 'Geist Mono, ui-monospace, monospace',
          fontSize: 10, letterSpacing: 1.5,
          color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)',
        }}>SUNX · EARTH WALLET</div>
        <div style={{
          padding: '4px 8px', borderRadius: 100,
          background: dark ? 'rgba(180,220,160,0.15)' : 'rgba(50,150,80,0.1)',
          color: ACCENT,
          fontFamily: 'Geist Mono, ui-monospace, monospace',
          fontSize: 9, letterSpacing: 0.5,
          display: 'flex', alignItems: 'center', gap: 4,
        }}>
          <span style={{ width: 5, height: 5, borderRadius: '50%', background: ACCENT,
            animation: 'dotBreath 1.5s ease-in-out infinite' }} />
          SETTLING
        </div>
      </div>

      <div style={{ marginTop: 14, display: 'flex', alignItems: 'baseline', gap: 6 }}>
        <div style={{
          fontFamily: 'Geist, Inter, system-ui', fontWeight: 600,
          fontSize: 56, letterSpacing: -2, lineHeight: 1,
          color: dark ? '#fff' : '#0a1420',
          fontVariantNumeric: 'tabular-nums',
        }}>{count.toLocaleString()}</div>
        <div style={{
          fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 14, color: gold,
        }}>SUNX</div>
      </div>
      <div style={{
        fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 10, color: ACCENT, marginTop: 2,
      }}>+86.4 this week · 14 declarations verified</div>

      <svg width={HERO_W - 40} height={130} style={{ position: 'absolute', left: 0, bottom: 20 }}
        viewBox={`0 110 ${HERO_W} 140`}>
        <defs>
          <linearGradient id="h4sparkFill" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0%" stopColor={PRIMARY} stopOpacity="0.35"/>
            <stop offset="100%" stopColor={PRIMARY} stopOpacity="0"/>
          </linearGradient>
        </defs>
        <path d={sparkArea} fill="url(#h4sparkFill)"/>
        <path d={sparkD} stroke={PRIMARY} strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
        <circle cx={spark[N-1][0]} cy={spark[N-1][1]} r="5" fill={PRIMARY}/>
        <circle cx={spark[N-1][0]} cy={spark[N-1][1]} r="9" fill={PRIMARY} opacity="0.3"
          style={{ animation: 'dotBreath 1.6s ease-in-out infinite',
            transformOrigin: `${spark[N-1][0]}px ${spark[N-1][1]}px` }} />
        {[0,1,2,3,4].map(i => (
          <circle key={i} cx={40 + i*60} cy={200} r="2" fill={gold}
            style={{ animation: `particleRise 3s ease-out infinite`, animationDelay: `${i*0.6}s` }} />
        ))}
      </svg>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// HERO 5 — Zone trust dial (H3 cell ready to declare)
// ─────────────────────────────────────────────────────────────
function Hero5Dial({ dark }) {
  const good = ACCENT;
  const track = dark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)';
  const textMute = dark ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.45)';

  const cx = HERO_W / 2, cy = 160, r = 100;
  const startA = 135, sweepA = 270;
  const trustScore = 0.87; // fraction
  const endA = startA + sweepA * trustScore;

  const polar = (deg, rad) => [cx + Math.cos(deg * Math.PI/180) * rad, cy + Math.sin(deg * Math.PI/180) * rad];
  const arcPath = (from, to, rad) => {
    const [x1,y1] = polar(from, rad), [x2,y2] = polar(to, rad);
    const large = to - from > 180 ? 1 : 0;
    return `M ${x1} ${y1} A ${rad} ${rad} 0 ${large} 1 ${x2} ${y2}`;
  };

  return (
    <div style={{ width: HERO_W, height: HERO_H, position: 'relative',
      display: 'flex', alignItems: 'center', justifyContent: 'center' }}>

      <div style={{
        position: 'absolute', width: 260, height: 260, borderRadius: '50%',
        background: `radial-gradient(circle, ${good} 0%, transparent 70%)`,
        opacity: 0.15, animation: 'haloBreath 4s ease-in-out infinite',
      }} />

      <svg width={HERO_W} height={HERO_H}>
        {/* hexagonal frame behind dial */}
        <path d={hexPath(cx, cy, 110)} fill="none"
          stroke={dark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)'}
          strokeWidth="1" strokeDasharray="2 4" />

        <path d={arcPath(startA, startA + sweepA, r)} fill="none" stroke={track} strokeWidth="14" strokeLinecap="round"/>
        <path d={arcPath(startA, endA, r)} fill="none" stroke={good} strokeWidth="14" strokeLinecap="round"
          style={{ strokeDasharray: 1000, strokeDashoffset: 1000, animation: 'dialDraw 2s ease-out forwards' }}/>

        {Array.from({ length: 14 }).map((_, i) => {
          const a = startA + (sweepA / 13) * i;
          const [x1,y1] = polar(a, r-22), [x2,y2] = polar(a, r-14);
          return <line key={i} x1={x1} y1={y1} x2={x2} y2={y2}
            stroke={dark ? 'rgba(255,255,255,0.15)' : 'rgba(0,0,0,0.12)'} strokeWidth="1.5"/>;
        })}

        <text x={cx} y={cy - 4} textAnchor="middle"
          style={{ fontFamily: 'Geist, Inter, system-ui', fontWeight: 600, fontSize: 56, letterSpacing: -1.8,
            fill: dark ? '#fff' : '#0a1420' }}>0.87</text>
        <text x={cx} y={cy + 26} textAnchor="middle"
          style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 11, letterSpacing: 2, fill: good }}>
          TRUST · READY</text>
        <text x={cx} y={cy + 48} textAnchor="middle"
          style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.2, fill: textMute }}>
          H3 · 8828308281fffff</text>
      </svg>

      <div style={{ position: 'absolute', left: 20, bottom: 20,
        fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
        color: textMute }}>0.00</div>
      <div style={{ position: 'absolute', right: 20, bottom: 20,
        fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
        color: textMute }}>1.00</div>
    </div>
  );
}

window.Heroes = [Hero1Globe, Hero2Ripple, Hero3Network, Hero4Tokens, Hero5Dial];

// ===== inline block =====
// Main onboarding prototype
// Slide shell that renders inside iOS or Android device

function OnboardingApp({ dark, lang, onToggleDark, onToggleLang, device, onEnterTutorial }) {
  const copy = window.ONBOARDING_COPY[lang];
  const [slide, setSlide] = React.useState(() => {
    const stored = parseInt(localStorage.getItem('sunx_slide') || '0', 10);
    return isNaN(stored) ? 0 : Math.max(0, Math.min(4, stored));
  });
  const [autoPlay, setAutoPlay] = React.useState(true);

  React.useEffect(() => {
    localStorage.setItem('sunx_slide', String(slide));
  }, [slide]);

  // Auto-advance
  React.useEffect(() => {
    if (!autoPlay) return;
    if (slide === 4) return; // don't auto-advance past the CTA
    const t = setTimeout(() => setSlide(s => Math.min(4, s + 1)), 6500);
    return () => clearTimeout(t);
  }, [slide, autoPlay]);

  const slideData = copy.slides[slide];
  const Hero = window.Heroes[slide];
  const moodByIdx = ['calm', 'focused', 'focused', 'excited', 'excited'];

  // Screen content
  const screen = (
    <div key={slide} style={{
      width: '100%', height: '100%', position: 'relative',
      display: 'flex', flexDirection: 'column',
      background: dark ? 'oklch(0.14 0.015 225)' : 'oklch(0.985 0.008 220)',
      animation: 'fadeSlide 0.5s ease-out',
      fontFamily: 'Geist, Inter, -apple-system, system-ui, sans-serif',
    }}>
      {/* Top bar: skip + progress */}
      <div style={{
        paddingTop: device === 'ios' ? 58 : 48,
        paddingLeft: 20, paddingRight: 20,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        flexShrink: 0,
      }}>
        {/* SUNX wordmark */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{
            width: 20, height: 20, borderRadius: 6,
            background: 'linear-gradient(135deg, oklch(0.65 0.14 230), oklch(0.72 0.14 155))',
            boxShadow: '0 2px 6px rgba(20,90,180,0.25)',
          }} />
          <span style={{
            fontFamily: 'Geist Mono, ui-monospace, monospace',
            fontSize: 11, letterSpacing: 2, fontWeight: 500,
            color: dark ? 'rgba(255,255,255,0.7)' : 'rgba(20,30,50,0.6)',
          }}>SUNX · SENSE</span>
        </div>
        <button onClick={() => setSlide(4)} style={{
          border: 'none', background: 'transparent',
          fontFamily: 'Geist, Inter, system-ui', fontSize: 13,
          color: dark ? 'rgba(255,255,255,0.55)' : 'rgba(20,30,50,0.5)',
          cursor: 'pointer', padding: '4px 8px',
        }}>{copy.skip}</button>
      </div>

      {/* Hero visual */}
      <div style={{
        margin: '20px auto 0',
        width: 342, position: 'relative',
        display: 'flex', justifyContent: 'center',
      }}>
        <Hero dark={dark} />
      </div>

      {/* Hero label strip */}
      <div style={{
        margin: '12px 24px 0',
        display: 'flex', alignItems: 'center', gap: 10,
        fontFamily: 'Geist Mono, ui-monospace, monospace',
        fontSize: 10, letterSpacing: 1.5,
        color: dark ? 'rgba(255,255,255,0.45)' : 'rgba(20,30,50,0.45)',
      }}>
        <div style={{
          width: 5, height: 5, borderRadius: '50%',
          background: 'oklch(0.72 0.14 155)',
          animation: 'dotBreath 1.6s ease-in-out infinite',
        }} />
        {slideData.heroLabel.toUpperCase()}
        <div style={{ flex: 1, height: 1, background: dark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)' }} />
        <span>
          <span style={{ color: dark ? 'rgba(255,255,255,0.7)' : 'rgba(20,30,50,0.7)', fontSize: 11 }}>{slideData.stat.value}</span>
          <span style={{ opacity: 0.7 }}>{slideData.stat.suffix}</span>
        </span>
      </div>

      {/* Copy block */}
      <div style={{ padding: '26px 24px 0', flex: 1 }}>
        <div style={{
          display: 'flex', alignItems: 'center', gap: 10, marginBottom: 10,
        }}>
          <SenseOrb size={32} dark={dark} mood={moodByIdx[slide]} />
          <div style={{
            fontFamily: 'Geist Mono, ui-monospace, monospace',
            fontSize: 10, letterSpacing: 1.8, fontWeight: 500,
            color: 'oklch(0.65 0.14 230)',
          }}>{slideData.eyebrow.toUpperCase()}</div>
        </div>
        <h1 style={{
          fontFamily: 'Geist, Inter, system-ui', fontWeight: 600,
          fontSize: 28, lineHeight: 1.15, letterSpacing: -0.8,
          color: dark ? '#fff' : '#0a1420',
          margin: '0 0 12px', textWrap: 'balance',
        }}>{slideData.title}</h1>
        <p style={{
          fontFamily: 'Geist, Inter, system-ui', fontSize: 15, lineHeight: 1.5,
          color: dark ? 'rgba(255,255,255,0.65)' : 'rgba(20,30,50,0.62)',
          margin: 0, textWrap: 'pretty',
          fontWeight: 400,
        }}>{slideData.body}</p>
      </div>

      {/* Footer: dots + CTA */}
      <div style={{
        padding: '0 24px',
        paddingBottom: device === 'ios' ? 40 : 32,
        display: 'flex', flexDirection: 'column', gap: 18,
        flexShrink: 0,
      }}>
        {/* Dots */}
        <div style={{ display: 'flex', gap: 6, justifyContent: 'center' }}>
          {[0,1,2,3,4].map(i => (
            <div key={i} onClick={() => { setAutoPlay(false); setSlide(i); }}
              style={{
                height: 6, borderRadius: 3,
                width: i === slide ? 24 : 6,
                background: i === slide
                  ? 'oklch(0.65 0.14 230)'
                  : dark ? 'rgba(255,255,255,0.15)' : 'rgba(20,30,50,0.12)',
                cursor: 'pointer',
                transition: 'all 0.35s cubic-bezier(.2,.9,.2,1)',
                position: 'relative', overflow: 'hidden',
              }}>
              {i === slide && autoPlay && slide !== 4 && (
                <div style={{
                  position: 'absolute', left: 0, top: 0, height: '100%',
                  background: 'rgba(255,255,255,0.45)',
                  animation: 'progressFill 6.5s linear forwards',
                  borderRadius: 3,
                }} />
              )}
            </div>
          ))}
        </div>

        {/* CTA */}
        <button onClick={() => {
          setAutoPlay(false);
          if (slide === 4) {
            // Enter tutorial flow
            if (onEnterTutorial) onEnterTutorial();
          } else {
            setSlide(slide + 1);
          }
        }} style={{
          height: 54, border: 'none', borderRadius: 16,
          background: slide === 4
            ? 'linear-gradient(135deg, oklch(0.65 0.14 230), oklch(0.58 0.16 220))'
            : dark ? '#fff' : '#0a1420',
          color: slide === 4 ? '#fff' : dark ? '#0a1420' : '#fff',
          fontFamily: 'Geist, Inter, system-ui',
          fontSize: 15, fontWeight: 600, letterSpacing: -0.2,
          cursor: 'pointer',
          boxShadow: slide === 4
            ? '0 10px 30px rgba(20,90,200,0.35), inset 0 1px 0 rgba(255,255,255,0.25)'
            : '0 2px 8px rgba(0,0,0,0.08)',
          display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
          transition: 'transform 0.15s',
        }}>
          {slide === 4 ? copy.getStarted : copy.next}
          <svg width="14" height="14" viewBox="0 0 14 14">
            <path d="M2 7h10m-4-4l4 4-4 4" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        </button>
      </div>
    </div>
  );

  return screen;
}

window.OnboardingApp = OnboardingApp;

// ===== inline block =====
const { useState, useEffect } = React;

  function App() {
    const [dark, setDark] = useState(TWEAK_DEFAULS.dark);
    const [lang, setLang] = useState(TWEAK_DEFAULS.lang);
    const [device, setDevice] = useState(TWEAK_DEFAULS.device);
    const [tweaksOn, setTweaksOn] = useState(false);
    const [mode, setMode] = useState(() => localStorage.getItem('sunx_mode') || 'onboarding');
    useEffect(() => { localStorage.setItem('sunx_mode', mode); }, [mode]);

    useEffect(() => {
      document.body.classList.toggle('dark', dark);
    }, [dark]);

    // Edit mode protocol
    useEffect(() => {
      const onMsg = (e) => {
        if (!e.data || typeof e.data !== 'object') return;
        if (e.data.type === '__activate_edit_mode') setTweaksOn(true);
        if (e.data.type === '__deactivate_edit_mode') setTweaksOn(false);
      };
      window.addEventListener('message', onMsg);
      window.parent.postMessage({ type: '__edit_mode_available' }, '*');
      return () => window.removeEventListener('message', onMsg);
    }, []);

    const persist = (patch) => {
      window.parent.postMessage({ type: '__edit_mode_set_keys', edits: patch }, '*');
    };

    const content = mode === 'tutorial' ? (
      <window.TutorialFlow dark={dark} lang={lang} device={device}
        onExit={() => { localStorage.removeItem('sunx_slide'); setMode('onboarding'); }} />
    ) : (
      <OnboardingApp dark={dark} lang={lang} device={device}
        onEnterTutorial={() => setMode('tutorial')} />
    );

    const phone = device === 'ios'
      ? <IOSDevice dark={dark} width={390} height={844}>{content}</IOSDevice>
      : <AndroidDevice dark={dark} width={390} height={844}>{content}</AndroidDevice>;

    return (
      <div className="phone-wrap" data-screen-label="SUNX Sense Onboarding">
        {phone}

        {tweaksOn && (
          <div className="tweaks">
            <h3>Tweaks</h3>

            <div className="tweak-row">
              <span>Appearance</span>
              <div className="seg">
                <button className={!dark ? 'active' : ''} onClick={() => { setDark(false); persist({ dark: false }); }}>LIGHT</button>
                <button className={dark ? 'active' : ''} onClick={() => { setDark(true); persist({ dark: true }); }}>DARK</button>
              </div>
            </div>

            <div className="tweak-row">
              <span>Language</span>
              <div className="seg">
                <button className={lang === 'en' ? 'active' : ''} onClick={() => { setLang('en'); persist({ lang: 'en' }); }}>EN</button>
                <button className={lang === 'tr' ? 'active' : ''} onClick={() => { setLang('tr'); persist({ lang: 'tr' }); }}>TR</button>
              </div>
            </div>

            <div className="tweak-row">
              <span>Device</span>
              <div className="seg">
                <button className={device === 'ios' ? 'active' : ''} onClick={() => { setDevice('ios'); persist({ device: 'ios' }); }}>iOS</button>
                <button className={device === 'android' ? 'active' : ''} onClick={() => { setDevice('android'); persist({ device: 'android' }); }}>AND</button>
              </div>
            </div>
            <div className="tweak-row">
              <span>Flow</span>
              <div class="seg">
                <button className={mode === 'onboarding' ? 'active' : ''} onClick={() => { localStorage.removeItem('sunx_slide'); setMode('onboarding'); }}>ONBOARD</button>
                <button className={mode === 'tutorial' ? 'active' : ''} onClick={() => setMode('tutorial')}>TUTORIAL</button>
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }

  ReactDOM.createRoot(document.getElementById('root')).render(<App />);
