// Auto-generated by extract.mjs from "SUNX Sense Consent.html".
// Edit the individual sections below; HMR will pick up changes.
import React from 'react';
import ReactDOM from 'react-dom/client';
// Babel-standalone code expected React/ReactDOM as globals.
window.React = React;
window.ReactDOM = { createRoot: ReactDOM.createRoot };

// ===== ios-frame.jsx =====

// iOS.jsx — Simplified iOS 26 (Liquid Glass) device frame
// Based on the iOS 26 UI Kit + Figma status bar spec. No assets, no deps.
// Exports: IOSDevice, IOSStatusBar, IOSNavBar, IOSGlassPill, IOSList, IOSListRow, IOSKeyboard

// ─────────────────────────────────────────────────────────────
// Status bar
// ─────────────────────────────────────────────────────────────
function IOSStatusBar({ dark = false, time = '9:41' }) {
  const c = dark ? '#fff' : '#000';
  return (
    <div style={{
      display: 'flex', gap: 154, alignItems: 'center', justifyContent: 'center',
      padding: '21px 24px 19px', boxSizing: 'border-box',
      position: 'relative', zIndex: 20, width: '100%',
    }}>
      <div style={{ flex: 1, height: 22, display: 'flex', alignItems: 'center', justifyContent: 'center', paddingTop: 1.5 }}>
        <span style={{
          fontFamily: '-apple-system, "SF Pro", system-ui', fontWeight: 590,
          fontSize: 17, lineHeight: '22px', color: c,
        }}>{time}</span>
      </div>
      <div style={{ flex: 1, height: 22, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 7, paddingTop: 1, paddingRight: 1 }}>
        <svg width="19" height="12" viewBox="0 0 19 12">
          <rect x="0" y="7.5" width="3.2" height="4.5" rx="0.7" fill={c}/>
          <rect x="4.8" y="5" width="3.2" height="7" rx="0.7" fill={c}/>
          <rect x="9.6" y="2.5" width="3.2" height="9.5" rx="0.7" fill={c}/>
          <rect x="14.4" y="0" width="3.2" height="12" rx="0.7" fill={c}/>
        </svg>
        <svg width="17" height="12" viewBox="0 0 17 12">
          <path d="M8.5 3.2C10.8 3.2 12.9 4.1 14.4 5.6L15.5 4.5C13.7 2.7 11.2 1.5 8.5 1.5C5.8 1.5 3.3 2.7 1.5 4.5L2.6 5.6C4.1 4.1 6.2 3.2 8.5 3.2Z" fill={c}/>
          <path d="M8.5 6.8C9.9 6.8 11.1 7.3 12 8.2L13.1 7.1C11.8 5.9 10.2 5.1 8.5 5.1C6.8 5.1 5.2 5.9 3.9 7.1L5 8.2C5.9 7.3 7.1 6.8 8.5 6.8Z" fill={c}/>
          <circle cx="8.5" cy="10.5" r="1.5" fill={c}/>
        </svg>
        <svg width="27" height="13" viewBox="0 0 27 13">
          <rect x="0.5" y="0.5" width="23" height="12" rx="3.5" stroke={c} strokeOpacity="0.35" fill="none"/>
          <rect x="2" y="2" width="20" height="9" rx="2" fill={c}/>
          <path d="M25 4.5V8.5C25.8 8.2 26.5 7.2 26.5 6.5C26.5 5.8 25.8 4.8 25 4.5Z" fill={c} fillOpacity="0.4"/>
        </svg>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Liquid glass pill — blur + tint + shine
// ─────────────────────────────────────────────────────────────
function IOSGlassPill({ children, dark = false, style = {} }) {
  return (
    <div style={{
      height: 44, minWidth: 44, borderRadius: 9999,
      position: 'relative', overflow: 'hidden',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      boxShadow: dark
        ? '0 2px 6px rgba(0,0,0,0.35), 0 6px 16px rgba(0,0,0,0.2)'
        : '0 1px 3px rgba(0,0,0,0.07), 0 3px 10px rgba(0,0,0,0.06)',
      ...style,
    }}>
      {/* blur + tint */}
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 9999,
        backdropFilter: 'blur(12px) saturate(180%)',
        WebkitBackdropFilter: 'blur(12px) saturate(180%)',
        background: dark ? 'rgba(120,120,128,0.28)' : 'rgba(255,255,255,0.5)',
      }} />
      {/* shine */}
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 9999,
        boxShadow: dark
          ? 'inset 1.5px 1.5px 1px rgba(255,255,255,0.15), inset -1px -1px 1px rgba(255,255,255,0.08)'
          : 'inset 1.5px 1.5px 1px rgba(255,255,255,0.7), inset -1px -1px 1px rgba(255,255,255,0.4)',
        border: dark ? '0.5px solid rgba(255,255,255,0.15)' : '0.5px solid rgba(0,0,0,0.06)',
      }} />
      <div style={{ position: 'relative', zIndex: 1, display: 'flex', alignItems: 'center', padding: '0 4px' }}>
        {children}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Navigation bar — glass pills + large title
// ─────────────────────────────────────────────────────────────
function IOSNavBar({ title = 'Title', dark = false, trailingIcon = true }) {
  const muted = dark ? 'rgba(255,255,255,0.6)' : '#404040';
  const text = dark ? '#fff' : '#000';
  const pillIcon = (content) => (
    <IOSGlassPill dark={dark}>
      <div style={{ width: 36, height: 36, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        {content}
      </div>
    </IOSGlassPill>
  );
  return (
    <div style={{
      display: 'flex', flexDirection: 'column', gap: 10,
      paddingTop: 62, paddingBottom: 10, position: 'relative', zIndex: 5,
    }}>
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '0 16px',
      }}>
        {/* back chevron */}
        {pillIcon(
          <svg width="12" height="20" viewBox="0 0 12 20" fill="none" style={{ marginLeft: -1 }}>
            <path d="M10 2L2 10l8 8" stroke={muted} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        )}
        {/* trailing ellipsis */}
        {trailingIcon && pillIcon(
          <svg width="22" height="6" viewBox="0 0 22 6">
            <circle cx="3" cy="3" r="2.5" fill={muted}/>
            <circle cx="11" cy="3" r="2.5" fill={muted}/>
            <circle cx="19" cy="3" r="2.5" fill={muted}/>
          </svg>
        )}
      </div>
      {/* large title */}
      <div style={{
        padding: '0 16px',
        fontFamily: '-apple-system, system-ui',
        fontSize: 34, fontWeight: 700, lineHeight: '41px',
        color: text, letterSpacing: 0.4,
      }}>{title}</div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Grouped list (inset card, r:26) + row (52px)
// ─────────────────────────────────────────────────────────────
function IOSListRow({ title, detail, icon, chevron = true, isLast = false, dark = false }) {
  const text = dark ? '#fff' : '#000';
  const sec = dark ? 'rgba(235,235,245,0.6)' : 'rgba(60,60,67,0.6)';
  const ter = dark ? 'rgba(235,235,245,0.3)' : 'rgba(60,60,67,0.3)';
  const sep = dark ? 'rgba(84,84,88,0.65)' : 'rgba(60,60,67,0.12)';
  return (
    <div style={{
      display: 'flex', alignItems: 'center', minHeight: 52,
      padding: '0 16px', position: 'relative',
      fontFamily: '-apple-system, system-ui', fontSize: 17,
      letterSpacing: -0.43,
    }}>
      {icon && (
        <div style={{
          width: 30, height: 30, borderRadius: 7, background: icon,
          marginRight: 12, flexShrink: 0,
        }} />
      )}
      <div style={{ flex: 1, color: text }}>{title}</div>
      {detail && <span style={{ color: sec, marginRight: 6 }}>{detail}</span>}
      {chevron && (
        <svg width="8" height="14" viewBox="0 0 8 14" style={{ flexShrink: 0 }}>
          <path d="M1 1l6 6-6 6" stroke={ter} strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      )}
      {!isLast && (
        <div style={{
          position: 'absolute', bottom: 0, right: 0,
          left: icon ? 58 : 16, height: 0.5, background: sep,
        }} />
      )}
    </div>
  );
}

function IOSList({ header, children, dark = false }) {
  const hc = dark ? 'rgba(235,235,245,0.6)' : 'rgba(60,60,67,0.6)';
  const bg = dark ? '#1C1C1E' : '#fff';
  return (
    <div>
      {header && (
        <div style={{
          fontFamily: '-apple-system, system-ui', fontSize: 13,
          color: hc, textTransform: 'uppercase',
          padding: '8px 36px 6px', letterSpacing: -0.08,
        }}>{header}</div>
      )}
      <div style={{
        background: bg, borderRadius: 26,
        margin: '0 16px', overflow: 'hidden',
      }}>{children}</div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Device frame
// ─────────────────────────────────────────────────────────────
function IOSDevice({
  children, width = 402, height = 874, dark = false,
  title, keyboard = false,
}) {
  return (
    <div style={{
      width, height, borderRadius: 48, overflow: 'hidden',
      position: 'relative', background: dark ? '#000' : '#F2F2F7',
      boxShadow: '0 40px 80px rgba(0,0,0,0.18), 0 0 0 1px rgba(0,0,0,0.12)',
      fontFamily: '-apple-system, system-ui, sans-serif',
      WebkitFontSmoothing: 'antialiased',
    }}>
      {/* dynamic island */}
      <div style={{
        position: 'absolute', top: 11, left: '50%', transform: 'translateX(-50%)',
        width: 126, height: 37, borderRadius: 24, background: '#000', zIndex: 50,
      }} />
      {/* status bar (absolute) */}
      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, zIndex: 10 }}>
        <IOSStatusBar dark={dark} />
      </div>
      {/* nav + content */}
      <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
        {title !== undefined && <IOSNavBar title={title} dark={dark} />}
        <div style={{ flex: 1, overflow: 'auto' }}>{children}</div>
        {keyboard && <IOSKeyboard dark={dark} />}
      </div>
      {/* home indicator — always on top */}
      <div style={{
        position: 'absolute', bottom: 0, left: 0, right: 0, zIndex: 60,
        height: 34, display: 'flex', justifyContent: 'center', alignItems: 'flex-end',
        paddingBottom: 8, pointerEvents: 'none',
      }}>
        <div style={{
          width: 139, height: 5, borderRadius: 100,
          background: dark ? 'rgba(255,255,255,0.7)' : 'rgba(0,0,0,0.25)',
        }} />
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Keyboard — iOS 26 liquid glass
// ─────────────────────────────────────────────────────────────
function IOSKeyboard({ dark = false }) {
  const glyph = dark ? 'rgba(255,255,255,0.7)' : '#595959';
  const sugg = dark ? 'rgba(255,255,255,0.6)' : '#333';
  const keyBg = dark ? 'rgba(255,255,255,0.22)' : 'rgba(255,255,255,0.85)';

  // special-key icons
  const icons = {
    shift: <svg width="19" height="17" viewBox="0 0 19 17"><path d="M9.5 1L1 9.5h4.5V16h8V9.5H18L9.5 1z" fill={glyph}/></svg>,
    del: <svg width="23" height="17" viewBox="0 0 23 17"><path d="M7 1h13a2 2 0 012 2v11a2 2 0 01-2 2H7l-6-7.5L7 1z" fill="none" stroke={glyph} strokeWidth="1.6" strokeLinejoin="round"/><path d="M10 5l7 7M17 5l-7 7" stroke={glyph} strokeWidth="1.6" strokeLinecap="round"/></svg>,
    ret: <svg width="20" height="14" viewBox="0 0 20 14"><path d="M18 1v6H4m0 0l4-4M4 7l4 4" fill="none" stroke="#fff" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>,
  };

  const key = (content, { w, flex, ret, fs = 25, k } = {}) => (
    <div key={k} style={{
      height: 42, borderRadius: 8.5,
      flex: flex ? 1 : undefined, width: w, minWidth: 0,
      background: ret ? '#08f' : keyBg,
      boxShadow: '0 1px 0 rgba(0,0,0,0.075)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      fontFamily: '-apple-system, "SF Compact", system-ui',
      fontSize: fs, fontWeight: 458, color: ret ? '#fff' : glyph,
    }}>{content}</div>
  );

  const row = (keys, pad = 0) => (
    <div style={{ display: 'flex', gap: 6.5, justifyContent: 'center', padding: `0 ${pad}px` }}>
      {keys.map(l => key(l, { flex: true, k: l }))}
    </div>
  );

  return (
    <div style={{
      position: 'relative', zIndex: 15, borderRadius: 27, overflow: 'hidden',
      padding: '11px 0 2px',
      display: 'flex', flexDirection: 'column', alignItems: 'center',
      boxShadow: dark
        ? '0 -2px 20px rgba(0,0,0,0.09)'
        : '0 -1px 6px rgba(0,0,0,0.018), 0 -3px 20px rgba(0,0,0,0.012)',
    }}>
      {/* liquid glass bg — same recipe as nav pills */}
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 27,
        backdropFilter: 'blur(12px) saturate(180%)',
        WebkitBackdropFilter: 'blur(12px) saturate(180%)',
        background: dark ? 'rgba(120,120,128,0.14)' : 'rgba(255,255,255,0.25)',
      }} />
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 27,
        boxShadow: dark
          ? 'inset 1.5px 1.5px 1px rgba(255,255,255,0.15)'
          : 'inset 1.5px 1.5px 1px rgba(255,255,255,0.7), inset -1px -1px 1px rgba(255,255,255,0.4)',
        border: dark ? '0.5px solid rgba(255,255,255,0.15)' : '0.5px solid rgba(0,0,0,0.06)',
        pointerEvents: 'none',
      }} />

      {/* autocorrect bar */}
      <div style={{
        display: 'flex', gap: 20, alignItems: 'center',
        padding: '8px 22px 13px', width: '100%', boxSizing: 'border-box',
        position: 'relative',
      }}>
        {['"The"', 'the', 'to'].map((w, i) => (
          <React.Fragment key={i}>
            {i > 0 && <div style={{ width: 1, height: 25, background: '#ccc', opacity: 0.3 }} />}
            <div style={{
              flex: 1, textAlign: 'center',
              fontFamily: '-apple-system, system-ui', fontSize: 17,
              color: sugg, letterSpacing: -0.43, lineHeight: '22px',
            }}>{w}</div>
          </React.Fragment>
        ))}
      </div>

      {/* key layout */}
      <div style={{
        display: 'flex', flexDirection: 'column', gap: 13,
        padding: '0 6.5px', width: '100%', boxSizing: 'border-box',
        position: 'relative',
      }}>
        {row(['q','w','e','r','t','y','u','i','o','p'])}
        {row(['a','s','d','f','g','h','j','k','l'], 20)}
        <div style={{ display: 'flex', gap: 14.25, alignItems: 'center' }}>
          {key(icons.shift, { w: 45, k: 'shift' })}
          <div style={{ display: 'flex', gap: 6.5, flex: 1 }}>
            {['z','x','c','v','b','n','m'].map(l => key(l, { flex: true, k: l }))}
          </div>
          {key(icons.del, { w: 45, k: 'del' })}
        </div>
        <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
          {key('ABC', { w: 92.25, fs: 18, k: 'abc' })}
          {key('', { flex: true, k: 'space' })}
          {key(icons.ret, { w: 92.25, ret: true, k: 'ret' })}
        </div>
      </div>

      {/* bottom spacer (emoji+mic area, icons omitted) */}
      <div style={{ height: 56, width: '100%', position: 'relative' }} />
    </div>
  );
}

Object.assign(window, {
  IOSDevice, IOSStatusBar, IOSNavBar, IOSGlassPill, IOSList, IOSListRow, IOSKeyboard,
});


// ===== android-frame.jsx =====

// Android.jsx — Simplified Android (Material 3) device frame
// Status bar + top app bar + content + gesture nav + keyboard.
// Based on Figma M3 spec. No dependencies, no image assets.

const MD_C = {
  surface: '#f4fbf8',
  surfaceVariant: '#dae5e1',
  inverseOnSurface: '#ecf2ef',
  secondaryContainer: '#cde8e1',
  primaryFixedDim: '#83d5c6',
  onSurface: '#171d1b',
  onSurfaceVar: '#49454f',
  onPrimaryContainer: '#00201c',
  primary: '#006a60',
  frameBorder: 'rgba(116,119,117,0.5)',
};

// ─────────────────────────────────────────────────────────────
// Status bar (time left, wifi/cell/battery right)
// ─────────────────────────────────────────────────────────────
function AndroidStatusBar({ dark = false }) {
  const c = dark ? '#fff' : MD_C.onSurface;
  return (
    <div style={{
      height: 40, display: 'flex', alignItems: 'center',
      justifyContent: 'space-between', padding: '0 16px',
      position: 'relative',
      fontFamily: 'Roboto, system-ui, sans-serif',
    }}>
      {/* time left */}
      <div style={{ width: 128, display: 'flex', alignItems: 'center', gap: 8 }}>
        <span style={{ fontSize: 14, fontWeight: 400, letterSpacing: 0.25, lineHeight: '20px', color: c }}>9:30</span>
      </div>
      {/* camera punch-hole (center) */}
      <div style={{
        position: 'absolute', left: '50%', top: 8, transform: 'translateX(-50%)',
        width: 24, height: 24, borderRadius: 100, background: '#2e2e2e',
      }} />
      {/* status icons right */}
      <div style={{ display: 'flex', alignItems: 'center' }}>
        <div style={{ display: 'flex', paddingRight: 2 }}>
          <svg width="16" height="16" viewBox="0 0 16 16" style={{ marginRight: -2 }}>
            <path d="M8 13.3L.67 5.97a10.37 10.37 0 0114.66 0L8 13.3z" fill={c}/>
          </svg>
          <svg width="16" height="16" viewBox="0 0 16 16" style={{ marginRight: -2 }}>
            <path d="M14.67 14.67V1.33L1.33 14.67h13.34z" fill={c}/>
          </svg>
        </div>
        <svg width="16" height="16" viewBox="0 0 16 16">
          <rect x="3.75" y="2" width="8.5" height="13" rx="1.5" fill={c}/>
          <rect x="5.5" y="0.9" width="5" height="2" rx="0.5" fill={c}/>
        </svg>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Top app bar (Material 3 small/medium)
// ─────────────────────────────────────────────────────────────
function AndroidAppBar({ title = 'Title', large = false }) {
  const iconDot = (
    <div style={{
      width: 48, height: 48, display: 'flex', alignItems: 'center', justifyContent: 'center',
    }}>
      <div style={{ width: 22, height: 22, borderRadius: '50%', background: MD_C.onSurfaceVar, opacity: 0.3 }} />
    </div>
  );
  return (
    <div style={{ background: MD_C.surface, padding: '4px 4px 0' }}>
      <div style={{ height: 56, display: 'flex', alignItems: 'center', gap: 4 }}>
        {iconDot}
        {!large && (
          <span style={{
            flex: 1, fontSize: 22, fontWeight: 400, color: MD_C.onSurface,
            fontFamily: 'Roboto, system-ui, sans-serif',
          }}>{title}</span>
        )}
        {large && <div style={{ flex: 1 }} />}
        {iconDot}
      </div>
      {large && (
        <div style={{
          padding: '16px 16px 20px',
          fontSize: 28, fontWeight: 400, color: MD_C.onSurface,
          fontFamily: 'Roboto, system-ui, sans-serif',
        }}>{title}</div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// List item (Material 3)
// ─────────────────────────────────────────────────────────────
function AndroidListItem({ headline, supporting, leading }) {
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 16,
      padding: '12px 16px', minHeight: 56, boxSizing: 'border-box',
      fontFamily: 'Roboto, system-ui, sans-serif',
    }}>
      {leading && (
        <div style={{
          width: 40, height: 40, borderRadius: '50%',
          background: MD_C.primary, color: '#fff',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: 18, fontWeight: 500, flexShrink: 0,
        }}>{leading}</div>
      )}
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 16, color: MD_C.onSurface, lineHeight: '24px' }}>{headline}</div>
        {supporting && (
          <div style={{ fontSize: 14, color: MD_C.onSurfaceVar, lineHeight: '20px' }}>{supporting}</div>
        )}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Gesture nav bar (pill)
// ─────────────────────────────────────────────────────────────
function AndroidNavBar({ dark = false }) {
  return (
    <div style={{
      height: 24, display: 'flex', alignItems: 'center', justifyContent: 'center',
    }}>
      <div style={{
        width: 108, height: 4, borderRadius: 2,
        background: dark ? '#fff' : MD_C.onSurface, opacity: 0.4,
      }} />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Device frame — wraps everything
// ─────────────────────────────────────────────────────────────
function AndroidDevice({
  children, width = 412, height = 892, dark = false,
  title, large = false, keyboard = false,
}) {
  return (
    <div style={{
      width, height, borderRadius: 18, overflow: 'hidden',
      background: dark ? '#1d1b20' : MD_C.surface,
      border: `8px solid ${MD_C.frameBorder}`,
      boxShadow: '0 30px 80px rgba(0,0,0,0.25)',
      display: 'flex', flexDirection: 'column', boxSizing: 'border-box',
    }}>
      <AndroidStatusBar dark={dark} />
      {title !== undefined && <AndroidAppBar title={title} large={large} />}
      <div style={{ flex: 1, overflow: 'auto' }}>
        {children}
      </div>
      {keyboard && <AndroidKeyboard />}
      <AndroidNavBar dark={dark} />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Keyboard — Gboard (Material 3)
// ─────────────────────────────────────────────────────────────
function AndroidKeyboard() {
  let _k = 0;
  const key = (l, { flex = 1, bg = MD_C.surface, r = 6, minW, fs = 21 } = {}) => (
    <div key={_k++} style={{
      height: 46, borderRadius: r, flex, minWidth: minW,
      background: bg, display: 'flex', alignItems: 'center', justifyContent: 'center',
      fontFamily: 'Roboto, system-ui', fontSize: fs,
      color: MD_C.onPrimaryContainer,
    }}>{l}</div>
  );
  const row = (keys, style = {}) => (
    <div style={{ display: 'flex', gap: 6, justifyContent: 'center', ...style }}>
      {keys.map(l => key(l))}
    </div>
  );
  return (
    <div style={{
      background: MD_C.inverseOnSurface, padding: '0 8px 8px',
      display: 'flex', flexDirection: 'column', gap: 4,
    }}>
      {/* navbar spacer (icons omitted) */}
      <div style={{ height: 44 }} />
      {/* key rows */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {row(['q','w','e','r','t','y','u','i','o','p'])}
        {row(['a','s','d','f','g','h','j','k','l'], { padding: '0 20px' })}
        <div style={{ display: 'flex', gap: 6 }}>
          {key('', { bg: MD_C.surfaceVariant })}
          <div style={{ display: 'flex', gap: 6, flex: 7, minWidth: 274 }}>
            {['z','x','c','v','b','n','m'].map(l => key(l))}
          </div>
          {key('', { bg: MD_C.surfaceVariant })}
        </div>
        <div style={{ display: 'flex', gap: 6 }}>
          {key('?123', { bg: MD_C.secondaryContainer, r: 100, minW: 58, fs: 14 })}
          {key(',', { bg: MD_C.surfaceVariant })}
          {key('', { flex: 3, minW: 154 })}
          {key('.', { bg: MD_C.surfaceVariant })}
          {key('', { bg: MD_C.primaryFixedDim, r: 100, minW: 58 })}
        </div>
      </div>
    </div>
  );
}

Object.assign(window, {
  AndroidDevice, AndroidStatusBar, AndroidAppBar, AndroidListItem, AndroidNavBar, AndroidKeyboard,
});


// ===== consent.jsx =====
// SUNX Sense — Beta Consent Flow (EK J — BETA AÇIK RIZA AKIŞI UX ŞABLONU)
// 8 screens implementing the spec from the user agreement appendix.
// Same format as gamification.jsx / tiers.jsx.

const C_PRIMARY = 'oklch(0.65 0.14 230)';
const C_ACCENT  = 'oklch(0.72 0.14 155)';
const C_AMBER   = 'oklch(0.78 0.14 75)';
const C_RED     = 'oklch(0.62 0.18 25)';
const C_VIOLET  = 'oklch(0.62 0.18 295)';

const CONSENT_COPY = {
  tr: {
    headerEyebrow: 'SUNX SENSE · BETA AÇIK RIZA AKIŞI · EK J',
    headerTitle: 'Sekiz ekranda KVKK + GDPR uyumlu Beta onayı.',
    headerSub: 'Karşılama, aydınlatma, yaş, sözleşme, sınır ötesi, granüler rıza, sistem izinleri, özet.',
    screens: [
      { id: 'welcome',   eyebrow: 'J.2.1 · KARŞILAMA',          label: 'Beta uyarısı' },
      { id: 'inform',    eyebrow: 'J.2.2 · AYDINLATMA',          label: 'KVKK m.10 / GDPR Art.13' },
      { id: 'age',       eyebrow: 'J.2.3 · YAŞ & ÜLKE',          label: 'COPPA / TMK 18+' },
      { id: 'contract',  eyebrow: 'J.2.4 · SÖZLEŞME',            label: 'Zorunlu kabul' },
      { id: 'transfer',  eyebrow: 'J.2.5 · YURTDIŞI AKTARIM',    label: 'KVKK m.9 açık rıza' },
      { id: 'granular',  eyebrow: 'J.2.6 · GRANÜLER RIZA',       label: 'Hepsi default kapalı' },
      { id: 'system',    eyebrow: 'J.2.7 · SİSTEM İZİNLERİ',     label: 'iOS / Android prompts' },
      { id: 'ready',     eyebrow: 'J.2.8 · HAZIRSIN',            label: 'Özet ve giriş' },
    ],
    welcome: {
      title: "Sense Beta'ya hoş geldin",
      sub: 'Hyperlocal hava kalitesi haritası — şu an Beta aşamasında',
      bullets: [
        { icon: '📍', t: 'Bulunduğun yerin çevresel verilerini gerçek zamanlı gör' },
        { icon: '🤖', t: 'AI destekli öneriler ve trend analizleri' },
        { icon: '🌍', t: 'Senin gibi binlerce kullanıcının verisiyle güçlenen bir ağ' },
      ],
      warnTitle: 'Beta uyarısı',
      warn: [
        'Sense şu an Beta aşamasında. Özellikler değişebilir, hatalar oluşabilir, ölçümler her zaman doğru olmayabilir.',
        'Beta ücretsizdir. Beta sırasında verdiğin veriler, ürünü iyileştirmek için kullanılabilir.',
        'Beta’yı dilediğin zaman bırakabilirsin.',
      ],
      primary: 'Devam Et',
      secondary: 'Daha Sonra',
    },
    inform: {
      title: 'Bilgilerin nasıl kullanılır?',
      sub: 'Sadece bilgilendirme — bu ekranda rıza alınmaz.',
      items: [
        { icon: '📍', h: 'KONUM',          t: 'Bulunduğun bölgenin hava kalitesini göstermek için konumun gerekli.' },
        { icon: '🌡️', h: 'ÇEVRESEL VERİ', t: 'CarboStar veya çevredeki sensörlerden gelen veriler haritalanır.' },
        { icon: '🤖', h: 'AI MODELLERİ',   t: 'Verilerin (anonimleştirilmiş olarak) çevresel tahmin modellerini iyileştirmek için kullanılabilir.' },
        { icon: '☁️', h: 'BULUT İŞLEME',   t: 'Verilerin global bulut sağlayıcılarda (AB ve ABD) güvenli olarak saklanır.' },
      ],
      link: 'Detaylı Gizlilik Politikası →',
      primary: 'Anladım, Devam Et',
    },
    age: {
      title: 'Devam etmeden önce birkaç soru',
      birthLabel: 'Doğum yılı',
      countryLabel: 'Bulunduğun ülke',
      note: 'Bulunduğun ülkeye göre uygulanacak veri koruma yasaları değişir.',
      birthValue: '1996',
      countryValue: 'Türkiye',
      primary: 'Devam Et',
    },
    contract: {
      title: 'Sözleşme ve Gizlilik',
      sub: 'Sözleşme özeti · tam metne aşağıdan ulaşabilirsin.',
      summary: [
        'Beta ücretsizdir ve gönüllü katılıma dayanır.',
        'Verilerin Hizmetlerin sunulması ve geliştirilmesi için işlenir.',
        'KVKK / GDPR hakların eksiksiz uygulanır.',
        'Beta’dan ayrılma ve hesap silme hakkın saklıdır.',
      ],
      boxes: [
        'Kullanıcı Sözleşmesini okudum ve kabul ediyorum',
        'Gizlilik Politikasını okudum ve verilerimin Sözleşmede açıklanan amaçlarla işlenmesini anladım',
        '18 yaşından büyük olduğumu beyan ederim',
      ],
      link: 'Tam Sözleşme Metni →',
      primary: 'İlerle',
    },
    transfer: {
      title: 'Verilerinin Yurtdışında İşlenmesi',
      body: "Sense'in çalışabilmesi için verilerin AB (Frankfurt, Dublin) ve ABD (Virginia, Oregon) bölgelerindeki bulut sunucularda işlenmesi gerekir. AWS / GCP / Azure tarafından sağlanır, TLS 1.3 ile şifrelenir. Tüm aktarımlar AB Standart Sözleşme Hükümleri (SCC) çerçevesinde yapılır.",
      box: 'Verilerimin bu kapsamda yurtdışına aktarılmasına açık rıza veriyorum',
      foot: "Bu rıza Sense’in temel işlevi için zorunludur. Kabul etmezsen Sense’i kullanamazsın. Türkiye içi sunucularla çalışan bir sürüm gelecekte sunulabilir.",
      primary: 'Kabul Et ve Devam',
      secondary: "Sense'i Kullanamıyorum",
    },
    granular: {
      title: 'Bunlardan hangilerine onay veriyorsun?',
      sub: "İsteğe bağlı. Hepsini reddetsen de Sense'i kullanabilirsin. İstediğin zaman Ayarlardan değiştirebilirsin.",
      toggles: [
        { k: 'gps',       h: 'Hassas GPS konumu',         t: 'Daha doğru harita ve hyperlocal öneri için.' },
        { k: 'ai',        h: 'AI modeli eğitimi',         t: "Anonimleştirilmiş verilerimle Sense’in tahmin modelleri iyileştirilebilir." },
        { k: 'analytics', h: 'Ticari analitik',           t: 'Anonim ve toplulaştırılmış verilerimin belediyeler, ESG, araştırma kurumlarıyla paylaşılması.' },
        { k: 'email',     h: 'Pazarlama e-postaları',     t: 'Yenilikler, ipuçları ve özel teklifler.' },
        { k: 'push',      h: 'Pazarlama push bildirim',   t: 'Yenilik ve kampanya bildirimleri.' },
        { k: 'research',  h: 'Araştırma programlarına katılım', t: 'Anonim akademik ve halk sağlığı katkısı (EK F).' },
      ],
      primary: 'Seçili Onayları Ver',
      secondary: 'Hiçbirine Vermiyorum',
    },
    system: {
      title: 'Birkaç son izin',
      sub: 'Bunlar sözleşmesel rızadan ayrıdır — işletim sistemi tarafından sunulur.',
      perms: [
        { icon: '📍', h: 'Konum',     t: 'Sense, çevredeki hava kalitesini gösterebilmek için konumuna ihtiyaç duyar.', when: 'Şimdi' },
        { icon: '🔔', h: 'Bildirim',  t: 'Hava kalitesi uyarıları ve önemli güncellemeler için.',                      when: 'Şimdi' },
        { icon: '📶', h: 'Bluetooth', t: 'CarboStar / SX Miner eşleştirme sırasında.',                                 when: 'Sonra' },
        { icon: '📷', h: 'Kamera',    t: 'Sadece QR kod taraması anında.',                                              when: 'Sonra' },
        { icon: '🛰', h: 'Takip Şeffaflığı (iOS)', t: 'Reklam yok — sadece pazarlama analitiği için gerekirse.',       when: 'Opsiyonel' },
      ],
      primary: 'İzinleri Aç',
    },
    ready: {
      title: 'Hazırsın!',
      sub: "Sense Beta’ya hoşgeldin.",
      summaryLabel: 'Verdiğin onaylar',
      note: 'Bu onayları istediğin zaman Profil → Gizlilik Ayarları → Açık Rızalar menüsünden değiştirebilirsin.',
      primary: "Sense'e Başla",
    },
    btnTrue: 'Verildi',
    btnFalse: 'Verilmedi',
  },
  en: {
    headerEyebrow: 'SUNX SENSE · BETA CONSENT FLOW · ANNEX J',
    headerTitle: 'Eight screens, KVKK + GDPR compliant Beta consent.',
    headerSub: 'Welcome, notice, age, contract, cross-border, granular, system perms, summary.',
    screens: [
      { id: 'welcome',   eyebrow: 'J.2.1 · WELCOME',         label: 'Beta warning' },
      { id: 'inform',    eyebrow: 'J.2.2 · NOTICE',           label: 'KVKK Art.10 / GDPR Art.13' },
      { id: 'age',       eyebrow: 'J.2.3 · AGE & REGION',     label: 'COPPA / 18+' },
      { id: 'contract',  eyebrow: 'J.2.4 · CONTRACT',         label: 'Required acceptance' },
      { id: 'transfer',  eyebrow: 'J.2.5 · CROSS-BORDER',     label: 'KVKK Art.9 explicit' },
      { id: 'granular',  eyebrow: 'J.2.6 · GRANULAR CONSENT', label: 'All default off' },
      { id: 'system',    eyebrow: 'J.2.7 · SYSTEM PERMS',     label: 'iOS / Android prompts' },
      { id: 'ready',     eyebrow: 'J.2.8 · YOU’RE READY', label: 'Summary & entry' },
    ],
    welcome: {
      title: 'Welcome to Sense Beta',
      sub: 'A hyperlocal air-quality map — currently in Beta',
      bullets: [
        { icon: '📍', t: 'See real-time environmental data around you' },
        { icon: '🤖', t: 'AI-powered suggestions and trend analysis' },
        { icon: '🌍', t: 'A network powered by thousands of users like you' },
      ],
      warnTitle: 'Beta notice',
      warn: [
        'Sense is currently in Beta. Features may change, errors may occur, measurements may not always be accurate.',
        'Beta is free. Data you share during Beta may be used to improve the product.',
        'You can leave Beta at any time.',
      ],
      primary: 'Continue',
      secondary: 'Later',
    },
    inform: {
      title: 'How your information is used',
      sub: 'Information only — no consent collected on this screen.',
      items: [
        { icon: '📍', h: 'LOCATION',         t: 'Your location is needed to show air quality for your area.' },
        { icon: '🌡️', h: 'ENVIRONMENTAL',    t: 'Data from CarboStar and nearby sensors is mapped.' },
        { icon: '🤖', h: 'AI MODELS',         t: 'Your (anonymised) data may improve environmental prediction models.' },
        { icon: '☁️', h: 'CLOUD PROCESSING',  t: 'Data is stored securely on global cloud providers (EU and US).' },
      ],
      link: 'Full Privacy Policy →',
      primary: 'Got it, continue',
    },
    age: {
      title: 'A few questions before you continue',
      birthLabel: 'Year of birth',
      countryLabel: 'Country of residence',
      note: 'Data protection laws applied depend on your country of residence.',
      birthValue: '1996',
      countryValue: 'Türkiye',
      primary: 'Continue',
    },
    contract: {
      title: 'Agreement & Privacy',
      sub: 'A short summary — full text available below.',
      summary: [
        'Beta is free and participation is voluntary.',
        'Your data is processed to provide and improve the Services.',
        'Your KVKK / GDPR rights apply in full.',
        'You retain the right to leave Beta and delete your account.',
      ],
      boxes: [
        'I have read and accept the User Agreement',
        'I have read the Privacy Policy and understand my data will be processed for the purposes stated in the Agreement',
        'I confirm I am 18 years or older',
      ],
      link: 'Full Agreement Text →',
      primary: 'Continue',
    },
    transfer: {
      title: 'Cross-border processing of your data',
      body: 'For Sense to function, your data must be processed on cloud servers in the EU (Frankfurt, Dublin) and US (Virginia, Oregon), provided by AWS / GCP / Azure, encrypted with TLS 1.3. International transfers are made under EU Standard Contractual Clauses (SCC).',
      box: 'I give explicit consent for my data to be transferred internationally as described',
      foot: 'This consent is required for Sense to function. If you decline, you cannot use Sense. A Türkiye-only version may be offered in the future.',
      primary: 'Accept & Continue',
      secondary: "Don't use Sense",
    },
    granular: {
      title: 'Which of these do you consent to?',
      sub: "Optional. You can use Sense even if you decline them all. Change anytime in Settings.",
      toggles: [
        { k: 'gps',       h: 'Precise GPS location',         t: 'For more accurate maps and hyperlocal suggestions.' },
        { k: 'ai',        h: 'AI model training',            t: "My anonymised data may improve Sense’s prediction models." },
        { k: 'analytics', h: 'Commercial analytics',         t: 'Anonymised aggregated data shared with municipalities, ESG, research institutions.' },
        { k: 'email',     h: 'Marketing emails',             t: 'Product updates, tips, and special offers.' },
        { k: 'push',      h: 'Marketing push notifications', t: 'Updates and campaign notifications.' },
        { k: 'research',  h: 'Research program participation', t: 'Anonymous contribution to academic and public-health research (Annex F).' },
      ],
      primary: 'Grant selected',
      secondary: 'Decline all',
    },
    system: {
      title: 'A few final permissions',
      sub: 'Separate from contractual consent — handled by your OS.',
      perms: [
        { icon: '📍', h: 'Location',  t: 'Sense needs your location to show ambient air quality around you.', when: 'Now' },
        { icon: '🔔', h: 'Notifications', t: 'For air-quality alerts and important updates.',                  when: 'Now' },
        { icon: '📶', h: 'Bluetooth', t: 'When pairing a CarboStar / SX Miner device.',                        when: 'Later' },
        { icon: '📷', h: 'Camera',    t: 'Only when scanning a QR code.',                                       when: 'Later' },
        { icon: '🛰', h: 'App Tracking (iOS)', t: 'No ads — only if marketing analytics requires it.',         when: 'Optional' },
      ],
      primary: 'Grant permissions',
    },
    ready: {
      title: "You’re ready!",
      sub: 'Welcome to Sense Beta.',
      summaryLabel: 'Your consents',
      note: 'You can change these anytime under Profile → Privacy Settings → Explicit Consents.',
      primary: 'Open Sense',
    },
    btnTrue: 'Granted',
    btnFalse: 'Declined',
  },
};

// --- Small shared bits ---

function Eyebrow({ children, dark }) {
  return (
    <div style={{
      fontFamily: 'Geist Mono, ui-monospace, monospace',
      fontSize: 10, letterSpacing: 1.8, fontWeight: 500,
      color: C_PRIMARY, margin: '14px 24px 0',
    }}>{children}</div>
  );
}

function ScreenTitle({ title, sub, dark }) {
  return (
    <div style={{ padding: '8px 24px 0' }}>
      <h1 style={{
        fontFamily: 'Geist', fontWeight: 600, fontSize: 22, lineHeight: 1.18, letterSpacing: -0.6,
        color: dark ? '#fff' : '#0a1420', margin: '0 0 6px', textWrap: 'balance',
      }}>{title}</h1>
      {sub && (
        <p style={{
          fontFamily: 'Geist', fontSize: 13, lineHeight: 1.5,
          color: dark ? 'rgba(255,255,255,0.6)' : 'rgba(20,30,50,0.6)',
          margin: 0, textWrap: 'pretty',
        }}>{sub}</p>
      )}
    </div>
  );
}

function PrimaryButton({ children, disabled, dark, fullWidth = true }) {
  return (
    <button disabled={disabled} style={{
      width: fullWidth ? '100%' : 'auto',
      height: 50, border: 'none', borderRadius: 14,
      background: disabled
        ? (dark ? 'rgba(255,255,255,0.08)' : 'rgba(20,30,50,0.08)')
        : 'linear-gradient(135deg, oklch(0.65 0.14 230), oklch(0.58 0.16 220))',
      color: disabled ? (dark ? 'rgba(255,255,255,0.3)' : 'rgba(20,30,50,0.3)') : '#fff',
      fontFamily: 'Geist', fontSize: 14, fontWeight: 600,
      cursor: disabled ? 'not-allowed' : 'pointer',
      boxShadow: disabled ? 'none' : '0 8px 20px rgba(20,90,200,0.3)',
      display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 8,
    }}>
      {children}
    </button>
  );
}

function GhostButton({ children, dark, fullWidth = true }) {
  return (
    <button style={{
      width: fullWidth ? '100%' : 'auto', height: 46, marginTop: 8,
      border: `1px solid ${dark ? 'rgba(255,255,255,0.16)' : 'rgba(20,30,50,0.16)'}`,
      borderRadius: 14, background: 'transparent',
      color: dark ? 'rgba(255,255,255,0.8)' : 'rgba(20,30,50,0.8)',
      fontFamily: 'Geist', fontSize: 13, fontWeight: 500, cursor: 'pointer',
    }}>{children}</button>
  );
}

function Checkbox({ checked, label, dark, sub }) {
  return (
    <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12, padding: '10px 0' }}>
      <div style={{
        width: 22, height: 22, flexShrink: 0, borderRadius: 6, marginTop: 2,
        border: `1.5px solid ${checked ? C_PRIMARY : (dark ? 'rgba(255,255,255,0.25)' : 'rgba(20,30,50,0.25)')}`,
        background: checked ? C_PRIMARY : 'transparent',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
      }}>
        {checked && <svg width="12" height="12" viewBox="0 0 12 12"><path d="M2 6l3 3 5-6" stroke="#fff" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/></svg>}
      </div>
      <div style={{ flex: 1 }}>
        <div style={{ fontFamily: 'Geist', fontSize: 13, lineHeight: 1.4, color: dark ? '#fff' : '#0a1420' }}>{label}</div>
        {sub && <div style={{ fontFamily: 'Geist', fontSize: 11, marginTop: 2,
          color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)' }}>{sub}</div>}
      </div>
    </div>
  );
}

function Toggle({ on, dark }) {
  return (
    <div style={{
      width: 38, height: 22, borderRadius: 999, flexShrink: 0,
      background: on ? C_PRIMARY : (dark ? 'rgba(255,255,255,0.16)' : 'rgba(20,30,50,0.16)'),
      position: 'relative', transition: 'background 0.2s',
    }}>
      <div style={{
        position: 'absolute', top: 2, left: on ? 18 : 2,
        width: 18, height: 18, borderRadius: 999, background: '#fff',
        transition: 'left 0.2s', boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
      }}/>
    </div>
  );
}

// --- Screen layouts ---

function WelcomeScreen({ dark, lang, device, copy }) {
  const c = copy.welcome;
  return (
    <Shell dark={dark} device={device}>
      <Eyebrow dark={dark}>{copy.screens[0].eyebrow}</Eyebrow>
      <ScreenTitle title={c.title} sub={c.sub} dark={dark} />
      <div style={{ padding: '14px 24px 0', flex: 1, display: 'flex', flexDirection: 'column', gap: 10 }}>
        {c.bullets.map((b, i) => (
          <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'flex-start',
            padding: 12, borderRadius: 12,
            background: dark ? 'rgba(255,255,255,0.04)' : 'rgba(20,30,50,0.04)' }}>
            <span style={{ fontSize: 18 }}>{b.icon}</span>
            <span style={{ fontFamily: 'Geist', fontSize: 13, lineHeight: 1.45,
              color: dark ? 'rgba(255,255,255,0.85)' : 'rgba(20,30,50,0.85)' }}>{b.t}</span>
          </div>
        ))}
        <div style={{
          marginTop: 10, padding: 14, borderRadius: 14,
          border: `1.5px solid ${C_AMBER}`,
          background: dark ? 'oklch(0.25 0.04 75 / 0.25)' : 'oklch(0.97 0.05 75 / 0.7)',
        }}>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 8 }}>
            <span style={{ fontSize: 16 }}>⚠️</span>
            <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 10,
              letterSpacing: 1.6, color: C_AMBER, fontWeight: 600,
              textTransform: 'uppercase' }}>{c.warnTitle}</span>
          </div>
          {c.warn.map((w, i) => (
            <div key={i} style={{ fontFamily: 'Geist', fontSize: 12, lineHeight: 1.45, marginTop: i ? 6 : 0,
              color: dark ? 'rgba(255,255,255,0.78)' : 'rgba(20,30,50,0.78)' }}>
              <span style={{ color: i ? C_ACCENT : C_AMBER, marginRight: 6 }}>{i ? '✓' : '•'}</span>{w}
            </div>
          ))}
        </div>
      </div>
      <Footer device={device}>
        <PrimaryButton dark={dark}>{c.primary} →</PrimaryButton>
        <GhostButton dark={dark}>{c.secondary}</GhostButton>
      </Footer>
    </Shell>
  );
}

function InformScreen({ dark, device, copy }) {
  const c = copy.inform;
  return (
    <Shell dark={dark} device={device}>
      <Eyebrow dark={dark}>{copy.screens[1].eyebrow}</Eyebrow>
      <ScreenTitle title={c.title} sub={c.sub} dark={dark} />
      <div style={{ padding: '14px 24px 0', flex: 1, display: 'flex', flexDirection: 'column', gap: 10 }}>
        {c.items.map((it, i) => (
          <div key={i} style={{ display: 'flex', gap: 12, padding: 12, borderRadius: 12,
            background: dark ? 'rgba(255,255,255,0.04)' : 'rgba(20,30,50,0.04)' }}>
            <div style={{ fontSize: 22, flexShrink: 0 }}>{it.icon}</div>
            <div>
              <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 10,
                letterSpacing: 1.6, color: C_PRIMARY, fontWeight: 600 }}>{it.h}</div>
              <div style={{ fontFamily: 'Geist', fontSize: 12.5, lineHeight: 1.45, marginTop: 4,
                color: dark ? 'rgba(255,255,255,0.78)' : 'rgba(20,30,50,0.78)' }}>{it.t}</div>
            </div>
          </div>
        ))}
        <div style={{ marginTop: 4, fontFamily: 'Geist', fontSize: 12, color: C_PRIMARY, fontWeight: 500 }}>{c.link}</div>
      </div>
      <Footer device={device}>
        <PrimaryButton dark={dark}>{c.primary} →</PrimaryButton>
      </Footer>
    </Shell>
  );
}

function AgeScreen({ dark, device, copy }) {
  const c = copy.age;
  return (
    <Shell dark={dark} device={device}>
      <Eyebrow dark={dark}>{copy.screens[2].eyebrow}</Eyebrow>
      <ScreenTitle title={c.title} dark={dark} />
      <div style={{ padding: '20px 24px 0', flex: 1, display: 'flex', flexDirection: 'column', gap: 16 }}>
        <FieldRow label={c.birthLabel} value={c.birthValue} dark={dark} />
        <FieldRow label={c.countryLabel} value={c.countryValue} dark={dark} flag="🇹🇷" />
        <div style={{
          padding: 12, borderRadius: 12,
          background: dark ? 'oklch(0.22 0.04 230 / 0.4)' : 'oklch(0.96 0.03 230 / 0.7)',
          border: `1px solid ${dark ? 'rgba(110,160,220,0.25)' : 'rgba(110,160,220,0.35)'}`,
        }}>
          <div style={{ display: 'flex', gap: 8, alignItems: 'flex-start' }}>
            <span style={{ fontSize: 14 }}>ℹ️</span>
            <span style={{ fontFamily: 'Geist', fontSize: 12, lineHeight: 1.45,
              color: dark ? 'rgba(255,255,255,0.78)' : 'rgba(20,30,50,0.78)' }}>{c.note}</span>
          </div>
        </div>
      </div>
      <Footer device={device}><PrimaryButton dark={dark}>{c.primary} →</PrimaryButton></Footer>
    </Shell>
  );
}

function FieldRow({ label, value, dark, flag }) {
  return (
    <div>
      <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 10,
        letterSpacing: 1.6, color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)',
        textTransform: 'uppercase', marginBottom: 6 }}>{label}</div>
      <div style={{
        height: 50, padding: '0 14px', borderRadius: 12,
        background: dark ? 'rgba(255,255,255,0.06)' : 'rgba(20,30,50,0.05)',
        border: `1px solid ${dark ? 'rgba(255,255,255,0.1)' : 'rgba(20,30,50,0.08)'}`,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        fontFamily: 'Geist', fontSize: 14, color: dark ? '#fff' : '#0a1420',
      }}>
        <span>{flag ? `${flag}  ` : ''}{value}</span>
        <svg width="14" height="14" viewBox="0 0 14 14"><path d="M3 5l4 4 4-4" stroke="currentColor" strokeWidth="1.6" fill="none" strokeLinecap="round" strokeLinejoin="round"/></svg>
      </div>
    </div>
  );
}

function ContractScreen({ dark, device, copy }) {
  const c = copy.contract;
  return (
    <Shell dark={dark} device={device}>
      <Eyebrow dark={dark}>{copy.screens[3].eyebrow}</Eyebrow>
      <ScreenTitle title={c.title} sub={c.sub} dark={dark} />
      <div style={{ padding: '14px 24px 0', flex: 1 }}>
        <div style={{ padding: 12, borderRadius: 12, marginBottom: 14,
          background: dark ? 'rgba(255,255,255,0.04)' : 'rgba(20,30,50,0.04)' }}>
          {c.summary.map((s, i) => (
            <div key={i} style={{
              fontFamily: 'Geist', fontSize: 12, lineHeight: 1.45, marginTop: i ? 6 : 0,
              color: dark ? 'rgba(255,255,255,0.78)' : 'rgba(20,30,50,0.78)',
            }}>
              <span style={{ color: C_ACCENT, marginRight: 6 }}>•</span>{s}
            </div>
          ))}
          <div style={{ marginTop: 10, fontFamily: 'Geist', fontSize: 12, color: C_PRIMARY, fontWeight: 500 }}>{c.link}</div>
        </div>
        {c.boxes.map((b, i) => (
          <Checkbox key={i} checked={i < 2} label={b} dark={dark} />
        ))}
      </div>
      <Footer device={device}><PrimaryButton dark={dark} disabled>{c.primary} →</PrimaryButton></Footer>
    </Shell>
  );
}

function TransferScreen({ dark, device, copy }) {
  const c = copy.transfer;
  return (
    <Shell dark={dark} device={device}>
      <Eyebrow dark={dark}>{copy.screens[4].eyebrow}</Eyebrow>
      <ScreenTitle title={c.title} dark={dark} />
      <div style={{ padding: '14px 24px 0', flex: 1 }}>
        <p style={{ fontFamily: 'Geist', fontSize: 12.5, lineHeight: 1.55,
          color: dark ? 'rgba(255,255,255,0.78)' : 'rgba(20,30,50,0.78)', margin: 0 }}>{c.body}</p>
        <div style={{ display: 'flex', gap: 8, marginTop: 14, flexWrap: 'wrap' }}>
          {['🇩🇪 Frankfurt', '🇮🇪 Dublin', '🇺🇸 Virginia', '🇺🇸 Oregon', 'TLS 1.3', 'SCC'].map((t, i) => (
            <span key={i} style={{
              fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 10, letterSpacing: 1,
              padding: '6px 10px', borderRadius: 999,
              background: dark ? 'rgba(255,255,255,0.06)' : 'rgba(20,30,50,0.06)',
              color: dark ? 'rgba(255,255,255,0.8)' : 'rgba(20,30,50,0.8)',
            }}>{t}</span>
          ))}
        </div>
        <div style={{ marginTop: 18, padding: 12, borderRadius: 12,
          border: `1.5px solid ${C_PRIMARY}`,
          background: dark ? 'oklch(0.22 0.04 230 / 0.3)' : 'oklch(0.97 0.03 230 / 0.5)' }}>
          <Checkbox checked={true} label={c.box} dark={dark} />
        </div>
        <p style={{ marginTop: 14, fontFamily: 'Geist', fontSize: 11.5, lineHeight: 1.5,
          color: dark ? 'rgba(255,255,255,0.55)' : 'rgba(20,30,50,0.55)' }}>{c.foot}</p>
      </div>
      <Footer device={device}>
        <PrimaryButton dark={dark}>{c.primary} →</PrimaryButton>
        <GhostButton dark={dark}>{c.secondary}</GhostButton>
      </Footer>
    </Shell>
  );
}

function GranularScreen({ dark, device, copy }) {
  const c = copy.granular;
  return (
    <Shell dark={dark} device={device}>
      <Eyebrow dark={dark}>{copy.screens[5].eyebrow}</Eyebrow>
      <ScreenTitle title={c.title} sub={c.sub} dark={dark} />
      <div style={{ padding: '12px 24px 0', flex: 1, overflow: 'hidden' }}>
        {c.toggles.map((t, i) => {
          const on = i === 0 || i === 5; // illustrative
          return (
            <div key={t.k} style={{
              display: 'flex', alignItems: 'flex-start', gap: 12,
              padding: '10px 0',
              borderTop: i ? `1px solid ${dark ? 'rgba(255,255,255,0.06)' : 'rgba(20,30,50,0.06)'}` : 'none',
            }}>
              <div style={{ flex: 1 }}>
                <div style={{ fontFamily: 'Geist', fontSize: 13, fontWeight: 500,
                  color: dark ? '#fff' : '#0a1420' }}>{t.h}</div>
                <div style={{ fontFamily: 'Geist', fontSize: 11.5, lineHeight: 1.4, marginTop: 2,
                  color: dark ? 'rgba(255,255,255,0.55)' : 'rgba(20,30,50,0.55)' }}>{t.t}</div>
              </div>
              <Toggle on={on} dark={dark} />
            </div>
          );
        })}
      </div>
      <Footer device={device}>
        <PrimaryButton dark={dark}>{c.primary}</PrimaryButton>
        <GhostButton dark={dark}>{c.secondary}</GhostButton>
      </Footer>
    </Shell>
  );
}

function SystemScreen({ dark, device, copy }) {
  const c = copy.system;
  return (
    <Shell dark={dark} device={device}>
      <Eyebrow dark={dark}>{copy.screens[6].eyebrow}</Eyebrow>
      <ScreenTitle title={c.title} sub={c.sub} dark={dark} />
      <div style={{ padding: '12px 24px 0', flex: 1 }}>
        {c.perms.map((p, i) => (
          <div key={i} style={{
            display: 'flex', alignItems: 'center', gap: 12, padding: 12, marginBottom: 8,
            borderRadius: 12,
            background: dark ? 'rgba(255,255,255,0.04)' : 'rgba(20,30,50,0.04)',
          }}>
            <div style={{ fontSize: 20 }}>{p.icon}</div>
            <div style={{ flex: 1 }}>
              <div style={{ fontFamily: 'Geist', fontSize: 13, fontWeight: 500,
                color: dark ? '#fff' : '#0a1420' }}>{p.h}</div>
              <div style={{ fontFamily: 'Geist', fontSize: 11.5, lineHeight: 1.4, marginTop: 2,
                color: dark ? 'rgba(255,255,255,0.55)' : 'rgba(20,30,50,0.55)' }}>{p.t}</div>
            </div>
            <span style={{
              fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.4,
              padding: '4px 8px', borderRadius: 999,
              background: dark ? 'rgba(255,255,255,0.08)' : 'rgba(20,30,50,0.08)',
              color: dark ? 'rgba(255,255,255,0.7)' : 'rgba(20,30,50,0.7)',
              textTransform: 'uppercase',
            }}>{p.when}</span>
          </div>
        ))}
      </div>
      <Footer device={device}><PrimaryButton dark={dark}>{c.primary} →</PrimaryButton></Footer>
    </Shell>
  );
}

function ReadyScreen({ dark, device, copy }) {
  const c = copy.ready;
  const summary = [
    { k: copy.granular.toggles[0].h, on: true },
    { k: copy.granular.toggles[1].h, on: false },
    { k: copy.granular.toggles[2].h, on: false },
    { k: copy.granular.toggles[3].h, on: false },
    { k: copy.granular.toggles[4].h, on: false },
    { k: copy.granular.toggles[5].h, on: true },
  ];
  return (
    <Shell dark={dark} device={device}>
      <Eyebrow dark={dark}>{copy.screens[7].eyebrow}</Eyebrow>
      <ScreenTitle title={c.title} sub={c.sub} dark={dark} />
      <div style={{ padding: '14px 24px 0', flex: 1 }}>
        <div style={{ display: 'flex', justifyContent: 'center', margin: '6px 0 14px' }}>
          <div style={{
            width: 88, height: 88, borderRadius: 999,
            background: 'linear-gradient(135deg, oklch(0.72 0.14 155), oklch(0.65 0.14 230))',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            boxShadow: '0 8px 28px rgba(20,90,200,0.3)',
          }}>
            <svg width="42" height="42" viewBox="0 0 42 42">
              <path d="M10 22l8 8 14-18" stroke="#fff" strokeWidth="3.5" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </div>
        </div>
        <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 10,
          letterSpacing: 1.6, color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)',
          textTransform: 'uppercase', marginBottom: 8 }}>{c.summaryLabel}</div>
        <div style={{ padding: 10, borderRadius: 12,
          background: dark ? 'rgba(255,255,255,0.04)' : 'rgba(20,30,50,0.04)' }}>
          {summary.map((s, i) => (
            <div key={i} style={{
              display: 'flex', justifyContent: 'space-between', alignItems: 'center',
              padding: '6px 4px',
              borderTop: i ? `1px solid ${dark ? 'rgba(255,255,255,0.06)' : 'rgba(20,30,50,0.06)'}` : 'none',
            }}>
              <span style={{ fontFamily: 'Geist', fontSize: 12,
                color: dark ? 'rgba(255,255,255,0.8)' : 'rgba(20,30,50,0.8)' }}>{s.k}</span>
              <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 10,
                letterSpacing: 1, color: s.on ? C_ACCENT : (dark ? 'rgba(255,255,255,0.4)' : 'rgba(20,30,50,0.4)'),
                fontWeight: 600 }}>
                {s.on ? `✓ ${copy.btnTrue}` : `✗ ${copy.btnFalse}`}
              </span>
            </div>
          ))}
        </div>
        <p style={{ marginTop: 14, fontFamily: 'Geist', fontSize: 11.5, lineHeight: 1.5,
          color: dark ? 'rgba(255,255,255,0.55)' : 'rgba(20,30,50,0.55)' }}>{c.note}</p>
      </div>
      <Footer device={device}><PrimaryButton dark={dark}>{c.primary} →</PrimaryButton></Footer>
    </Shell>
  );
}

// --- Shell + footer ---

function Shell({ dark, device, children }) {
  return (
    <div style={{
      width: '100%', height: '100%', position: 'relative',
      display: 'flex', flexDirection: 'column',
      background: dark ? 'oklch(0.14 0.015 225)' : 'oklch(0.985 0.008 220)',
      animation: 'fadeSlide 0.5s ease-out',
      fontFamily: 'Geist, Inter, -apple-system, system-ui, sans-serif',
      paddingTop: device === 'ios' ? 58 : 48,
    }}>
      {children}
    </div>
  );
}

function Footer({ device, children }) {
  return (
    <div style={{
      padding: '16px 24px',
      paddingBottom: device === 'ios' ? 40 : 32,
      display: 'flex', flexDirection: 'column',
    }}>{children}</div>
  );
}

// --- Dispatcher ---

function ConsentScreen({ dark, lang, device, idx }) {
  const copy = window.CONSENT_COPY[lang];
  const id = copy.screens[idx].id;
  switch (id) {
    case 'welcome':  return <WelcomeScreen  dark={dark} lang={lang} device={device} copy={copy} />;
    case 'inform':   return <InformScreen   dark={dark}             device={device} copy={copy} />;
    case 'age':      return <AgeScreen      dark={dark}             device={device} copy={copy} />;
    case 'contract': return <ContractScreen dark={dark}             device={device} copy={copy} />;
    case 'transfer': return <TransferScreen dark={dark}             device={device} copy={copy} />;
    case 'granular': return <GranularScreen dark={dark}             device={device} copy={copy} />;
    case 'system':   return <SystemScreen   dark={dark}             device={device} copy={copy} />;
    case 'ready':    return <ReadyScreen    dark={dark}             device={device} copy={copy} />;
    default:         return null;
  }
}

window.ConsentScreen = ConsentScreen;
window.CONSENT_COPY = CONSENT_COPY;


// ===== inline block =====
const { useState, useEffect } = React;

function App() {
  const [state, setState] = useState(() => ({ ...TWEAK_DEFAULS }));
  const set = (k, v) => {
    setState(s => ({ ...s, [k]: v }));
    window.parent.postMessage({ type: '__edit_mode_set_keys', edits: { [k]: v } }, '*');
  };

  useEffect(() => {
    document.body.classList.toggle('dark', state.dark);
    const copy = window.CONSENT_COPY[state.lang];
    document.getElementById('hdr-eyebrow').textContent = copy.headerEyebrow;
    document.getElementById('hdr-title').textContent = copy.headerTitle;
    document.getElementById('hdr-sub').textContent = copy.headerSub;
  }, [state.dark, state.lang]);

  const screens = window.CONSENT_COPY[state.lang].screens;

  return (
    <>
      <div className="grid">
        {screens.map((s, i) => {
          const content = (
            <window.ConsentScreen
              dark={state.dark} lang={state.lang} device={state.device} idx={i}
            />
          );
          const phone = state.device === 'ios'
            ? <window.IOSDevice dark={state.dark} width={390} height={844}>{content}</window.IOSDevice>
            : <window.AndroidDevice dark={state.dark} width={390} height={844}>{content}</window.AndroidDevice>;

          return (
            <div key={i} data-screen-label={`${String(i+1).padStart(2,'0')} ${s.id}`}>
              {phone}
              <div className="label">{s.eyebrow}</div>
            </div>
          );
        })}
      </div>

      <div className="tweaks">
        <h3>Tweaks</h3>
        <div className="tweak-row">
          <span>Theme</span>
          <div className="seg">
            <button className={!state.dark ? 'active' : ''} onClick={() => set('dark', false)}>LIGHT</button>
            <button className={state.dark ? 'active' : ''} onClick={() => set('dark', true)}>DARK</button>
          </div>
        </div>
        <div className="tweak-row">
          <span>Language</span>
          <div className="seg">
            <button className={state.lang === 'tr' ? 'active' : ''} onClick={() => set('lang', 'tr')}>TR</button>
            <button className={state.lang === 'en' ? 'active' : ''} onClick={() => set('lang', 'en')}>EN</button>
          </div>
        </div>
        <div className="tweak-row">
          <span>Device</span>
          <div className="seg">
            <button className={state.device === 'ios' ? 'active' : ''} onClick={() => set('device', 'ios')}>iOS</button>
            <button className={state.device === 'android' ? 'active' : ''} onClick={() => set('device', 'android')}>AND</button>
          </div>
        </div>
      </div>
    </>
  );
}

setTimeout(() => {
  ReactDOM.createRoot(document.getElementById('root')).render(<App />);
}, 100);
