#!/usr/bin/env node
// briefs/build.mjs — scans briefs/data/*.json, renders each via the shared
// render-core, and rebuilds briefs/manifest.json from scratch. Idempotent.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderBrief, manifestEntry } from './render-core.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const DATA_DIR = path.join(HERE, 'data');
const TEMPLATE = path.join(HERE, 'template.html');
const MANIFEST = path.join(HERE, 'manifest.json');

const tpl = fs.readFileSync(TEMPLATE, 'utf8');

if (!fs.existsSync(DATA_DIR)) {
  console.error('✗ briefs/data/ not found. Create it and add JSON files.');
  process.exit(1);
}

const files = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('.json')).sort();
if (!files.length) console.warn('⚠ No briefs in briefs/data/. Manifest will be empty.');

console.log(`Building ${files.length} brief${files.length === 1 ? '' : 's'} from briefs/data/`);

const renderedFilenames = new Set();
const entries = [];

for (const f of files) {
  const slug = path.basename(f, '.json');
  const data = JSON.parse(fs.readFileSync(path.join(DATA_DIR, f), 'utf8'));
  const outputFilename = data.meta.outputFilename || `${data.meta.client} ${data.meta.project} Mission Brief.html`;

  if (data.meta.skipBuild) {
    console.log(`  · ${slug} → ${outputFilename} (skipBuild: hand-crafted)`);
  } else {
    console.log(`  · ${slug} → ${outputFilename}`);
    const { html, leftover } = renderBrief(tpl, data);
    if (leftover.length) console.warn(`  ⚠ ${slug}: ${leftover.length} unresolved token(s):`, leftover);
    fs.writeFileSync(path.join(ROOT, outputFilename), html);
  }
  renderedFilenames.add(outputFilename);
  entries.push(manifestEntry(data, slug, outputFilename));
}

// Stale-output cleanup
let prev = { briefs: [] };
try { prev = JSON.parse(fs.readFileSync(MANIFEST, 'utf8')); } catch {}
for (const oldEntry of prev.briefs || []) {
  if (!renderedFilenames.has(oldEntry.url) && oldEntry.handcrafted !== true) {
    const stale = path.join(ROOT, oldEntry.url);
    if (fs.existsSync(stale)) {
      fs.unlinkSync(stale);
      console.log(`  ✗ removed stale: ${oldEntry.url}`);
    }
  }
}

const manifest = {
  $comment: 'Auto-generated by briefs/build.mjs from briefs/data/*.json. Do not edit by hand.',
  generatedAt: new Date().toISOString(),
  briefs: entries,
};
fs.writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + '\n');
console.log(`✓ manifest.json updated (${entries.length} brief${entries.length === 1 ? '' : 's'})`);
