// Auto-generated by extract.mjs from "SUNX Sense Tiers.html".
// Edit the individual sections below; HMR will pick up changes.
import React from 'react';
import ReactDOM from 'react-dom/client';
// Babel-standalone code expected React/ReactDOM as globals.
window.React = React;
window.ReactDOM = { createRoot: ReactDOM.createRoot };

// ===== ios-frame.jsx =====

// iOS.jsx — Simplified iOS 26 (Liquid Glass) device frame
// Based on the iOS 26 UI Kit + Figma status bar spec. No assets, no deps.
// Exports: IOSDevice, IOSStatusBar, IOSNavBar, IOSGlassPill, IOSList, IOSListRow, IOSKeyboard

// ─────────────────────────────────────────────────────────────
// Status bar
// ─────────────────────────────────────────────────────────────
function IOSStatusBar({ dark = false, time = '9:41' }) {
  const c = dark ? '#fff' : '#000';
  return (
    <div style={{
      display: 'flex', gap: 154, alignItems: 'center', justifyContent: 'center',
      padding: '21px 24px 19px', boxSizing: 'border-box',
      position: 'relative', zIndex: 20, width: '100%',
    }}>
      <div style={{ flex: 1, height: 22, display: 'flex', alignItems: 'center', justifyContent: 'center', paddingTop: 1.5 }}>
        <span style={{
          fontFamily: '-apple-system, "SF Pro", system-ui', fontWeight: 590,
          fontSize: 17, lineHeight: '22px', color: c,
        }}>{time}</span>
      </div>
      <div style={{ flex: 1, height: 22, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 7, paddingTop: 1, paddingRight: 1 }}>
        <svg width="19" height="12" viewBox="0 0 19 12">
          <rect x="0" y="7.5" width="3.2" height="4.5" rx="0.7" fill={c}/>
          <rect x="4.8" y="5" width="3.2" height="7" rx="0.7" fill={c}/>
          <rect x="9.6" y="2.5" width="3.2" height="9.5" rx="0.7" fill={c}/>
          <rect x="14.4" y="0" width="3.2" height="12" rx="0.7" fill={c}/>
        </svg>
        <svg width="17" height="12" viewBox="0 0 17 12">
          <path d="M8.5 3.2C10.8 3.2 12.9 4.1 14.4 5.6L15.5 4.5C13.7 2.7 11.2 1.5 8.5 1.5C5.8 1.5 3.3 2.7 1.5 4.5L2.6 5.6C4.1 4.1 6.2 3.2 8.5 3.2Z" fill={c}/>
          <path d="M8.5 6.8C9.9 6.8 11.1 7.3 12 8.2L13.1 7.1C11.8 5.9 10.2 5.1 8.5 5.1C6.8 5.1 5.2 5.9 3.9 7.1L5 8.2C5.9 7.3 7.1 6.8 8.5 6.8Z" fill={c}/>
          <circle cx="8.5" cy="10.5" r="1.5" fill={c}/>
        </svg>
        <svg width="27" height="13" viewBox="0 0 27 13">
          <rect x="0.5" y="0.5" width="23" height="12" rx="3.5" stroke={c} strokeOpacity="0.35" fill="none"/>
          <rect x="2" y="2" width="20" height="9" rx="2" fill={c}/>
          <path d="M25 4.5V8.5C25.8 8.2 26.5 7.2 26.5 6.5C26.5 5.8 25.8 4.8 25 4.5Z" fill={c} fillOpacity="0.4"/>
        </svg>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Liquid glass pill — blur + tint + shine
// ─────────────────────────────────────────────────────────────
function IOSGlassPill({ children, dark = false, style = {} }) {
  return (
    <div style={{
      height: 44, minWidth: 44, borderRadius: 9999,
      position: 'relative', overflow: 'hidden',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      boxShadow: dark
        ? '0 2px 6px rgba(0,0,0,0.35), 0 6px 16px rgba(0,0,0,0.2)'
        : '0 1px 3px rgba(0,0,0,0.07), 0 3px 10px rgba(0,0,0,0.06)',
      ...style,
    }}>
      {/* blur + tint */}
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 9999,
        backdropFilter: 'blur(12px) saturate(180%)',
        WebkitBackdropFilter: 'blur(12px) saturate(180%)',
        background: dark ? 'rgba(120,120,128,0.28)' : 'rgba(255,255,255,0.5)',
      }} />
      {/* shine */}
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 9999,
        boxShadow: dark
          ? 'inset 1.5px 1.5px 1px rgba(255,255,255,0.15), inset -1px -1px 1px rgba(255,255,255,0.08)'
          : 'inset 1.5px 1.5px 1px rgba(255,255,255,0.7), inset -1px -1px 1px rgba(255,255,255,0.4)',
        border: dark ? '0.5px solid rgba(255,255,255,0.15)' : '0.5px solid rgba(0,0,0,0.06)',
      }} />
      <div style={{ position: 'relative', zIndex: 1, display: 'flex', alignItems: 'center', padding: '0 4px' }}>
        {children}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Navigation bar — glass pills + large title
// ─────────────────────────────────────────────────────────────
function IOSNavBar({ title = 'Title', dark = false, trailingIcon = true }) {
  const muted = dark ? 'rgba(255,255,255,0.6)' : '#404040';
  const text = dark ? '#fff' : '#000';
  const pillIcon = (content) => (
    <IOSGlassPill dark={dark}>
      <div style={{ width: 36, height: 36, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        {content}
      </div>
    </IOSGlassPill>
  );
  return (
    <div style={{
      display: 'flex', flexDirection: 'column', gap: 10,
      paddingTop: 62, paddingBottom: 10, position: 'relative', zIndex: 5,
    }}>
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '0 16px',
      }}>
        {/* back chevron */}
        {pillIcon(
          <svg width="12" height="20" viewBox="0 0 12 20" fill="none" style={{ marginLeft: -1 }}>
            <path d="M10 2L2 10l8 8" stroke={muted} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        )}
        {/* trailing ellipsis */}
        {trailingIcon && pillIcon(
          <svg width="22" height="6" viewBox="0 0 22 6">
            <circle cx="3" cy="3" r="2.5" fill={muted}/>
            <circle cx="11" cy="3" r="2.5" fill={muted}/>
            <circle cx="19" cy="3" r="2.5" fill={muted}/>
          </svg>
        )}
      </div>
      {/* large title */}
      <div style={{
        padding: '0 16px',
        fontFamily: '-apple-system, system-ui',
        fontSize: 34, fontWeight: 700, lineHeight: '41px',
        color: text, letterSpacing: 0.4,
      }}>{title}</div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Grouped list (inset card, r:26) + row (52px)
// ─────────────────────────────────────────────────────────────
function IOSListRow({ title, detail, icon, chevron = true, isLast = false, dark = false }) {
  const text = dark ? '#fff' : '#000';
  const sec = dark ? 'rgba(235,235,245,0.6)' : 'rgba(60,60,67,0.6)';
  const ter = dark ? 'rgba(235,235,245,0.3)' : 'rgba(60,60,67,0.3)';
  const sep = dark ? 'rgba(84,84,88,0.65)' : 'rgba(60,60,67,0.12)';
  return (
    <div style={{
      display: 'flex', alignItems: 'center', minHeight: 52,
      padding: '0 16px', position: 'relative',
      fontFamily: '-apple-system, system-ui', fontSize: 17,
      letterSpacing: -0.43,
    }}>
      {icon && (
        <div style={{
          width: 30, height: 30, borderRadius: 7, background: icon,
          marginRight: 12, flexShrink: 0,
        }} />
      )}
      <div style={{ flex: 1, color: text }}>{title}</div>
      {detail && <span style={{ color: sec, marginRight: 6 }}>{detail}</span>}
      {chevron && (
        <svg width="8" height="14" viewBox="0 0 8 14" style={{ flexShrink: 0 }}>
          <path d="M1 1l6 6-6 6" stroke={ter} strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
      )}
      {!isLast && (
        <div style={{
          position: 'absolute', bottom: 0, right: 0,
          left: icon ? 58 : 16, height: 0.5, background: sep,
        }} />
      )}
    </div>
  );
}

function IOSList({ header, children, dark = false }) {
  const hc = dark ? 'rgba(235,235,245,0.6)' : 'rgba(60,60,67,0.6)';
  const bg = dark ? '#1C1C1E' : '#fff';
  return (
    <div>
      {header && (
        <div style={{
          fontFamily: '-apple-system, system-ui', fontSize: 13,
          color: hc, textTransform: 'uppercase',
          padding: '8px 36px 6px', letterSpacing: -0.08,
        }}>{header}</div>
      )}
      <div style={{
        background: bg, borderRadius: 26,
        margin: '0 16px', overflow: 'hidden',
      }}>{children}</div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Device frame
// ─────────────────────────────────────────────────────────────
function IOSDevice({
  children, width = 402, height = 874, dark = false,
  title, keyboard = false,
}) {
  return (
    <div style={{
      width, height, borderRadius: 48, overflow: 'hidden',
      position: 'relative', background: dark ? '#000' : '#F2F2F7',
      boxShadow: '0 40px 80px rgba(0,0,0,0.18), 0 0 0 1px rgba(0,0,0,0.12)',
      fontFamily: '-apple-system, system-ui, sans-serif',
      WebkitFontSmoothing: 'antialiased',
    }}>
      {/* dynamic island */}
      <div style={{
        position: 'absolute', top: 11, left: '50%', transform: 'translateX(-50%)',
        width: 126, height: 37, borderRadius: 24, background: '#000', zIndex: 50,
      }} />
      {/* status bar (absolute) */}
      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, zIndex: 10 }}>
        <IOSStatusBar dark={dark} />
      </div>
      {/* nav + content */}
      <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
        {title !== undefined && <IOSNavBar title={title} dark={dark} />}
        <div style={{ flex: 1, overflow: 'auto' }}>{children}</div>
        {keyboard && <IOSKeyboard dark={dark} />}
      </div>
      {/* home indicator — always on top */}
      <div style={{
        position: 'absolute', bottom: 0, left: 0, right: 0, zIndex: 60,
        height: 34, display: 'flex', justifyContent: 'center', alignItems: 'flex-end',
        paddingBottom: 8, pointerEvents: 'none',
      }}>
        <div style={{
          width: 139, height: 5, borderRadius: 100,
          background: dark ? 'rgba(255,255,255,0.7)' : 'rgba(0,0,0,0.25)',
        }} />
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Keyboard — iOS 26 liquid glass
// ─────────────────────────────────────────────────────────────
function IOSKeyboard({ dark = false }) {
  const glyph = dark ? 'rgba(255,255,255,0.7)' : '#595959';
  const sugg = dark ? 'rgba(255,255,255,0.6)' : '#333';
  const keyBg = dark ? 'rgba(255,255,255,0.22)' : 'rgba(255,255,255,0.85)';

  // special-key icons
  const icons = {
    shift: <svg width="19" height="17" viewBox="0 0 19 17"><path d="M9.5 1L1 9.5h4.5V16h8V9.5H18L9.5 1z" fill={glyph}/></svg>,
    del: <svg width="23" height="17" viewBox="0 0 23 17"><path d="M7 1h13a2 2 0 012 2v11a2 2 0 01-2 2H7l-6-7.5L7 1z" fill="none" stroke={glyph} strokeWidth="1.6" strokeLinejoin="round"/><path d="M10 5l7 7M17 5l-7 7" stroke={glyph} strokeWidth="1.6" strokeLinecap="round"/></svg>,
    ret: <svg width="20" height="14" viewBox="0 0 20 14"><path d="M18 1v6H4m0 0l4-4M4 7l4 4" fill="none" stroke="#fff" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg>,
  };

  const key = (content, { w, flex, ret, fs = 25, k } = {}) => (
    <div key={k} style={{
      height: 42, borderRadius: 8.5,
      flex: flex ? 1 : undefined, width: w, minWidth: 0,
      background: ret ? '#08f' : keyBg,
      boxShadow: '0 1px 0 rgba(0,0,0,0.075)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      fontFamily: '-apple-system, "SF Compact", system-ui',
      fontSize: fs, fontWeight: 458, color: ret ? '#fff' : glyph,
    }}>{content}</div>
  );

  const row = (keys, pad = 0) => (
    <div style={{ display: 'flex', gap: 6.5, justifyContent: 'center', padding: `0 ${pad}px` }}>
      {keys.map(l => key(l, { flex: true, k: l }))}
    </div>
  );

  return (
    <div style={{
      position: 'relative', zIndex: 15, borderRadius: 27, overflow: 'hidden',
      padding: '11px 0 2px',
      display: 'flex', flexDirection: 'column', alignItems: 'center',
      boxShadow: dark
        ? '0 -2px 20px rgba(0,0,0,0.09)'
        : '0 -1px 6px rgba(0,0,0,0.018), 0 -3px 20px rgba(0,0,0,0.012)',
    }}>
      {/* liquid glass bg — same recipe as nav pills */}
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 27,
        backdropFilter: 'blur(12px) saturate(180%)',
        WebkitBackdropFilter: 'blur(12px) saturate(180%)',
        background: dark ? 'rgba(120,120,128,0.14)' : 'rgba(255,255,255,0.25)',
      }} />
      <div style={{
        position: 'absolute', inset: 0, borderRadius: 27,
        boxShadow: dark
          ? 'inset 1.5px 1.5px 1px rgba(255,255,255,0.15)'
          : 'inset 1.5px 1.5px 1px rgba(255,255,255,0.7), inset -1px -1px 1px rgba(255,255,255,0.4)',
        border: dark ? '0.5px solid rgba(255,255,255,0.15)' : '0.5px solid rgba(0,0,0,0.06)',
        pointerEvents: 'none',
      }} />

      {/* autocorrect bar */}
      <div style={{
        display: 'flex', gap: 20, alignItems: 'center',
        padding: '8px 22px 13px', width: '100%', boxSizing: 'border-box',
        position: 'relative',
      }}>
        {['"The"', 'the', 'to'].map((w, i) => (
          <React.Fragment key={i}>
            {i > 0 && <div style={{ width: 1, height: 25, background: '#ccc', opacity: 0.3 }} />}
            <div style={{
              flex: 1, textAlign: 'center',
              fontFamily: '-apple-system, system-ui', fontSize: 17,
              color: sugg, letterSpacing: -0.43, lineHeight: '22px',
            }}>{w}</div>
          </React.Fragment>
        ))}
      </div>

      {/* key layout */}
      <div style={{
        display: 'flex', flexDirection: 'column', gap: 13,
        padding: '0 6.5px', width: '100%', boxSizing: 'border-box',
        position: 'relative',
      }}>
        {row(['q','w','e','r','t','y','u','i','o','p'])}
        {row(['a','s','d','f','g','h','j','k','l'], 20)}
        <div style={{ display: 'flex', gap: 14.25, alignItems: 'center' }}>
          {key(icons.shift, { w: 45, k: 'shift' })}
          <div style={{ display: 'flex', gap: 6.5, flex: 1 }}>
            {['z','x','c','v','b','n','m'].map(l => key(l, { flex: true, k: l }))}
          </div>
          {key(icons.del, { w: 45, k: 'del' })}
        </div>
        <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
          {key('ABC', { w: 92.25, fs: 18, k: 'abc' })}
          {key('', { flex: true, k: 'space' })}
          {key(icons.ret, { w: 92.25, ret: true, k: 'ret' })}
        </div>
      </div>

      {/* bottom spacer (emoji+mic area, icons omitted) */}
      <div style={{ height: 56, width: '100%', position: 'relative' }} />
    </div>
  );
}

Object.assign(window, {
  IOSDevice, IOSStatusBar, IOSNavBar, IOSGlassPill, IOSList, IOSListRow, IOSKeyboard,
});


// ===== android-frame.jsx =====

// Android.jsx — Simplified Android (Material 3) device frame
// Status bar + top app bar + content + gesture nav + keyboard.
// Based on Figma M3 spec. No dependencies, no image assets.

const MD_C = {
  surface: '#f4fbf8',
  surfaceVariant: '#dae5e1',
  inverseOnSurface: '#ecf2ef',
  secondaryContainer: '#cde8e1',
  primaryFixedDim: '#83d5c6',
  onSurface: '#171d1b',
  onSurfaceVar: '#49454f',
  onPrimaryContainer: '#00201c',
  primary: '#006a60',
  frameBorder: 'rgba(116,119,117,0.5)',
};

// ─────────────────────────────────────────────────────────────
// Status bar (time left, wifi/cell/battery right)
// ─────────────────────────────────────────────────────────────
function AndroidStatusBar({ dark = false }) {
  const c = dark ? '#fff' : MD_C.onSurface;
  return (
    <div style={{
      height: 40, display: 'flex', alignItems: 'center',
      justifyContent: 'space-between', padding: '0 16px',
      position: 'relative',
      fontFamily: 'Roboto, system-ui, sans-serif',
    }}>
      {/* time left */}
      <div style={{ width: 128, display: 'flex', alignItems: 'center', gap: 8 }}>
        <span style={{ fontSize: 14, fontWeight: 400, letterSpacing: 0.25, lineHeight: '20px', color: c }}>9:30</span>
      </div>
      {/* camera punch-hole (center) */}
      <div style={{
        position: 'absolute', left: '50%', top: 8, transform: 'translateX(-50%)',
        width: 24, height: 24, borderRadius: 100, background: '#2e2e2e',
      }} />
      {/* status icons right */}
      <div style={{ display: 'flex', alignItems: 'center' }}>
        <div style={{ display: 'flex', paddingRight: 2 }}>
          <svg width="16" height="16" viewBox="0 0 16 16" style={{ marginRight: -2 }}>
            <path d="M8 13.3L.67 5.97a10.37 10.37 0 0114.66 0L8 13.3z" fill={c}/>
          </svg>
          <svg width="16" height="16" viewBox="0 0 16 16" style={{ marginRight: -2 }}>
            <path d="M14.67 14.67V1.33L1.33 14.67h13.34z" fill={c}/>
          </svg>
        </div>
        <svg width="16" height="16" viewBox="0 0 16 16">
          <rect x="3.75" y="2" width="8.5" height="13" rx="1.5" fill={c}/>
          <rect x="5.5" y="0.9" width="5" height="2" rx="0.5" fill={c}/>
        </svg>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Top app bar (Material 3 small/medium)
// ─────────────────────────────────────────────────────────────
function AndroidAppBar({ title = 'Title', large = false }) {
  const iconDot = (
    <div style={{
      width: 48, height: 48, display: 'flex', alignItems: 'center', justifyContent: 'center',
    }}>
      <div style={{ width: 22, height: 22, borderRadius: '50%', background: MD_C.onSurfaceVar, opacity: 0.3 }} />
    </div>
  );
  return (
    <div style={{ background: MD_C.surface, padding: '4px 4px 0' }}>
      <div style={{ height: 56, display: 'flex', alignItems: 'center', gap: 4 }}>
        {iconDot}
        {!large && (
          <span style={{
            flex: 1, fontSize: 22, fontWeight: 400, color: MD_C.onSurface,
            fontFamily: 'Roboto, system-ui, sans-serif',
          }}>{title}</span>
        )}
        {large && <div style={{ flex: 1 }} />}
        {iconDot}
      </div>
      {large && (
        <div style={{
          padding: '16px 16px 20px',
          fontSize: 28, fontWeight: 400, color: MD_C.onSurface,
          fontFamily: 'Roboto, system-ui, sans-serif',
        }}>{title}</div>
      )}
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// List item (Material 3)
// ─────────────────────────────────────────────────────────────
function AndroidListItem({ headline, supporting, leading }) {
  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 16,
      padding: '12px 16px', minHeight: 56, boxSizing: 'border-box',
      fontFamily: 'Roboto, system-ui, sans-serif',
    }}>
      {leading && (
        <div style={{
          width: 40, height: 40, borderRadius: '50%',
          background: MD_C.primary, color: '#fff',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: 18, fontWeight: 500, flexShrink: 0,
        }}>{leading}</div>
      )}
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 16, color: MD_C.onSurface, lineHeight: '24px' }}>{headline}</div>
        {supporting && (
          <div style={{ fontSize: 14, color: MD_C.onSurfaceVar, lineHeight: '20px' }}>{supporting}</div>
        )}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Gesture nav bar (pill)
// ─────────────────────────────────────────────────────────────
function AndroidNavBar({ dark = false }) {
  return (
    <div style={{
      height: 24, display: 'flex', alignItems: 'center', justifyContent: 'center',
    }}>
      <div style={{
        width: 108, height: 4, borderRadius: 2,
        background: dark ? '#fff' : MD_C.onSurface, opacity: 0.4,
      }} />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Device frame — wraps everything
// ─────────────────────────────────────────────────────────────
function AndroidDevice({
  children, width = 412, height = 892, dark = false,
  title, large = false, keyboard = false,
}) {
  return (
    <div style={{
      width, height, borderRadius: 18, overflow: 'hidden',
      background: dark ? '#1d1b20' : MD_C.surface,
      border: `8px solid ${MD_C.frameBorder}`,
      boxShadow: '0 30px 80px rgba(0,0,0,0.25)',
      display: 'flex', flexDirection: 'column', boxSizing: 'border-box',
    }}>
      <AndroidStatusBar dark={dark} />
      {title !== undefined && <AndroidAppBar title={title} large={large} />}
      <div style={{ flex: 1, overflow: 'auto' }}>
        {children}
      </div>
      {keyboard && <AndroidKeyboard />}
      <AndroidNavBar dark={dark} />
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Keyboard — Gboard (Material 3)
// ─────────────────────────────────────────────────────────────
function AndroidKeyboard() {
  let _k = 0;
  const key = (l, { flex = 1, bg = MD_C.surface, r = 6, minW, fs = 21 } = {}) => (
    <div key={_k++} style={{
      height: 46, borderRadius: r, flex, minWidth: minW,
      background: bg, display: 'flex', alignItems: 'center', justifyContent: 'center',
      fontFamily: 'Roboto, system-ui', fontSize: fs,
      color: MD_C.onPrimaryContainer,
    }}>{l}</div>
  );
  const row = (keys, style = {}) => (
    <div style={{ display: 'flex', gap: 6, justifyContent: 'center', ...style }}>
      {keys.map(l => key(l))}
    </div>
  );
  return (
    <div style={{
      background: MD_C.inverseOnSurface, padding: '0 8px 8px',
      display: 'flex', flexDirection: 'column', gap: 4,
    }}>
      {/* navbar spacer (icons omitted) */}
      <div style={{ height: 44 }} />
      {/* key rows */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
        {row(['q','w','e','r','t','y','u','i','o','p'])}
        {row(['a','s','d','f','g','h','j','k','l'], { padding: '0 20px' })}
        <div style={{ display: 'flex', gap: 6 }}>
          {key('', { bg: MD_C.surfaceVariant })}
          <div style={{ display: 'flex', gap: 6, flex: 7, minWidth: 274 }}>
            {['z','x','c','v','b','n','m'].map(l => key(l))}
          </div>
          {key('', { bg: MD_C.surfaceVariant })}
        </div>
        <div style={{ display: 'flex', gap: 6 }}>
          {key('?123', { bg: MD_C.secondaryContainer, r: 100, minW: 58, fs: 14 })}
          {key(',', { bg: MD_C.surfaceVariant })}
          {key('', { flex: 3, minW: 154 })}
          {key('.', { bg: MD_C.surfaceVariant })}
          {key('', { bg: MD_C.primaryFixedDim, r: 100, minW: 58 })}
        </div>
      </div>
    </div>
  );
}

Object.assign(window, {
  AndroidDevice, AndroidStatusBar, AndroidAppBar, AndroidListItem, AndroidNavBar, AndroidKeyboard,
});


// ===== tiers.jsx =====
// SUNX Sense Tier System — 8 screens, same format
// Free vs Pro · SP economy · Fog of data · envlab.ai · Pro reports · Hardware unlock

const TI_PRIMARY = 'oklch(0.65 0.14 230)';
const TI_ACCENT  = 'oklch(0.72 0.14 155)';
const TI_AMBER   = 'oklch(0.78 0.14 75)';
const TI_RED     = 'oklch(0.62 0.18 25)';
const TI_VIOLET  = 'oklch(0.62 0.18 295)';
const TI_GOLD    = 'oklch(0.80 0.13 80)';

function tiHex(cx, cy, r) {
  const pts = [];
  for (let i = 0; i < 6; i++) {
    const a = Math.PI / 3 * i - Math.PI / 2;
    pts.push([cx + Math.cos(a) * r, cy + Math.sin(a) * r]);
  }
  return 'M ' + pts.map(p => p.join(' ')).join(' L ') + ' Z';
}

const TIER_COPY = {
  en: {
    headerEyebrow: 'SUNX SENSE · TIER SYSTEM',
    headerTitle: 'A free that feels alive. A Pro that sees everything.',
    headerSub: 'Tiers, SP economy, fog of data, envlab.ai, exposure reports, hardware unlocks.',
    screens: [
      { id: 'tiers',     eyebrow: '01 · TIERS',           title: 'Explore the planet. Or understand it.',          body: 'Free users discover, participate, earn SP. Pro users get full environmental intelligence — deep zoom, history, AI, exposure reports.', cta: 'Try Pro 7 days free' },
      { id: 'heatmap',   eyebrow: '02 · HEATMAP ACCESS',  title: 'Free sees the city. Pro sees the room.',         body: 'Free users browse global → city level. District, street, and building layers stay behind a fog you can sense, but not enter.',           cta: 'Unlock with 10 SP' },
      { id: 'wallet',    eyebrow: '03 · SP WALLET',       title: 'Behavioral currency.',                            body: 'Sense Points are earned through participation and spent on temporary unlocks — district zoom, history, AI queries, even temporary Pro.', cta: 'See ways to earn' },
      { id: 'unlock',    eyebrow: '04 · UNLOCK',          title: 'Open a district for 24 hours.',                   body: 'Tap a locked area and trade SP for time-bound access. Cheap unlocks for curiosity, full Pro for daily use.',                            cta: 'Unlock · 10 SP' },
      { id: 'envlab',    eyebrow: '05 · ENVLAB.AI',       title: 'Ask the air a question.',                         body: 'Free users pay 5 SP per query. Pro users ask as often as they breathe.',                                                                  cta: 'Ask (5 SP)' },
      { id: 'exposure',  eyebrow: '06 · EXPOSURE',        title: 'What you actually breathed this week.',           body: 'Daily, weekly, and monthly exposure across CO₂, PM, and VOC. Free users get a 30-day trial, then Pro continues the story.',             cta: 'See trends' },
      { id: 'replay',    eyebrow: '07 · REPLAY',          title: 'Your year in air.',                               body: 'A Spotify-Wrapped style recap: cleanest hours, dirtiest commutes, exposure milestones, and the places that treated your lungs best.',  cta: 'Open my replay' },
      { id: 'hardware',  eyebrow: '08 · HARDWARE = PRO',  title: 'A Carbostar earns Pro by existing.',              body: 'Carbostar and SX Miner owners receive Pro automatically — no subscription, with potential SP earning multipliers ahead.',                cta: 'Pair a device' },
    ],
    free: 'Free',
    pro: 'Pro',
    tagFree: 'Explore the planet.',
    tagPro: 'Understand your environment.',
    sp: 'SP',
    spBalance: 'Sense Points',
    locked: 'Locked',
    foggy: 'Foggy',
    earn: 'Earn',
    spend: 'Spend',
    activeNow: 'ACTIVE NOW',
    proActive: 'PRO ACTIVE',
    trialDay: 'Day 18 of 30 · trial',
    earnMethods: [
      { name: 'Daily check-in',        sp: '+5/day',   color: TI_ACCENT },
      { name: 'Declaration',           sp: '+3 ea.',    color: TI_PRIMARY },
      { name: 'Anomaly report',        sp: '+25',       color: TI_AMBER },
      { name: 'Carbostar sync',        sp: '+10/hr',   color: TI_VIOLET },
      { name: 'Route tracking',        sp: '+8/route', color: 'oklch(0.62 0.16 200)' },
      { name: 'Quiz · 5 questions',    sp: '+15',       color: TI_GOLD },
    ],
    unlockOptions: [
      { name: 'District zoom · 24h',   sp: 10,  active: true  },
      { name: 'Building insight',      sp: 15,  active: false },
      { name: '7-day history',         sp: 20,  active: false },
      { name: '30-day history',        sp: 100, active: false },
      { name: '1 day Pro',             sp: 50,  active: false },
      { name: '1 week Pro',            sp: 250, active: false },
    ],
    aiQueries: [
      'Best low-PM running route nearby?',
      'Which hours today have cleaner air?',
      'Lowest CO₂ coworking spaces nearby?',
      'Best district for children today?',
    ],
    exposureMetrics: [
      { name: 'CO₂',  unit: 'ppm·hr', value: 4820, delta: -8,  color: TI_PRIMARY },
      { name: 'PM2.5',unit: 'µg·hr',  value: 612,  delta: +14, color: TI_AMBER   },
      { name: 'VOC',  unit: 'ppb·hr', value: 218,  delta: -2,  color: TI_ACCENT  },
    ],
    replayCards: [
      { metric: 'Cleanest hour', value: '06:14', sub: 'Mon · Maçka Park · 388 ppm' },
      { metric: 'Worst commute', value: 'Tue 8:42', sub: 'Mecidiyeköy crossing · 1,420 ppm' },
      { metric: 'Best place',    value: 'Atatürk Arboretum', sub: '24 visits this year' },
      { metric: 'Lifetime',      value: '2,140 hrs', sub: 'of air measured' },
    ],
    hardware: [
      { name: 'PX Carbostar', sub: 'Portable CO₂ · BLE 5.0', state: 'paired',    color: TI_ACCENT },
      { name: 'SX Miner',     sub: 'Stationary node · WiFi', state: 'available', color: TI_PRIMARY },
    ],
  },
  tr: {
    headerEyebrow: 'SUNX SENSE · KATMAN SİSTEMİ',
    headerTitle: 'Yaşayan bir Free. Her şeyi gören bir Pro.',
    headerSub: 'Katmanlar, SP ekonomisi, veri sisi, envlab.ai, maruziyet raporları, donanım kilitleri.',
    screens: [
      { id: 'tiers',     eyebrow: '01 · KATMANLAR',         title: 'Gezegeni keşfet. Ya da onu anla.',                body: 'Free kullanıcı keşfeder, katılır, SP kazanır. Pro kullanıcı tam çevre zekâsı alır — derin zoom, tarih, AI, maruziyet raporları.', cta: 'Pro\u2019yu 7 gün dene' },
      { id: 'heatmap',   eyebrow: '02 · ISI HARİTASI',      title: 'Free şehri görür. Pro odayı görür.',              body: 'Free kullanıcı küresel → şehir seviyesini gezer. İlçe, sokak ve bina katmanları, hissedilen ama açılmayan bir sis ardında kalır.', cta: '10 SP ile aç' },
      { id: 'wallet',    eyebrow: '03 · SP CÜZDAN',         title: 'Davranışsal para birimi.',                        body: 'Sense Points katılımla kazanılır, geçici kilitleri açmak için harcanır — ilçe zoom, tarih, AI sorusu, hatta geçici Pro.',         cta: 'Kazanma yollarını gör' },
      { id: 'unlock',    eyebrow: '04 · KİLİT AÇ',          title: 'Bir ilçeyi 24 saatliğine aç.',                    body: 'Kilitli bir alana dokun ve SP\u2019yle zaman sınırlı erişim al. Merak için ucuz açımlar, günlük kullanım için tam Pro.',           cta: 'Aç · 10 SP' },
      { id: 'envlab',    eyebrow: '05 · ENVLAB.AI',         title: 'Havaya bir soru sor.',                            body: 'Free kullanıcı sorgu başına 5 SP öder. Pro kullanıcı nefes alır gibi sorar.',                                                          cta: 'Sor (5 SP)' },
      { id: 'exposure',  eyebrow: '06 · MARUZİYET',         title: 'Bu hafta gerçekten ne soluduğun.',                body: 'CO₂, PM ve VOC için günlük, haftalık, aylık maruziyet. Free kullanıcı 30 gün deneme alır, sonra hikâyeyi Pro sürdürür.',             cta: 'Trendleri gör' },
      { id: 'replay',    eyebrow: '07 · REPLAY',            title: 'Yılın · hava.',                                   body: 'Spotify Wrapped tarzı bir özet: en temiz saatler, en kirli yolculuklar, maruziyet kilometre taşları ve ciğerlerine en iyi davranan yerler.', cta: 'Replay\u2019imi aç' },
      { id: 'hardware',  eyebrow: '08 · DONANIM = PRO',     title: 'Carbostar varlığıyla Pro kazandırır.',            body: 'Carbostar ve SX Miner sahipleri otomatik Pro alır — abonelik yok, ileride SP kazanma çarpanları olası.',                              cta: 'Cihaz eşle' },
    ],
    free: 'Free',
    pro: 'Pro',
    tagFree: 'Gezegeni keşfet.',
    tagPro: 'Çevreni anla.',
    sp: 'SP',
    spBalance: 'Sense Points',
    locked: 'Kilitli',
    foggy: 'Sisli',
    earn: 'Kazan',
    spend: 'Harca',
    activeNow: 'ŞU AN AKTİF',
    proActive: 'PRO AKTİF',
    trialDay: '30 günün 18. günü · deneme',
    earnMethods: [
      { name: 'Günlük giriş',         sp: '+5/gün',     color: TI_ACCENT },
      { name: 'Deklarasyon',          sp: '+3 adet',    color: TI_PRIMARY },
      { name: 'Anomali bildirimi',    sp: '+25',        color: TI_AMBER },
      { name: 'Carbostar senkron',    sp: '+10/saat',   color: TI_VIOLET },
      { name: 'Rota kaydı',           sp: '+8/rota',    color: 'oklch(0.62 0.16 200)' },
      { name: 'Quiz · 5 soru',        sp: '+15',        color: TI_GOLD },
    ],
    unlockOptions: [
      { name: 'İlçe zoom · 24sa',     sp: 10,  active: true  },
      { name: 'Bina içgörüsü',        sp: 15,  active: false },
      { name: '7 günlük tarih',       sp: 20,  active: false },
      { name: '30 günlük tarih',      sp: 100, active: false },
      { name: '1 gün Pro',            sp: 50,  active: false },
      { name: '1 hafta Pro',          sp: 250, active: false },
    ],
    aiQueries: [
      'Düşük PM\u2019li koşu rotası?',
      'Bugün hangi saatler daha temiz?',
      'En düşük CO₂\u2019li coworking?',
      'Çocuk için en iyi ilçe bugün?',
    ],
    exposureMetrics: [
      { name: 'CO₂',  unit: 'ppm·sa', value: 4820, delta: -8,  color: TI_PRIMARY },
      { name: 'PM2.5',unit: 'µg·sa',  value: 612,  delta: +14, color: TI_AMBER   },
      { name: 'VOC',  unit: 'ppb·sa', value: 218,  delta: -2,  color: TI_ACCENT  },
    ],
    replayCards: [
      { metric: 'En temiz saat',    value: '06:14', sub: 'Pzt · Maçka Parkı · 388 ppm' },
      { metric: 'En kötü yol',      value: 'Sal 8:42', sub: 'Mecidiyeköy kavşağı · 1.420 ppm' },
      { metric: 'En iyi yer',       value: 'Atatürk Arboretumu', sub: 'Bu yıl 24 ziyaret' },
      { metric: 'Toplam',           value: '2.140 sa', sub: 'havayla ölçülmüş' },
    ],
    hardware: [
      { name: 'PX Carbostar', sub: 'Taşınabilir CO₂ · BLE 5.0', state: 'paired',    color: TI_ACCENT },
      { name: 'SX Miner',     sub: 'Sabit düğüm · WiFi',         state: 'available', color: TI_PRIMARY },
    ],
  },
};

// ─────────────────────────────────────────────────────────────
// 1. TIERS — Free vs Pro side by side
// ─────────────────────────────────────────────────────────────
function TiTiers({ dark, lang }) {
  const c = TIER_COPY[lang];

  const Row = ({ label, free, pro }) => (
    <div style={{ display: 'grid', gridTemplateColumns: '1fr 36px 36px', gap: 8, alignItems: 'center',
      padding: '6px 0',
      borderBottom: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)'}` }}>
      <div style={{ fontFamily: 'Geist', fontSize: 11.5,
        color: dark ? 'rgba(255,255,255,0.75)' : 'rgba(20,30,50,0.75)' }}>{label}</div>
      <div style={{ textAlign: 'center' }}>{free ? <Check color={TI_ACCENT}/> : <Dash dark={dark}/>}</div>
      <div style={{ textAlign: 'center' }}>{pro ? <Check color={TI_GOLD}/> : <Dash dark={dark}/>}</div>
    </div>
  );

  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', gap: 12 }}>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
        {/* Free card */}
        <div style={{ padding: 14, borderRadius: 14,
          background: dark ? 'oklch(0.20 0.02 225)' : 'rgba(255,255,255,0.85)',
          border: `1px solid ${dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)'}` }}>
          <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
            color: TI_ACCENT }}>{c.free.toUpperCase()}</div>
          <div style={{ fontFamily: 'Geist', fontSize: 26, fontWeight: 600, marginTop: 2, letterSpacing: -0.8,
            color: dark ? '#fff' : '#0a1420' }}>$0</div>
          <div style={{ fontFamily: 'Geist', fontSize: 11, marginTop: 4,
            color: dark ? 'rgba(255,255,255,0.55)' : 'rgba(20,30,50,0.55)', textWrap: 'balance' }}>{c.tagFree}</div>
        </div>
        {/* Pro card */}
        <div style={{ padding: 14, borderRadius: 14,
          background: 'linear-gradient(135deg, oklch(0.22 0.04 250), oklch(0.16 0.02 230))',
          border: `1px solid ${TI_GOLD}55`,
          position: 'relative', overflow: 'hidden' }}>
          <div style={{ position: 'absolute', top: -10, right: -10, opacity: 0.3 }}>
            <svg width="80" height="80" viewBox="-40 -40 80 80">
              <path d={tiHex(0,0,30)} fill="none" stroke={TI_GOLD} strokeWidth="1.5"/>
              <path d={tiHex(0,0,18)} fill={TI_GOLD} opacity="0.5"/>
            </svg>
          </div>
          <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
            color: TI_GOLD }}>{c.pro.toUpperCase()}</div>
          <div style={{ fontFamily: 'Geist', fontSize: 26, fontWeight: 600, marginTop: 2, letterSpacing: -0.8,
            color: '#fff' }}>$5<span style={{ fontSize: 12, color: 'rgba(255,255,255,0.5)' }}>/mo</span></div>
          <div style={{ fontFamily: 'Geist', fontSize: 11, marginTop: 4,
            color: 'rgba(255,255,255,0.65)', textWrap: 'balance' }}>{c.tagPro}</div>
        </div>
      </div>

      {/* Comparison rows */}
      <div style={{ padding: '4px 14px 8px', borderRadius: 14,
        background: dark ? 'oklch(0.18 0.012 225)' : 'rgba(255,255,255,0.6)',
        border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}` }}>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 36px 36px', gap: 8,
          fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
          color: dark ? 'rgba(255,255,255,0.4)' : 'rgba(20,30,50,0.4)',
          padding: '8px 0 6px', borderBottom: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)'}` }}>
          <span>FEATURE</span><span style={{ textAlign: 'center' }}>FREE</span><span style={{ textAlign: 'center' }}>PRO</span>
        </div>
        <Row label="City-level heatmap" free pro />
        <Row label="District / street zoom" free={false} pro />
        <Row label="Building insights" free={false} pro />
        <Row label="24-hour history" free pro />
        <Row label="Unlimited history" free={false} pro />
        <Row label="envlab.ai queries" free={false} pro />
        <Row label="Exposure reports" free={false} pro />
        <Row label="Environmental Replay" free={false} pro />
      </div>
    </div>
  );
}
function Check({ color }) {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16">
      <circle cx="8" cy="8" r="7" fill={color} opacity="0.18"/>
      <path d="M5 8l2 2 4-4" stroke={color} strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  );
}
function Dash({ dark }) {
  return <div style={{ width: 12, height: 2, borderRadius: 1,
    background: dark ? 'rgba(255,255,255,0.18)' : 'rgba(0,0,0,0.18)', margin: '0 auto' }} />;
}

// ─────────────────────────────────────────────────────────────
// 2. HEATMAP — fog of data, zoom levels
// ─────────────────────────────────────────────────────────────
function TiHeatmap({ dark, lang }) {
  const c = TIER_COPY[lang];
  const W = 342, H = 220;
  const cx = W/2, cy = H/2;

  // hex tiles around center; outer ring foggy
  const tiles = [];
  const r = 16;
  const dx = r * Math.sqrt(3);
  const dy = r * 1.5;
  for (let row = -5; row <= 5; row++) {
    for (let col = -6; col <= 6; col++) {
      const x = cx + col*dx + (row%2 ? dx/2 : 0);
      const y = cy + row*dy;
      const d = Math.hypot(x-cx, y-cy);
      if (d > 130) continue;
      tiles.push({ x, y, d });
    }
  }
  // give some tiles colors (city-level visible)
  const colorByDist = (d) => {
    if (d < 35) return TI_AMBER;
    if (d < 70) return 'oklch(0.78 0.14 95)';
    return TI_ACCENT;
  };

  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', gap: 12 }}>
      {/* map */}
      <div style={{ position: 'relative', width: W, height: H,
        borderRadius: 18, overflow: 'hidden',
        background: dark ? 'oklch(0.17 0.015 225)' : 'oklch(0.98 0.008 225)',
        border: `1px solid ${dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)'}` }}>
        <svg width={W} height={H}>
          <defs>
            <radialGradient id="fogmask" cx="50%" cy="50%" r="50%">
              <stop offset="0%" stopColor="#fff" stopOpacity="1"/>
              <stop offset="55%" stopColor="#fff" stopOpacity="1"/>
              <stop offset="100%" stopColor="#fff" stopOpacity="0.05"/>
            </radialGradient>
            <filter id="blur1"><feGaussianBlur stdDeviation="2"/></filter>
          </defs>
          {tiles.map((t, i) => {
            const foggy = t.d > 90;
            return (
              <path key={i} d={tiHex(t.x, t.y, r-1)}
                fill={foggy ? (dark ? 'rgba(140,180,255,0.08)' : 'rgba(20,90,180,0.05)') : colorByDist(t.d)}
                stroke={dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'} strokeWidth="0.8"
                opacity={foggy ? 0.4 : 0.85}
                filter={foggy ? 'url(#blur1)' : undefined}
              />
            );
          })}
          {/* center crosshair */}
          <circle cx={cx} cy={cy} r="3" fill={TI_PRIMARY}
            style={{ animation: 'dotBreath 1.4s ease-in-out infinite', transformOrigin: `${cx}px ${cy}px` }}/>
        </svg>

        {/* lock chip at foggy edge */}
        <div style={{ position: 'absolute', right: 18, top: 16,
          padding: '6px 10px', borderRadius: 100,
          background: dark ? 'rgba(15,25,35,0.9)' : 'rgba(255,255,255,0.95)',
          border: `1px solid ${dark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.06)'}`,
          fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
          color: dark ? 'rgba(255,255,255,0.7)' : 'rgba(20,30,50,0.7)',
          display: 'flex', alignItems: 'center', gap: 6,
        }}>
          <Lock size={10} color={TI_AMBER}/>
          {c.foggy.toUpperCase()} · STREET LV
        </div>

        {/* zoom levels indicator */}
        <div style={{ position: 'absolute', left: 16, bottom: 14,
          fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.2,
          color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)' }}>
          ZOOM · CITY · 50KM RADIUS
        </div>
      </div>

      {/* zoom ladder */}
      <div style={{ padding: '8px 12px', borderRadius: 14,
        background: dark ? 'oklch(0.18 0.012 225)' : 'rgba(255,255,255,0.6)',
        border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}`,
        display: 'flex', flexDirection: 'column', gap: 0 }}>
        {[
          { lv: 'Global',   open: true },
          { lv: 'City',     open: true },
          { lv: 'District', open: false, cost: '10 SP' },
          { lv: 'Street',   open: false, cost: '10 SP' },
          { lv: 'Building', open: false, cost: '15 SP' },
        ].map((z, i, arr) => (
          <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10,
            padding: '8px 4px',
            borderBottom: i < arr.length-1 ? `1px solid ${dark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.04)'}` : 'none'
          }}>
            <div style={{ width: 14, height: 14, borderRadius: 4,
              background: z.open ? TI_ACCENT : 'transparent',
              border: z.open ? 'none' : `1.5px solid ${dark ? 'rgba(255,255,255,0.3)' : 'rgba(0,0,0,0.25)'}`,
              display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              {z.open ? <svg width="9" height="9" viewBox="0 0 9 9"><path d="M2 4.5l2 2 3-4" stroke="#fff" strokeWidth="1.6" fill="none" strokeLinecap="round" strokeLinejoin="round"/></svg>
                : <Lock size={8} color={dark ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.3)'}/>}
            </div>
            <span style={{ flex: 1, fontFamily: 'Geist', fontSize: 12,
              color: dark ? '#fff' : '#0a1420',
              opacity: z.open ? 1 : 0.7 }}>{z.lv}</span>
            <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
              color: z.open ? TI_ACCENT : TI_PRIMARY }}>
              {z.open ? c.activeNow : z.cost}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}
function Lock({ size = 12, color = '#888' }) {
  return (
    <svg width={size} height={size} viewBox="0 0 12 12">
      <rect x="2.5" y="5.5" width="7" height="5" rx="1" fill={color}/>
      <path d="M4 5.5V4a2 2 0 014 0v1.5" stroke={color} strokeWidth="1.4" fill="none"/>
    </svg>
  );
}

// ─────────────────────────────────────────────────────────────
// 3. SP WALLET — balance + earn methods
// ─────────────────────────────────────────────────────────────
function TiWallet({ dark, lang }) {
  const c = TIER_COPY[lang];
  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', gap: 10 }}>
      {/* balance card */}
      <div style={{ padding: 18, borderRadius: 18,
        background: 'linear-gradient(135deg, oklch(0.22 0.04 250), oklch(0.16 0.02 230))',
        border: `1px solid rgba(255,255,255,0.06)`,
        position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', right: -20, bottom: -30, opacity: 0.2 }}>
          <svg width="160" height="160" viewBox="-80 -80 160 160">
            <path d={tiHex(0,0,60)} fill="none" stroke={TI_PRIMARY} strokeWidth="1.5"/>
            <path d={tiHex(0,0,40)} fill="none" stroke={TI_PRIMARY} strokeWidth="1" strokeDasharray="2 4"/>
            <text x="0" y="6" textAnchor="middle" fontFamily="Geist" fontWeight="700" fontSize="22" fill={TI_PRIMARY}>SP</text>
          </svg>
        </div>
        <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
          color: 'rgba(255,255,255,0.5)' }}>{c.spBalance.toUpperCase()}</div>
        <div style={{ fontFamily: 'Geist', fontSize: 50, fontWeight: 600, lineHeight: 1, letterSpacing: -1.8,
          fontVariantNumeric: 'tabular-nums', color: '#fff', marginTop: 4 }}>284<span style={{ fontSize: 18, color: TI_PRIMARY, marginLeft: 6 }}>SP</span></div>
        <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.2,
          color: TI_ACCENT, marginTop: 4 }}>+38 THIS WEEK · 0 SPENT</div>
      </div>

      {/* earn methods */}
      <div style={{ padding: '4px 0', borderRadius: 14,
        background: dark ? 'oklch(0.18 0.012 225)' : 'rgba(255,255,255,0.6)',
        border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}` }}>
        <div style={{ padding: '10px 14px 6px',
          fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
          color: dark ? 'rgba(255,255,255,0.4)' : 'rgba(20,30,50,0.4)' }}>{c.earn.toUpperCase()}</div>
        {c.earnMethods.map((m, i) => (
          <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10,
            padding: '8px 14px',
            borderTop: `1px solid ${dark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.04)'}` }}>
            <div style={{ width: 6, height: 22, borderRadius: 3, background: m.color }} />
            <span style={{ flex: 1, fontFamily: 'Geist', fontSize: 12, fontWeight: 500,
              color: dark ? '#fff' : '#0a1420' }}>{m.name}</span>
            <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 11, letterSpacing: 0.5,
              fontWeight: 600, color: m.color, fontVariantNumeric: 'tabular-nums' }}>{m.sp}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 4. UNLOCK — district unlock interaction modal
// ─────────────────────────────────────────────────────────────
function TiUnlock({ dark, lang }) {
  const c = TIER_COPY[lang];

  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', gap: 10 }}>
      {/* primary unlock card */}
      <div style={{ padding: 18, borderRadius: 18,
        background: dark ? 'oklch(0.20 0.02 225)' : 'rgba(255,255,255,0.9)',
        border: `1.5px solid ${TI_PRIMARY}`,
        boxShadow: `0 8px 30px ${TI_PRIMARY}33` }}>

        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Lock size={14} color={TI_PRIMARY}/>
            <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
              color: TI_PRIMARY }}>UNLOCK · 24 HOURS</span>
          </div>
          <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.2,
            color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)' }}>23:59:48</span>
        </div>

        <div style={{ marginTop: 12, fontFamily: 'Geist', fontSize: 22, fontWeight: 600, letterSpacing: -0.6,
          color: dark ? '#fff' : '#0a1420' }}>Çankaya · Kavaklıdere</div>
        <div style={{ fontFamily: 'Geist', fontSize: 12, marginTop: 2,
          color: dark ? 'rgba(255,255,255,0.55)' : 'rgba(20,30,50,0.55)' }}>2.4 km² · 412 active sensors · 1,820 declarations</div>

        {/* SP cost line */}
        <div style={{ marginTop: 14, padding: '12px 14px', borderRadius: 12,
          background: dark ? 'rgba(120,180,255,0.08)' : 'rgba(20,90,200,0.06)',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div>
            <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.2,
              color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)' }}>COST</div>
            <div style={{ fontFamily: 'Geist', fontSize: 22, fontWeight: 600, marginTop: 2,
              color: TI_PRIMARY }}>10 <span style={{ fontSize: 11, fontFamily: 'Geist Mono, ui-monospace, monospace', letterSpacing: 1 }}>SP</span></div>
          </div>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.2,
              color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)' }}>BALANCE AFTER</div>
            <div style={{ fontFamily: 'Geist', fontSize: 16, fontWeight: 500, marginTop: 4,
              color: dark ? '#fff' : '#0a1420' }}>284 → <span style={{ color: TI_ACCENT }}>274</span></div>
          </div>
        </div>
      </div>

      {/* other options */}
      <div style={{ padding: '4px 0', borderRadius: 14,
        background: dark ? 'oklch(0.18 0.012 225)' : 'rgba(255,255,255,0.6)',
        border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}` }}>
        <div style={{ padding: '10px 14px 6px',
          fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
          color: dark ? 'rgba(255,255,255,0.4)' : 'rgba(20,30,50,0.4)' }}>OTHER UNLOCKS</div>
        {c.unlockOptions.slice(1).map((o, i) => (
          <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10,
            padding: '8px 14px',
            borderTop: `1px solid ${dark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.04)'}` }}>
            <Lock size={11} color={dark ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)'}/>
            <span style={{ flex: 1, fontFamily: 'Geist', fontSize: 12,
              color: dark ? '#fff' : '#0a1420' }}>{o.name}</span>
            <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 11, letterSpacing: 0.5,
              fontWeight: 600, color: TI_PRIMARY }}>{o.sp} SP</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 5. ENVLAB.AI — query interface
// ─────────────────────────────────────────────────────────────
function TiEnvlab({ dark, lang }) {
  const c = TIER_COPY[lang];

  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', gap: 10 }}>
      {/* AI orb hero */}
      <div style={{ padding: 16, borderRadius: 18,
        background: 'linear-gradient(160deg, oklch(0.22 0.04 250), oklch(0.16 0.02 230))',
        border: `1px solid rgba(255,255,255,0.06)`,
        position: 'relative', overflow: 'hidden',
        display: 'flex', alignItems: 'center', gap: 14 }}>
        {/* orb */}
        <div style={{ position: 'relative', width: 64, height: 64,
          display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          {[0,1,2].map(i => (
            <div key={i} style={{
              position: 'absolute', width: 64, height: 64, borderRadius: '50%',
              border: `1px solid ${TI_VIOLET}`, opacity: 0.4,
              animation: 'haloBreath 2.5s ease-in-out infinite',
              animationDelay: `${i * 0.4}s`,
            }} />
          ))}
          <div style={{
            width: 36, height: 36, borderRadius: '50%',
            background: `radial-gradient(circle at 35% 30%, #fff, ${TI_VIOLET})`,
            boxShadow: `0 0 24px ${TI_VIOLET}`,
            animation: 'dotBreath 1.6s ease-in-out infinite',
          }}/>
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
            color: 'rgba(255,255,255,0.55)' }}>ENVLAB · AI</div>
          <div style={{ fontFamily: 'Geist', fontSize: 18, fontWeight: 600, color: '#fff', marginTop: 2, letterSpacing: -0.4 }}>
            Ask the air.
          </div>
          <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
            color: TI_ACCENT, marginTop: 4 }}>5 SP / QUERY · UNLIMITED FOR PRO</div>
        </div>
      </div>

      {/* suggested queries */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
        {c.aiQueries.map((q, i) => (
          <div key={i} style={{ padding: '10px 12px', borderRadius: 10,
            background: dark ? 'oklch(0.18 0.012 225)' : 'rgba(255,255,255,0.6)',
            border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}`,
            display: 'flex', alignItems: 'center', gap: 10 }}>
            <div style={{ width: 22, height: 22, borderRadius: '50%',
              background: dark ? 'rgba(120,180,255,0.10)' : 'rgba(20,90,200,0.08)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              color: TI_PRIMARY, fontFamily: 'Geist', fontSize: 12, fontWeight: 600 }}>?</div>
            <span style={{ flex: 1, fontFamily: 'Geist', fontSize: 12,
              color: dark ? '#fff' : '#0a1420' }}>{q}</span>
            <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 10, letterSpacing: 0.8,
              color: TI_PRIMARY, fontWeight: 600 }}>5 SP</span>
          </div>
        ))}
      </div>

      {/* input field */}
      <div style={{ padding: '10px 12px', borderRadius: 12,
        background: dark ? 'oklch(0.16 0.012 225)' : '#fff',
        border: `1.5px dashed ${TI_VIOLET}55`,
        fontFamily: 'Geist', fontSize: 12,
        color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <span>Type your question…</span>
        <div style={{ width: 24, height: 24, borderRadius: '50%',
          background: TI_PRIMARY,
          display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <svg width="12" height="12" viewBox="0 0 12 12"><path d="M2 6h7m-3-3l3 3-3 3" stroke="#fff" strokeWidth="1.8" fill="none" strokeLinecap="round" strokeLinejoin="round"/></svg>
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 6. EXPOSURE REPORT — Pro weekly recap (or trial)
// ─────────────────────────────────────────────────────────────
function TiExposure({ dark, lang }) {
  const c = TIER_COPY[lang];

  // sparkline for CO2 exposure across 7 days
  const W = 310, H = 80;
  const pts = [0.5, 0.7, 0.4, 0.85, 0.6, 0.55, 0.42].map((v, i, arr) => {
    const x = (i / (arr.length-1)) * (W - 16) + 8;
    const y = H - 12 - v * (H - 22);
    return [x, y];
  });
  const sparkD = pts.reduce((a, [x,y], i) => a + (i===0?`M ${x} ${y}`:` L ${x} ${y}`), '');
  const sparkArea = sparkD + ` L ${pts[pts.length-1][0]} ${H-6} L ${pts[0][0]} ${H-6} Z`;

  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', gap: 10 }}>
      {/* Pro-trial banner */}
      <div style={{ padding: '8px 12px', borderRadius: 10,
        background: dark ? 'rgba(180,220,160,0.10)' : 'rgba(50,150,80,0.08)',
        border: `1px solid ${TI_ACCENT}55`,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ width: 6, height: 6, borderRadius: '50%', background: TI_ACCENT,
            animation: 'dotBreath 1.5s ease-in-out infinite' }} />
          <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.2,
            color: TI_ACCENT, fontWeight: 600 }}>{c.trialDay.toUpperCase()}</span>
        </div>
        <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
          color: dark ? 'rgba(255,255,255,0.4)' : 'rgba(20,30,50,0.4)' }}>12 DAYS LEFT</span>
      </div>

      {/* CO2 hero */}
      <div style={{ padding: '14px 16px', borderRadius: 14,
        background: dark ? 'oklch(0.20 0.02 225)' : 'rgba(255,255,255,0.85)',
        border: `1px solid ${dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)'}` }}>
        <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between' }}>
          <div>
            <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.5,
              color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)' }}>WEEK 19 · CO₂ EXPOSURE</div>
            <div style={{ fontFamily: 'Geist', fontSize: 34, fontWeight: 600, marginTop: 2, letterSpacing: -1.2,
              fontVariantNumeric: 'tabular-nums', color: dark ? '#fff' : '#0a1420' }}>4,820 <span style={{ fontSize: 13, color: TI_PRIMARY }}>ppm·hr</span></div>
          </div>
          <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 11, letterSpacing: 0.8,
            color: TI_ACCENT, fontWeight: 600 }}>▼ 8%</div>
        </div>
        <svg width={W} height={H} style={{ marginTop: 6, marginLeft: -2 }}>
          <defs>
            <linearGradient id="expFill" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor={TI_PRIMARY} stopOpacity="0.35"/>
              <stop offset="100%" stopColor={TI_PRIMARY} stopOpacity="0"/>
            </linearGradient>
          </defs>
          <path d={sparkArea} fill="url(#expFill)"/>
          <path d={sparkD} stroke={TI_PRIMARY} strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/>
          {pts.map(([x,y], i) => (
            <circle key={i} cx={x} cy={y} r={i === pts.length-1 ? 4 : 2.5} fill={TI_PRIMARY}/>
          ))}
        </svg>
        <div style={{ display: 'flex', justifyContent: 'space-between',
          fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 8.5, letterSpacing: 1,
          color: dark ? 'rgba(255,255,255,0.35)' : 'rgba(20,30,50,0.35)', marginTop: 2 }}>
          <span>MON</span><span>TUE</span><span>WED</span><span>THU</span><span>FRI</span><span>SAT</span><span>SUN</span>
        </div>
      </div>

      {/* other metrics */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
        {c.exposureMetrics.slice(1).map((m, i) => (
          <div key={i} style={{ padding: '12px 14px', borderRadius: 12,
            background: dark ? 'oklch(0.18 0.012 225)' : 'rgba(255,255,255,0.6)',
            border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}` }}>
            <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.2,
              color: m.color, fontWeight: 600 }}>{m.name.toUpperCase()}</div>
            <div style={{ fontFamily: 'Geist', fontSize: 22, fontWeight: 600, marginTop: 2, letterSpacing: -0.6,
              fontVariantNumeric: 'tabular-nums', color: dark ? '#fff' : '#0a1420' }}>{m.value.toLocaleString()}</div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: 2,
              fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 0.8 }}>
              <span style={{ color: dark ? 'rgba(255,255,255,0.4)' : 'rgba(20,30,50,0.4)' }}>{m.unit}</span>
              <span style={{ color: m.delta > 0 ? TI_AMBER : TI_ACCENT, fontWeight: 600 }}>
                {m.delta > 0 ? '▲' : '▼'} {Math.abs(m.delta)}%
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 7. ENVIRONMENTAL REPLAY — Spotify-Wrapped style
// ─────────────────────────────────────────────────────────────
function TiReplay({ dark, lang }) {
  const c = TIER_COPY[lang];

  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', gap: 10 }}>
      {/* Big wrapped card */}
      <div style={{ padding: 20, borderRadius: 22,
        background: `linear-gradient(150deg, ${TI_VIOLET}, oklch(0.45 0.18 280), ${TI_PRIMARY})`,
        position: 'relative', overflow: 'hidden',
        minHeight: 150 }}>
        <div style={{ position: 'absolute', right: -30, top: -30, opacity: 0.4 }}>
          <svg width="200" height="200" viewBox="-100 -100 200 200">
            {[80, 60, 40, 20].map((rr,i) => (
              <path key={i} d={tiHex(0,0,rr)} fill="none" stroke="#fff" strokeWidth="1" opacity={0.4 - i*0.08}/>
            ))}
          </svg>
        </div>

        <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 2.5,
          color: 'rgba(255,255,255,0.7)' }}>SUNX · REPLAY 2026</div>
        <div style={{ fontFamily: 'Geist', fontSize: 32, fontWeight: 600, marginTop: 6, lineHeight: 1.05,
          letterSpacing: -1, color: '#fff', textWrap: 'balance' }}>
          Your year<br/>in air.
        </div>
        <div style={{ marginTop: 12, fontFamily: 'Geist', fontSize: 12,
          color: 'rgba(255,255,255,0.75)' }}>2,140 hours · 18,200 measurements</div>
      </div>

      {/* recap cards */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
        {c.replayCards.map((r, i) => (
          <div key={i} style={{ padding: 12, borderRadius: 12,
            background: dark ? 'oklch(0.18 0.012 225)' : 'rgba(255,255,255,0.7)',
            border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}` }}>
            <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 8.5, letterSpacing: 1.2,
              color: dark ? 'rgba(255,255,255,0.45)' : 'rgba(20,30,50,0.45)' }}>{r.metric.toUpperCase()}</div>
            <div style={{ fontFamily: 'Geist', fontSize: 15, fontWeight: 600, marginTop: 2, lineHeight: 1.15,
              color: dark ? '#fff' : '#0a1420', letterSpacing: -0.2 }}>{r.value}</div>
            <div style={{ fontFamily: 'Geist', fontSize: 10.5, marginTop: 4, lineHeight: 1.4,
              color: dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)' }}>{r.sub}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// 8. HARDWARE = PRO — Carbostar / SX Miner auto-unlock
// ─────────────────────────────────────────────────────────────
function TiHardware({ dark, lang }) {
  const c = TIER_COPY[lang];

  return (
    <div style={{ width: 342, display: 'flex', flexDirection: 'column', gap: 10 }}>
      {/* Pro Active hero */}
      <div style={{ padding: 16, borderRadius: 18,
        background: 'linear-gradient(135deg, oklch(0.22 0.04 250), oklch(0.16 0.02 230))',
        border: `1.5px solid ${TI_GOLD}55`,
        position: 'relative', overflow: 'hidden' }}>
        <div style={{ position: 'absolute', right: -16, top: -16, opacity: 0.25 }}>
          <svg width="130" height="130" viewBox="-65 -65 130 130">
            <path d={tiHex(0,0,52)} fill="none" stroke={TI_GOLD} strokeWidth="1.5"/>
            <path d={tiHex(0,0,38)} fill="none" stroke={TI_GOLD} strokeWidth="1" strokeDasharray="2 4"/>
            <path d={tiHex(0,0,24)} fill={TI_GOLD} opacity="0.4"/>
          </svg>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ width: 6, height: 6, borderRadius: '50%', background: TI_GOLD,
            animation: 'dotBreath 1.5s ease-in-out infinite' }} />
          <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1.8,
            color: TI_GOLD, fontWeight: 600 }}>{c.proActive}</span>
        </div>
        <div style={{ marginTop: 8, fontFamily: 'Geist', fontSize: 22, fontWeight: 600, letterSpacing: -0.6,
          lineHeight: 1.15, color: '#fff', textWrap: 'balance' }}>
          Carbostar paired.<br/>Pro unlocked.
        </div>
        <div style={{ marginTop: 6, fontFamily: 'Geist', fontSize: 11.5,
          color: 'rgba(255,255,255,0.65)' }}>No subscription. Indefinite access while device is active.</div>
      </div>

      {/* device list */}
      <div style={{ padding: '4px 0', borderRadius: 14,
        background: dark ? 'oklch(0.18 0.012 225)' : 'rgba(255,255,255,0.6)',
        border: `1px solid ${dark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)'}` }}>
        {c.hardware.map((h, i, arr) => {
          const paired = h.state === 'paired';
          return (
            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 12,
              padding: '12px 14px',
              borderTop: i > 0 ? `1px solid ${dark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.04)'}` : 'none'
            }}>
              <div style={{ width: 42, height: 42, borderRadius: 10,
                background: paired
                  ? `linear-gradient(135deg, ${h.color}33, ${h.color}11)`
                  : (dark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.04)'),
                border: paired ? `1px solid ${h.color}55` : 'none',
                display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative' }}>
                {paired ? (
                  <div style={{ width: 10, height: 10, borderRadius: '50%', background: h.color,
                    boxShadow: `0 0 10px ${h.color}`,
                    animation: 'dotBreath 1.4s ease-in-out infinite' }} />
                ) : (
                  <Lock size={14} color={dark ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)'}/>
                )}
                <div style={{ position: 'absolute', right: 4, top: 6, width: 4, height: 28,
                  background: paired
                    ? `repeating-linear-gradient(to bottom, transparent 0 2px, ${h.color}aa 2px 3px)`
                    : 'transparent',
                  borderRadius: 2 }} />
              </div>
              <div style={{ flex: 1 }}>
                <div style={{ fontFamily: 'Geist', fontSize: 13, fontWeight: 600,
                  color: dark ? '#fff' : '#0a1420' }}>{h.name}</div>
                <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1,
                  color: dark ? 'rgba(255,255,255,0.45)' : 'rgba(20,30,50,0.45)', marginTop: 2 }}>{h.sub}</div>
              </div>
              <span style={{
                padding: '4px 8px', borderRadius: 100,
                fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 9, letterSpacing: 1, fontWeight: 600,
                color: paired ? h.color : (dark ? 'rgba(255,255,255,0.5)' : 'rgba(20,30,50,0.5)'),
                background: paired ? `${h.color}22` : (dark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.05)'),
              }}>{paired ? 'PAIRED' : 'AVAILABLE'}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

const TIER_COMPONENTS = [TiTiers, TiHeatmap, TiWallet, TiUnlock, TiEnvlab, TiExposure, TiReplay, TiHardware];

// ─────────────────────────────────────────────────────────────
// Screen shell — identical chrome to gamification
// ─────────────────────────────────────────────────────────────
function TierScreen({ dark, lang, device, idx }) {
  const c = TIER_COPY[lang];
  const screen = c.screens[idx];
  const Hero = TIER_COMPONENTS[idx];

  return (
    <div key={idx} style={{
      width: '100%', height: '100%', position: 'relative',
      display: 'flex', flexDirection: 'column',
      background: dark ? 'oklch(0.14 0.015 225)' : 'oklch(0.985 0.008 220)',
      animation: 'fadeSlide 0.5s ease-out',
      fontFamily: 'Geist, Inter, -apple-system, system-ui, sans-serif',
    }}>
      <div style={{
        paddingTop: device === 'ios' ? 58 : 48,
        paddingLeft: 20, paddingRight: 20,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{ width: 20, height: 20, borderRadius: 6,
            background: 'linear-gradient(135deg, oklch(0.65 0.14 230), oklch(0.72 0.14 155))',
            boxShadow: '0 2px 6px rgba(20,90,180,0.25)' }} />
          <span style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 11, letterSpacing: 2, fontWeight: 500,
            color: dark ? 'rgba(255,255,255,0.7)' : 'rgba(20,30,50,0.6)' }}>SUNX · SENSE</span>
        </div>
        <div style={{ fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 10, letterSpacing: 1.5,
          color: dark ? 'rgba(255,255,255,0.45)' : 'rgba(20,30,50,0.45)' }}>
          {String(idx+1).padStart(2,'0')} / 08
        </div>
      </div>

      <div style={{ margin: '20px auto 0', display: 'flex', justifyContent: 'center' }}>
        <Hero dark={dark} lang={lang} />
      </div>

      <div style={{ margin: '14px 24px 0',
        fontFamily: 'Geist Mono, ui-monospace, monospace', fontSize: 10, letterSpacing: 1.8,
        color: TI_PRIMARY, fontWeight: 500 }}>{screen.eyebrow}</div>

      <div style={{ padding: '8px 24px 0', flex: 1 }}>
        <h1 style={{ fontFamily: 'Geist', fontWeight: 600, fontSize: 22, lineHeight: 1.18, letterSpacing: -0.6,
          color: dark ? '#fff' : '#0a1420', margin: '0 0 8px', textWrap: 'balance' }}>{screen.title}</h1>
        <p style={{ fontFamily: 'Geist', fontSize: 13, lineHeight: 1.5,
          color: dark ? 'rgba(255,255,255,0.6)' : 'rgba(20,30,50,0.6)',
          margin: 0, textWrap: 'pretty' }}>{screen.body}</p>
      </div>

      <div style={{ padding: '0 24px', paddingBottom: device === 'ios' ? 40 : 32 }}>
        <button style={{
          width: '100%', height: 50, border: 'none', borderRadius: 14,
          background: 'linear-gradient(135deg, oklch(0.65 0.14 230), oklch(0.58 0.16 220))',
          color: '#fff', fontFamily: 'Geist', fontSize: 14, fontWeight: 600,
          cursor: 'pointer',
          boxShadow: '0 8px 20px rgba(20,90,200,0.3)',
          display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
        }}>
          {screen.cta}
          <svg width="14" height="14" viewBox="0 0 14 14"><path d="M2 7h10m-4-4l4 4-4 4" stroke="currentColor" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round"/></svg>
        </button>
      </div>
    </div>
  );
}

window.TierScreen = TierScreen;
window.TIER_COPY = TIER_COPY;


// ===== inline block =====
const { useState, useEffect } = React;

function App() {
  const [state, setState] = useState(() => ({ ...TWEAK_DEFAULS }));
  const set = (k, v) => {
    setState(s => ({ ...s, [k]: v }));
    window.parent.postMessage({ type: '__edit_mode_set_keys', edits: { [k]: v } }, '*');
  };

  useEffect(() => {
    document.body.classList.toggle('dark', state.dark);
    const copy = window.TIER_COPY[state.lang];
    document.getElementById('hdr-eyebrow').textContent = copy.headerEyebrow;
    document.getElementById('hdr-title').textContent = copy.headerTitle;
    document.getElementById('hdr-sub').textContent = copy.headerSub;
  }, [state.dark, state.lang]);

  const screens = window.TIER_COPY[state.lang].screens;

  return (
    <>
      <div className="grid">
        {screens.map((s, i) => {
          const content = (
            <window.TierScreen
              dark={state.dark} lang={state.lang} device={state.device} idx={i}
            />
          );
          const phone = state.device === 'ios'
            ? <window.IOSDevice dark={state.dark} width={390} height={844}>{content}</window.IOSDevice>
            : <window.AndroidDevice dark={state.dark} width={390} height={844}>{content}</window.AndroidDevice>;

          return (
            <div key={i} data-screen-label={`${String(i+1).padStart(2,'0')} ${s.id}`}>
              {phone}
              <div className="label">{s.eyebrow}</div>
            </div>
          );
        })}
      </div>

      <div className="tweaks">
        <h3>Tweaks</h3>
        <div className="tweak-row">
          <span>Theme</span>
          <div className="seg">
            <button className={!state.dark ? 'active' : ''} onClick={() => set('dark', false)}>LIGHT</button>
            <button className={state.dark ? 'active' : ''} onClick={() => set('dark', true)}>DARK</button>
          </div>
        </div>
        <div className="tweak-row">
          <span>Language</span>
          <div className="seg">
            <button className={state.lang === 'en' ? 'active' : ''} onClick={() => set('lang', 'en')}>EN</button>
            <button className={state.lang === 'tr' ? 'active' : ''} onClick={() => set('lang', 'tr')}>TR</button>
          </div>
        </div>
        <div className="tweak-row">
          <span>Device</span>
          <div className="seg">
            <button className={state.device === 'ios' ? 'active' : ''} onClick={() => set('device', 'ios')}>iOS</button>
            <button className={state.device === 'android' ? 'active' : ''} onClick={() => set('device', 'android')}>AND</button>
          </div>
        </div>
      </div>
    </>
  );
}

setTimeout(() => {
  ReactDOM.createRoot(document.getElementById('root')).render(<App />);
}, 100);
