// Concatenates all <script type="text/babel"> blocks and src=*.jsx into one main.jsx per page.
// Keeps the existing window.X global bridging pattern intact.
import fs from 'node:fs';
import path from 'node:path';

const SRC = path.resolve(import.meta.dirname, '..');
const OUT = path.resolve(import.meta.dirname, 'src');

const pages = [
  { name: 'onboarding',   html: 'SUNX Sense Onboarding.html'   },
  { name: 'gamification', html: 'SUNX Sense Gamification.html' },
  { name: 'tiers',        html: 'SUNX Sense Tiers.html'        },
  { name: 'consent',      html: 'SUNX Sense Consent.html'      },
];

// Match <script type="text/babel" ...>...</script> (inline or external src=)
const RE = /<script\s+type="text\/babel"(?:\s+src="([^"]+)")?\s*>([\s\S]*?)<\/script>/g;
// Also capture the leading plain <script> (TWEAK_DEFAULS block) — we keep it inline in HTML.

for (const p of pages) {
  const html = fs.readFileSync(path.join(SRC, p.html), 'utf8');
  const parts = [];
  let m;
  while ((m = RE.exec(html)) !== null) {
    const [, src, body] = m;
    if (src) {
      const ext = fs.readFileSync(path.join(SRC, src), 'utf8');
      parts.push(`// ===== ${src} =====\n${ext}`);
    } else {
      parts.push(`// ===== inline block =====\n${body.trim()}`);
    }
  }

  const out = [
    `// Auto-generated by extract.mjs from "${p.html}".`,
    `// Edit the individual sections below; HMR will pick up changes.`,
    `import React from 'react';`,
    `import ReactDOM from 'react-dom/client';`,
    `// Babel-standalone code expected React/ReactDOM as globals.`,
    `window.React = React;`,
    `window.ReactDOM = ReactDOM;`,
    ``,
    parts.join('\n\n'),
    ``,
  ].join('\n');

  // The original code uses ReactDOM.createRoot(...).render(...). React 18's
  // react-dom/client only exports createRoot, not the legacy ReactDOM.render —
  // patch the global so existing calls keep working.
  const patched = out.replace(
    `window.ReactDOM = ReactDOM;`,
    `window.ReactDOM = { createRoot: ReactDOM.createRoot };`
  );

  const outPath = path.join(OUT, p.name, 'main.jsx');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, patched);
  console.log(`wrote ${outPath} (${parts.length} script blocks)`);
}
